import type * as app_session from '@ankoh/dashql-jsonschema/app_session.js';
import type { TopLevelSpec } from 'vega-lite';

/// Notebook type definitions (migrated from protobuf)
///
/// These types represent the runtime state of the notebook editor.
/// Storage format types (NotebookMetadata, NotebookOriginType) come from JSON Schema.

// Re-export storage format types from JSON Schema
export type NotebookMetadata = app_session.NotebookMetadata;
export type NotebookOriginType = NonNullable<app_session.NotebookMetadata['originType']>;

/// A visualize statement resolved against the notebook (SQL + parsed Vega-Lite spec).
export interface ResolvedVisualizeQuery {
    // The SQL to execute against the backend
    sql: string;
    // The Vega-Lite spec generated by the analyzer
    vegaLiteSpec: TopLevelSpec;
}

/// Script annotations derived from analysis
export interface NotebookScriptAnnotations {
    // The table references
    tableRefs: string[];
    // The table definitions
    tableDefs: string[];
    // The restricted columns
    restrictedColumns: string[];
    // The resolved VISUALIZE query for this script, if any.
    visualizeQuery: ResolvedVisualizeQuery | null;
}

/// A script in the notebook (runtime representation)
export interface NotebookScript {
    // The script id
    scriptId: number;
    // The script text
    scriptText: string;
    // The script annotations
    annotations: NotebookScriptAnnotations;
}

/// A script reference in a notebook page
export interface NotebookPageScript {
    // The script id
    scriptId: number;
    // The explicit file name (e.g., "01-script.sql")
    fileName: string;
}

/// A notebook page containing script references, keyed by file name
export interface NotebookPage {
    // The folder name for this page
    folderName: string;
    // The entries (script references) keyed by file name
    scripts: { [fileName: string]: NotebookPageScript };
}

/// Complete notebook structure (runtime representation)
export interface Notebook {
    // The connection params (if any)
    connectionParams?: any; // ConnectionParams from JSON Schema
    // The scripts
    scripts: NotebookScript[];
    // The notebook pages keyed by folder name
    notebookPages: { [folderName: string]: NotebookPage };
    // The notebook metadata
    notebookMetadata: NotebookMetadata;
    // The uncommitted script id (0 = unset)
    uncommittedScriptId: number;
}

/// Helper to create empty annotations
export function createEmptyAnnotations(): NotebookScriptAnnotations {
    return {
        tableRefs: [],
        tableDefs: [],
        restrictedColumns: [],
        visualizeQuery: null,
    };
}

/// Helper to create empty metadata
export function createEmptyMetadata(): NotebookMetadata {
    return {
        originType: 'LOCAL',
        originalFileName: '',
        originalHttpUrl: '',
    };
}

/// A leading numeric ordering prefix on a page folder name, e.g. "03_" in "03_main".
///
/// The prefix encodes the tab order *on disk* (folders sort lexicographically, so a
/// zero-padded numeric prefix yields the desired tab order). It is deliberately hidden from
/// the UI and from the logical SQL-reference namespace: a page's clean name is its stable
/// identity, so reordering a tab (which rewrites the prefix) must not change its display
/// label or break cross-script references that point at it.
///
/// Anchored at the start and requires the `<digits>_` shape. Note the known ambiguity: a page
/// a user literally names `2024_report` parses as prefix `2024` + clean `report`. This is
/// accepted as part of the lean "prefix lives in the folder name" model.
const PAGE_ORDER_PREFIX_RE = /^(\d+)_/;

/// The display / logical name of a page, with any storage ordering prefix removed.
/// "03_main" -> "main"; "main" -> "main".
export function stripPageOrderPrefix(folderName: string): string {
    return folderName.replace(PAGE_ORDER_PREFIX_RE, '');
}

/// The leading ordering prefix of a page folder name *including* the trailing underscore
/// ("03_main" -> "03_"), or the empty string if the folder carries none. Used to preserve a
/// page's position across a rename.
export function pageOrderPrefixString(folderName: string): string {
    const m = PAGE_ORDER_PREFIX_RE.exec(folderName);
    return m ? m[0] : '';
}

/// Format a 1-based ordering prefix, zero-padded to just the digit count required by `total`
/// (total <= 9 -> "1_"; total in 10..99 -> "01_"). The uniform width keeps a plain
/// lexicographic sort of the resulting folder names in numeric order.
export function formatPageOrderPrefix(index1: number, total: number): string {
    const width = String(Math.max(total, 1)).length;
    return `${String(index1).padStart(width, '0')}_`;
}

/// Helper to generate a script file name that doesn't collide with existing entries
export function generateScriptFileName(existingScripts: { [fileName: string]: NotebookPageScript }): string {
    const count = Object.keys(existingScripts).length;
    let index = count + 1;
    let candidate = `${String(index).padStart(2, '0')}-script.sql`;
    while (existingScripts[candidate] !== undefined) {
        index++;
        candidate = `${String(index).padStart(2, '0')}-script.sql`;
    }
    return candidate;
}

/// Helper to create an empty page
export function createEmptyPage(folderName: string = 'Untitled'): NotebookPage {
    return {
        folderName,
        scripts: {},
    };
}

/// Helper to create a page script entry
export function createPageScript(scriptId: number, fileName: string): NotebookPageScript {
    return {
        scriptId,
        fileName,
    };
}
