import type { TopLevelSpec } from 'vega-lite';

import * as buffers from '../core/buffers.js';
import { resolveSymbolSpan } from '../core/tokens.js';
import { ScriptData } from '../notebook/notebook_state.js';
import { NotebookState } from '../notebook/notebook_state.js';

/**
 * Resolves the executable SQL for a single VISUALIZE statement.
 *
 * Returns null if the script does not contain a VIS_VISUALISE statement, or if
 * the source could not be resolved to executable SQL.
 */
export interface ResolvedVisualizeQuery {
    /// The SQL to execute against the backend
    sql: string;
    /// The Vega-Lite spec generated by the analyzer (the `data` field is filled in client-side)
    vegaLiteSpec: TopLevelSpec;
}

function quoteIdent(name: string): string {
    return '"' + name.replace(/"/g, '""') + '"';
}

function findScriptByQualifiedPath(notebook: NotebookState, path: string): ScriptData | null {
    for (const key in notebook.scripts) {
        const data = notebook.scripts[key];
        if (!data.folderName || !data.fileName) continue;
        const fullPath = `${data.folderName}/${data.fileName}`;
        if (fullPath === path) return data;
    }
    return null;
}

export function resolveVisualizeQuery(scriptData: ScriptData, notebook: NotebookState): ResolvedVisualizeQuery | null {
    const analyzedPtr = scriptData.scriptAnalysis.buffers.analyzed;
    const parsedPtr = scriptData.scriptAnalysis.buffers.parsed;
    if (!analyzedPtr || !parsedPtr) return null;

    const analyzed = analyzedPtr.read();
    if (analyzed.visualizationSpecsLength() === 0) return null;

    const tmpSpec = new buffers.analyzer.VisualizationSpec();
    const spec = analyzed.visualizationSpecs(0, tmpSpec);
    if (!spec) return null;

    const vegaLiteSpecRaw = spec.vegaliteSpec();
    if (!vegaLiteSpecRaw) return null;
    let vegaLiteSpec: TopLevelSpec;
    try {
        vegaLiteSpec = JSON.parse(vegaLiteSpecRaw) as TopLevelSpec;
    } catch {
        return null;
    }

    const scriptText = scriptData.script.toString();
    const sourceKind = spec.sourceKind();

    let sql: string | null = null;
    switch (sourceKind) {
        case buffers.analyzer.VisSourceKind.SCRIPT_REFERENCE: {
            const tmpName = new buffers.analyzer.QualifiedTableName();
            const qname = spec.sourceQualifiedName(tmpName);
            const tableName = qname?.tableName() ?? null;
            if (tableName) {
                const target = findScriptByQualifiedPath(notebook, tableName);
                if (target) {
                    sql = target.script.toString();
                }
            }
            break;
        }
        case buffers.analyzer.VisSourceKind.TABLE_REFERENCE: {
            const tmpName = new buffers.analyzer.QualifiedTableName();
            const qname = spec.sourceQualifiedName(tmpName);
            if (qname) {
                const parts: string[] = [];
                const db = qname.databaseName();
                const schema = qname.schemaName();
                const tbl = qname.tableName();
                if (db) parts.push(quoteIdent(db));
                if (schema) parts.push(quoteIdent(schema));
                if (tbl) parts.push(quoteIdent(tbl));
                if (parts.length > 0) {
                    sql = `SELECT * FROM ${parts.join('.')}`;
                }
            }
            break;
        }
        case buffers.analyzer.VisSourceKind.INLINE_SELECT: {
            const nodeId = spec.sourceInlineSelectAstNodeId();
            const parsed = parsedPtr.read();
            const tokens = parsed.tokens();
            const node = parsed.nodes(nodeId);
            const span = node?.symbolSpan() ?? null;
            if (tokens && span) {
                const ts = resolveSymbolSpan(tokens, span);
                // Strip the wrapping parentheses inserted by the grammar (`LRB sql_select_stmt RRB`)
                const inner = scriptText.substr(ts.offset + 1, Math.max(ts.length - 2, 0));
                sql = inner.trim();
            }
            break;
        }
        default:
            break;
    }

    if (!sql) return null;
    return { sql, vegaLiteSpec };
}
