/* eslint-disable */
import { flatbuffers } from "flatbuffers";
// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export enum SQLTypeID{
  SQL_INVALID= 0,
  SQL_NULL= 1,
  SQL_UNKNOWN= 2,
  SQL_ANY= 3,
  SQL_BOOLEAN= 10,
  SQL_TINYINT= 11,
  SQL_SMALLINT= 12,
  SQL_INTEGER= 13,
  SQL_BIGINT= 14,
  SQL_DATE= 15,
  SQL_TIME= 16,
  SQL_TIMESTAMP= 17,
  SQL_FLOAT= 18,
  SQL_DOUBLE= 19,
  SQL_DECIMAL= 20,
  SQL_CHAR= 21,
  SQL_VARCHAR= 22,
  SQL_VARBINARY= 23,
  SQL_BLOB= 24,
  SQL_STRUCT= 100,
  SQL_LIST= 101
};

/**
 * @constructor
 */
export class SQLType {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SQLType
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SQLType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SQLType= obj
 * @returns SQLType
 */
static getRootAsSQLType(bb:flatbuffers.ByteBuffer, obj?:SQLType):SQLType {
  return (obj || new SQLType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SQLType= obj
 * @returns SQLType
 */
static getSizePrefixedRootAsSQLType(bb:flatbuffers.ByteBuffer, obj?:SQLType):SQLType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SQLType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns SQLTypeID
 */
typeId():SQLTypeID {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : SQLTypeID.SQL_INVALID;
};

/**
 * @returns number
 */
width():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
scale():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
collation():string|null
collation(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
collation(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSQLType(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param SQLTypeID typeId
 */
static addTypeId(builder:flatbuffers.Builder, typeId:SQLTypeID) {
  builder.addFieldInt8(0, typeId, SQLTypeID.SQL_INVALID);
};

/**
 * @param flatbuffers.Builder builder
 * @param number width
 */
static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt16(1, width, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number scale
 */
static addScale(builder:flatbuffers.Builder, scale:number) {
  builder.addFieldInt8(2, scale, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset collationOffset
 */
static addCollation(builder:flatbuffers.Builder, collationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, collationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSQLType(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSQLType(builder:flatbuffers.Builder, typeId:SQLTypeID, width:number, scale:number, collationOffset:flatbuffers.Offset):flatbuffers.Offset {
  SQLType.startSQLType(builder);
  SQLType.addTypeId(builder, typeId);
  SQLType.addWidth(builder, width);
  SQLType.addScale(builder, scale);
  SQLType.addCollation(builder, collationOffset);
  return SQLType.endSQLType(builder);
}
}
