/* eslint-disable */
import { flatbuffers } from "flatbuffers";
// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum AConstType{
  INTEGER= 0,
  FLOAT= 1,
  STRING= 2,
  BITSTRING= 3,
  NULL_= 4
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum AExprKind{
  AEXPR_OP= 0,
  AEXPR_OP_ANY= 1,
  AEXPR_OP_ALL= 2,
  AEXPR_DISTINCT= 3,
  AEXPR_NOT_DISTINCT= 4,
  AEXPR_NULLIF= 5,
  AEXPR_OF= 6,
  AEXPR_IN= 7,
  AEXPR_LIKE= 8,
  AEXPR_ILIKE= 9,
  AEXPR_GLOB= 10,
  AEXPR_SIMILAR= 11,
  AEXPR_BETWEEN= 12,
  AEXPR_NOT_BETWEEN= 13,
  AEXPR_BETWEEN_SYM= 14,
  AEXPR_NOT_BETWEEN_SYM= 15,
  AEXPR_PAREN= 16
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum TempType{
  TEMP_DEFAULT= 0,
  TEMP_GLOBAL= 1,
  TEMP_LOCAL= 2,
  TEMP_UNLOGGED= 3
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum WindowBoundMode{
  NONE= 0,
  UNBOUNDED= 1,
  CURRENT_ROW= 2,
  VALUE= 3
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum WindowBoundDirection{
  NONE= 0,
  PRECEDING= 1,
  FOLLOWING= 2
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum WindowRangeMode{
  NONE= 0,
  RANGE= 1,
  ROWS= 2,
  GROUPS= 3
};
}

/**
 * @enum {number}
 */
export namespace dashql.proto.syntax_sql{
export enum WindowExclusionMode{
  NONE= 0,
  CURRENT_ROW= 1,
  GROUP= 2,
  TIES= 3
};
}

