CORE_WASM_EXPORTS = [
    "'_dashql_malloc'",
    "'_dashql_free'",
    "'_dashql_delete_owner'",
    "'_dashql_agent_session_new'",
    "'_dashql_agent_session_start'",
    "'_dashql_agent_session_complete_effect'",
    "'_dashql_agent_session_cancel'",
    "'_dashql_editor_session_new'",
    "'_dashql_editor_session_destroy'",
    "'_dashql_editor_session_get_catalog_entry_id'",
    "'_dashql_editor_session_get_text'",
    "'_dashql_editor_session_get_document_revision'",
    "'_dashql_editor_session_get_state_revision'",
    "'_dashql_editor_session_get_catalog_revision'",
    "'_dashql_editor_session_replace_text'",
    "'_dashql_editor_session_apply'",
    "'_dashql_editor_session_set_primary_cursor'",
    "'_dashql_editor_session_ensure_analysis'",
    "'_dashql_editor_session_complete_at_cursor'",
    "'_dashql_editor_session_compile_query'",
    "'_dashql_editor_session_format'",
    "'_dashql_editor_session_is_fully_formattable'",
    "'_dashql_editor_session_compute_diff'",
    "'_dashql_editor_session_load_into_catalog'",
    "'_dashql_editor_session_drop_from_catalog'",
    "'_dashql_catalog_new'",
    "'_dashql_catalog_clear'",
    "'_dashql_catalog_contains_entry_id'",
    "'_dashql_catalog_describe_entries'",
    "'_dashql_catalog_describe_entries_of'",
    "'_dashql_catalog_load_script'",
    "'_dashql_catalog_load_scripts'",
    "'_dashql_catalog_drop_script'",
    "'_dashql_catalog_get_statistics'",
    "'_dashql_catalog_flatten'",
    "'_dashql_parse_vegalite_to_visualize'",
    "'_dashql_script_new'",
    "'_dashql_script_get_catalog_entry_id'",
    "'_dashql_script_insert_text_at'",
    "'_dashql_script_insert_char_at'",
    "'_dashql_script_erase_text_range'",
    "'_dashql_script_replace_text'",
    "'_dashql_script_to_string'",
    "'_dashql_script_get_statement_text'",
    "'_dashql_script_compile_query'",
    "'_dashql_script_scan'",
    "'_dashql_script_parse'",
    "'_dashql_script_analyze'",
    "'_dashql_script_analyze_async'",
    "'_dashql_script_analysis_job_get_error_code'",
    "'_dashql_script_analysis_job_get_error_message'",
    "'_dashql_script_analysis_job_cancel'",
    "'_dashql_script_analysis_job_release'",
    "'_dashql_script_get_scanned'",
    "'_dashql_script_get_parsed'",
    "'_dashql_script_get_analyzed'",
    "'_dashql_script_compute_diff'",
    "'_dashql_script_get_statistics'",
    "'_dashql_script_format'",
    "'_dashql_script_is_fully_formattable'",
    "'_dashql_script_get_unformattable_nodes'",
    "'_dashql_script_move_cursor'",
    "'_dashql_script_complete_at_cursor'",
    "'_dashql_plan_view_model_configure'",
    "'_dashql_plan_view_model_load_hyper_plan'",
    "'_dashql_plan_view_model_new'",
    "'_dashql_plan_view_model_pack'",
    "'_dashql_plan_view_model_reset'",
    "'_dashql_plan_view_model_reset_execution'",
]

SHELL_WASM_EXPORTS = [
    "'_dashql_shell_new'",
    "'_dashql_shell_destroy'",
    "'_dashql_shell_resize'",
    "'_dashql_shell_session_relations_set'",
    "'_dashql_shell_commands_set'",
    "'_dashql_shell_prompt_set'",
    "'_dashql_shell_prompt_insert'",
    "'_dashql_shell_prompt_move_left'",
    "'_dashql_shell_prompt_move_right'",
    "'_dashql_shell_prompt_delete_backward'",
    "'_dashql_shell_prompt_delete_forward'",
    "'_dashql_shell_prompt_complete'",
    "'_dashql_shell_prompt_apply_completion'",
    "'_dashql_shell_prompt_consume'",
    "'_dashql_shell_prompt_submit'",
    "'_dashql_shell_prompt_result_destroy'",
    "'_dashql_shell_completion_result_destroy'",
    "'_dashql_shell_terminal_open'",
    "'_dashql_shell_terminal_consume'",
    "'_dashql_shell_terminal_finish_query'",
    "'_dashql_shell_terminal_query_progress'",
    "'_dashql_shell_terminal_query_progress_clear'",
    "'_dashql_shell_terminal_status'",
    "'_dashql_shell_terminal_result_destroy'",
    "'_dashql_shell_history_export'",
    "'_dashql_shell_history_import'",
    "'_dashql_shell_start_query'",
    "'_dashql_shell_complete_effect'",
    "'_dashql_shell_cancel_effect'",
    "'_dashql_shell_result_destroy'",
]

DASHQL_WASM_RUNTIME_METHODS = [
    "'ccall'",
    "'cwrap'",
    "'stackSave'",
    "'stackAlloc'",
    "'stackRestore'",
    "'HEAP8'",
    "'HEAP16'",
    "'HEAP32'",
    "'HEAPU8'",
    "'HEAPU16'",
    "'HEAPU32'",
    "'HEAP64'",
    "'HEAPU64'",
    "'HEAPF32'",
    "'HEAPF64'",
]

def dashql_wasm_linkopts(exports, initial_memory, environment, maximum_memory = None, export_name = "createDashQLModule"):
    linkopts = [
        "-sMODULARIZE=1",
        "-sEXPORT_ES6=1",
        "-sEXPORT_NAME=" + export_name,
        "-sEXPORTED_FUNCTIONS=[" + ",".join(exports) + "]",
        "-sEXPORTED_RUNTIME_METHODS=[" + ",".join(DASHQL_WASM_RUNTIME_METHODS) + "]",
        "-sALLOW_MEMORY_GROWTH=1",
        "-sSTANDALONE_WASM=0",
        "-sINITIAL_MEMORY=" + str(initial_memory),
        "-sAGGRESSIVE_VARIABLE_ELIMINATION=1",
        "-sELIMINATE_DUPLICATE_FUNCTIONS=1",
        "-sFILESYSTEM=0",
        "-sENVIRONMENT='" + environment + "'",
        "-sUSE_WEBGL2=0",
        "-sUSE_SDL=0",
    ]
    if maximum_memory != None:
        linkopts.append("-sMAXIMUM_MEMORY=" + str(maximum_memory))
    return linkopts
