[package]
name = "sqlynx-native"
version = "0.0.2-dev.14"
description = "SQL client for the Hyper database system and Salesforce Data Cloud"
edition = "2021"
rust-version = "1.70"
workspace = "../../"

[build-dependencies.tauri-build]
version = "2.0.0-beta"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-updater = "2.0.0-beta.0"
http = "1.0.0"
bytes = "1"
tonic = "^0.11.0"
prost = "^0.12.3"
once_cell = "1.19.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta"
features = []

[dependencies.tokio]
version = "^1.36.0"
features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
