[package]
name = "sqlynx-native"
version = "0.0.2-dev.17"
description = "SQL client for the Hyper database system and Salesforce Data Cloud"
edition = "2021"
rust-version = "1.70"
workspace = "../../"

[build-dependencies.tauri-build]
version = "2.0.0-beta"
features = []

[build-dependencies.tonic-build]
version = "0.11"
features = []

[dependencies]
anyhow = "1.0.80"
serde_json = "1.0"
tauri-plugin-updater = "2.0.0-beta.1"
http = "1.1.0"
tower-service = "0.3.2"
bytes = "1"
prost = "^0.12.3"
once_cell = "1.19.0"
lazy_static = "1.4.0"
log = "0.4"
env_logger = "0.11.2"
regex-automata = "0.4.5"

[dependencies.tonic]
version = "^0.11.0"
features = ["tls"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta"
features = []


[dependencies.tokio-stream]
version = "0.1.14"
features = [
    "net",
]

[dependencies.tokio]
version = "^1.36.0"
features = [
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time"
]

[features]
custom-protocol = ["tauri/custom-protocol"]
