[package]
name = "sqlynx-native"
version = "0.0.2-dev.17"
description = "SQL client for the Hyper database system and Salesforce Data Cloud"
edition = "2021"
rust-version = "1.70"
workspace = "../../"

[build-dependencies.tauri-build]
version = "2.0.0-beta"
features = []

[build-dependencies.tonic-build]
version = "0.11"
features = []

[dependencies]
anyhow = "1.0.83"
byteorder = "1.5.0"
serde_json = "1.0.117"
tauri-plugin-updater = "2.0.0-beta.5"
tauri-plugin-deep-link = "2.0.0-beta.4"
tauri-plugin-log = "2.0.0-beta.4"
tauri-plugin-shell = "2.0.0-beta.4"
tauri-plugin-os = "2.0.0-beta.4"
tauri-plugin-http = "2.0.0-beta.7"
hyper = "1.3.1"
http-body-util = "0.1.1"
http = "1.1.0"
tower-service = "0.3.2"
bytes = "1.6.0"
prost = "^0.12.4"
once_cell = "1.19.0"
lazy_static = "1.4.0"
log = "0.4.21"
url = "2.5.0"
env_logger = "0.11.3"
regex-automata = "0.4.6"
mime = "0.3.17"
futures-util = "0.3.30"
futures-core = "0.3.30"

[dependencies.hyper-util]
version = "0.1.3"
features = ["server"]

[dependencies.reqwest]
version = "^0.12.4"
features = ["stream"]

[dependencies.tonic]
version = "^0.11.0"
features = ["tls"]

[dependencies.serde]
version = "1.0.202"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta"
features = []


[dependencies.tokio-stream]
version = "0.1.15"
features = [
    "net",
]

[dependencies.tokio]
version = "^1.37.0"
features = [
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time"
]

[features]
custom-protocol = ["tauri/custom-protocol"]
