# Root workspace for desktop and release tooling crates.
# Used by Bazel crate_universe as the primary "crates" universe.
[workspace]
resolver = "2"
members = [
    "packages/dashql-native-napi",
    "packages/dashql-native-proxy",
    "packages/dashql-pack",
    "packages/dashql-data",
]

[profile.release]
strip = true
lto = true
opt-level = "s"
