packages:
  - 'packages/*'
onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - electron
  - electron-winstaller
minimumReleaseAgeExclude:
  - hyperdb-wasm@0.0.26553-dev.wasm.gc7d06744 || 0.0.26772-dev.wasm.g94d5c8ef || 0.0.26773-dev.wasm.g25ca5c66 || 0.0.26773-dev.wasm.g4670215f || 0.0.26774-dev.wasm.g364818c4 || 0.0.26792-dev.wasm.g72cc44c1
allowBuilds:
  '@bufbuild/buf': true
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
