[package]
name = "flatsql_proto"
version = "0.1.0"
edition = "2018"

workspace = "../../"

[lib]
name = "flatsql_proto"
path = "src/lib.rs"
test = false
doctest = false

[dependencies]
flatbuffers = "2.1.1"
