[package]
name = "flatsql-parser"
version = "0.1.0"
edition = "2018"

workspace = "../../"

[lib]
name = "flatsql_parser"
test = true
doctest = false

[dependencies]
flatsql-proto = { path = "../flatsql-proto-rs" }
flatbuffers = "23.1.21"
cty = "0.2.2"
bumpalo = "3.9.1"

[build-dependencies]
cmake = "0.1.48"
