/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tigon.proto.tql.ExtractStatement');

goog.require('jspb.Message');
goog.require('proto.tigon.proto.tql.CSVExtract');
goog.require('proto.tigon.proto.tql.JSONExtract');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tigon.proto.tql.ExtractStatement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tigon.proto.tql.ExtractStatement.oneofGroups_);
};
goog.inherits(proto.tigon.proto.tql.ExtractStatement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tigon.proto.tql.ExtractStatement.displayName = 'proto.tigon.proto.tql.ExtractStatement';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tigon.proto.tql.ExtractStatement.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.tigon.proto.tql.ExtractStatement.MethodCase = {
  METHOD_NOT_SET: 0,
  JSON: 3,
  CSV: 4
};

/**
 * @return {proto.tigon.proto.tql.ExtractStatement.MethodCase}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.getMethodCase = function() {
  return /** @type {proto.tigon.proto.tql.ExtractStatement.MethodCase} */(jspb.Message.computeOneofCase(this, proto.tigon.proto.tql.ExtractStatement.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.toObject = function(opt_includeInstance) {
  return proto.tigon.proto.tql.ExtractStatement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tigon.proto.tql.ExtractStatement} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tigon.proto.tql.ExtractStatement.toObject = function(includeInstance, msg) {
  var f, obj = {
    extractName: msg.getExtractName(),
    dataName: msg.getDataName(),
    json: (f = msg.getJson()) && proto.tigon.proto.tql.JSONExtract.toObject(includeInstance, f),
    csv: (f = msg.getCsv()) && proto.tigon.proto.tql.CSVExtract.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tigon.proto.tql.ExtractStatement} The clone.
 */
proto.tigon.proto.tql.ExtractStatement.prototype.cloneMessage = function() {
  return /** @type {!proto.tigon.proto.tql.ExtractStatement} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string extract_name = 1;
 * @return {string}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.getExtractName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.tigon.proto.tql.ExtractStatement.prototype.setExtractName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string data_name = 2;
 * @return {string}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.getDataName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.tigon.proto.tql.ExtractStatement.prototype.setDataName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional JSONExtract json = 3;
 * @return {proto.tigon.proto.tql.JSONExtract}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.getJson = function() {
  return /** @type{proto.tigon.proto.tql.JSONExtract} */ (
    jspb.Message.getWrapperField(this, proto.tigon.proto.tql.JSONExtract, 3));
};


/** @param {proto.tigon.proto.tql.JSONExtract|undefined} value  */
proto.tigon.proto.tql.ExtractStatement.prototype.setJson = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.tigon.proto.tql.ExtractStatement.oneofGroups_[0], value);
};


proto.tigon.proto.tql.ExtractStatement.prototype.clearJson = function() {
  this.setJson(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.hasJson = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CSVExtract csv = 4;
 * @return {proto.tigon.proto.tql.CSVExtract}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.getCsv = function() {
  return /** @type{proto.tigon.proto.tql.CSVExtract} */ (
    jspb.Message.getWrapperField(this, proto.tigon.proto.tql.CSVExtract, 4));
};


/** @param {proto.tigon.proto.tql.CSVExtract|undefined} value  */
proto.tigon.proto.tql.ExtractStatement.prototype.setCsv = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.tigon.proto.tql.ExtractStatement.oneofGroups_[0], value);
};


proto.tigon.proto.tql.ExtractStatement.prototype.clearCsv = function() {
  this.setCsv(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.tigon.proto.tql.ExtractStatement.prototype.hasCsv = function() {
  return jspb.Message.getField(this, 4) != null;
};


