/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tigon.proto.web_api.FormattedText');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tigon.proto.web_api.FormattedText = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tigon.proto.web_api.FormattedText, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tigon.proto.web_api.FormattedText.displayName = 'proto.tigon.proto.web_api.FormattedText';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tigon.proto.web_api.FormattedText.prototype.toObject = function(opt_includeInstance) {
  return proto.tigon.proto.web_api.FormattedText.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tigon.proto.web_api.FormattedText} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tigon.proto.web_api.FormattedText.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: msg.getText()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tigon.proto.web_api.FormattedText} The clone.
 */
proto.tigon.proto.web_api.FormattedText.prototype.cloneMessage = function() {
  return /** @type {!proto.tigon.proto.web_api.FormattedText} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.tigon.proto.web_api.FormattedText.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.tigon.proto.web_api.FormattedText.prototype.setText = function(value) {
  jspb.Message.setField(this, 1, value);
};


