/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tigon.proto.duckdb.QueryPlan');

goog.require('jspb.Message');

goog.forwardDeclare('proto.tigon.proto.duckdb.LogicalOperatorType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tigon.proto.duckdb.QueryPlan = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tigon.proto.duckdb.QueryPlan.repeatedFields_, null);
};
goog.inherits(proto.tigon.proto.duckdb.QueryPlan, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tigon.proto.duckdb.QueryPlan.displayName = 'proto.tigon.proto.duckdb.QueryPlan';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tigon.proto.duckdb.QueryPlan.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tigon.proto.duckdb.QueryPlan.prototype.toObject = function(opt_includeInstance) {
  return proto.tigon.proto.duckdb.QueryPlan.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tigon.proto.duckdb.QueryPlan} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tigon.proto.duckdb.QueryPlan.toObject = function(includeInstance, msg) {
  var f, obj = {
    operatorChildrenList: jspb.Message.getField(msg, 1),
    operatorChildOffsetsList: jspb.Message.getField(msg, 2),
    operatorTypesList: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tigon.proto.duckdb.QueryPlan} The clone.
 */
proto.tigon.proto.duckdb.QueryPlan.prototype.cloneMessage = function() {
  return /** @type {!proto.tigon.proto.duckdb.QueryPlan} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated uint64 operator_children = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.tigon.proto.duckdb.QueryPlan.prototype.getOperatorChildrenList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 1));
};


/** @param {Array.<number>} value  */
proto.tigon.proto.duckdb.QueryPlan.prototype.setOperatorChildrenList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


proto.tigon.proto.duckdb.QueryPlan.prototype.clearOperatorChildrenList = function() {
  jspb.Message.setField(this, 1, []);
};


/**
 * repeated uint64 operator_child_offsets = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.tigon.proto.duckdb.QueryPlan.prototype.getOperatorChildOffsetsList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 2));
};


/** @param {Array.<number>} value  */
proto.tigon.proto.duckdb.QueryPlan.prototype.setOperatorChildOffsetsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


proto.tigon.proto.duckdb.QueryPlan.prototype.clearOperatorChildOffsetsList = function() {
  jspb.Message.setField(this, 2, []);
};


/**
 * repeated LogicalOperatorType operator_types = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tigon.proto.duckdb.LogicalOperatorType>}
 */
proto.tigon.proto.duckdb.QueryPlan.prototype.getOperatorTypesList = function() {
  return /** @type {!Array.<!proto.tigon.proto.duckdb.LogicalOperatorType>} */ (jspb.Message.getField(this, 3));
};


/** @param {!Array.<!proto.tigon.proto.duckdb.LogicalOperatorType>} value  */
proto.tigon.proto.duckdb.QueryPlan.prototype.setOperatorTypesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


proto.tigon.proto.duckdb.QueryPlan.prototype.clearOperatorTypesList = function() {
  jspb.Message.setField(this, 3, []);
};


