// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: rpath.fbe
// Version: 1.3.0.0

/* eslint-disable prefer-const */
'use strict'

const util = require('util')

const big = require('./big')
const int64 = require('./int64')
const uuid = require('./uuid')

const Big = big.Big // eslint-disable-line
const Int64 = int64.Int64 // eslint-disable-line
const UInt64 = int64.UInt64 // eslint-disable-line
const UUID = uuid.UUID // eslint-disable-line

const fbe = require('./fbe')

/**
 * RPathArraySlice struct
 */
class RPathArraySlice {
  /**
   * Copy struct (shallow copy)
   * @this {!RPathArraySlice}
   * @param {!RPathArraySlice} other Other struct
   * @returns {!RPathArraySlice} This struct
   */
  copy (other) {
    return this
  }

  /**
   * Clone struct (deep clone)
   * @this {!RPathArraySlice}
   * @returns {!RPathArraySlice} Cloned struct
   */
  clone () {
    // Serialize the struct to the FBE stream
    let writer = new RPathArraySliceModel(new fbe.WriteBuffer())
    writer.serialize(this)

    // Deserialize the struct from the FBE stream
    let reader = new RPathArraySliceModel(new fbe.ReadBuffer())
    reader.attachBuffer(writer.buffer)
    return reader.deserialize().value
  }

  /**
   * Is this struct equal to other one?
   * @this {!RPathArraySlice}
   * @param {!RPathArraySlice} other Other struct
   * @returns {boolean} Equal result
   */
  eq (other) {
    if (!(other instanceof RPathArraySlice)) {
      throw new TypeError('Instance of RPathArraySlice is required!')
    }
    return true
  }

  /**
   * Convert struct to string
   * @this {!RPathArraySlice}
   * @returns {!string} Struct value string
   */
  toString () {
    let result = ''
    result += 'RPathArraySlice('
    result += ')'
    return result
  }

  /**
   * Inspect struct
   * @this {!RPathArraySlice}
   * @returns {!string} Struct value string
   */
  [util.inspect.custom] () {
    return this.toString()
  }

  /**
   * Convert struct to JSON
   * @this {!RPathArraySlice}
   * @returns {!object} Struct value for JSON
   */
  toJSON () {
    return {
    }
  }

  /**
   * Convert JSON to struct
   * @param {!string} json JSON string
   * @returns {!object} Struct value for JSON
   */
  static fromJSON (json) {
    return RPathArraySlice.fromObject(JSON.parse(json))
  }

  /**
   * Create struct from object value
   * @param {!RPathArraySlice} other Object value
   * @returns {!RPathArraySlice} Created struct
   */
  static fromObject (other) {
    return new RPathArraySlice().copy(other)
  }

  /**
   * Get the FBE type
   * @this {!RPathArraySlice}
   * @returns {!number} FBE type
   */
  get fbeType () {
    return RPathArraySlice.fbeType
  }

  /**
   * Get the FBE type (static)
   * @this {!RPathArraySlice}
   * @returns {!number} FBE type
   */
  static get fbeType () {
    return 1
  }
}

exports.RPathArraySlice = RPathArraySlice

/**
 * Fast Binary Encoding RPathArraySlice field model
 */
class FieldModelRPathArraySlice extends fbe.FieldModel {
  /**
   * Get the field size
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field size
   */
  get fbeSize () {
    return 4
  }

  /**
   * Get the field body size
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field body size
   */
  get fbeBody () {
    return 4 + 4
  }

  /**
   * Get the field extra size
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field extra size
   */
  get fbeExtra () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4) > this._buffer.size)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)

    let fbeResult = this.fbeBody

    this._buffer.unshift(fbeStructOffset)

    return fbeResult
  }

  /**
   * Get the field type
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field type
   */
  get fbeType () {
    return FieldModelRPathArraySlice.fbeType
  }

  /**
   * Get the field type (static)
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field type
   */
  static get fbeType () {
    return 1
  }

  /**
   * Check if the struct value is valid
   * @this {!FieldModelRPathArraySlice}
   * @param {!boolean} fbeVerifyType Verify model type flag, defaults is true
   * @returns {!boolean} Field model valid state
   */
  verify (fbeVerifyType = true) {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return true
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return false
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    if (fbeStructSize < (4 + 4)) {
      return false
    }

    let fbeStructType = this.readUInt32(fbeStructOffset + 4)
    if (fbeVerifyType && (fbeStructType !== this.fbeType)) {
      return false
    }

    this._buffer.shift(fbeStructOffset)
    let fbeResult = this.verifyFields(fbeStructSize)
    this._buffer.unshift(fbeStructOffset)
    return fbeResult
  }

  /**
   * Check if the struct fields are valid
   * @this {!FieldModelRPathArraySlice}
   * @param {!number} fbeStructSize FBE struct size
   * @returns {!boolean} Field model valid state
   */
  verifyFields (fbeStructSize) {
    return true
  }

  /**
   * Get the struct value (begin phase)
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field model begin offset
   */
  getBegin () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + 4 + 4) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return 0
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    console.assert((fbeStructSize >= (4 + 4)), 'Model is broken!')
    if (fbeStructSize < (4 + 4)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Get the struct value (end phase)
   * @this {!FieldModelRPathArraySlice}
   * @param {!number} fbeBegin Field model begin offset
   */
  getEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Get the struct value
   * @this {!FieldModelRPathArraySlice}
   * @param {!RPathArraySlice} fbeValue Default value, defaults is new RPathArraySlice()
   * @returns {!RPathArraySlice} RPathArraySlice value
   */
  get (fbeValue = new RPathArraySlice()) {
    let fbeBegin = this.getBegin()
    if (fbeBegin === 0) {
      return fbeValue
    }

    let fbeStructSize = this.readUInt32(0)
    this.getFields(fbeValue, fbeStructSize)
    this.getEnd(fbeBegin)
    return fbeValue
  }

  /**
   * Get the struct fields values
   * @this {!FieldModelRPathArraySlice}
   * @param {!RPathArraySlice} fbeValue RPathArraySlice value
   * @param {!number} fbeStructSize Struct size
   */
  getFields (fbeValue, fbeStructSize) {
  }

  /**
   * Set the struct value (begin phase)
   * @this {!FieldModelRPathArraySlice}
   * @returns {!number} Field model begin offset
   */
  setBegin () {
    console.assert(((this._buffer.offset + this.fbeOffset + this.fbeSize) <= this._buffer.size), 'Model is broken!')
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructSize = this.fbeBody
    let fbeStructOffset = this._buffer.allocate(fbeStructSize) - this._buffer.offset
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + fbeStructSize) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset <= 0) || ((this._buffer.offset + fbeStructOffset + fbeStructSize) > this._buffer.size)) {
      return 0
    }

    this.writeUInt32(this.fbeOffset, fbeStructOffset)
    this.writeUInt32(fbeStructOffset, fbeStructSize)
    this.writeUInt32(fbeStructOffset + 4, this.fbeType)

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Set the struct value (end phase)
   * @this {!FieldModelRPathArraySlice}
   * @param {!number} fbeBegin Field model begin offset
   */
  setEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Set the struct value
   * @this {!FieldModelRPathArraySlice}
   * @param {!RPathArraySlice} fbeValue RPathArraySlice value
   */
  set (fbeValue) {
    let fbeBegin = this.setBegin()
    if (fbeBegin === 0) {
      return
    }

    this.setFields(fbeValue)
    this.setEnd(fbeBegin)
  }

  /**
   * Set the struct fields values
   * @this {!FieldModelRPathArraySlice}
   * @param {RPathArraySlice} fbeValue RPathArraySlice value
   */
  setFields (fbeValue) {
  }
}

exports.FieldModelRPathArraySlice = FieldModelRPathArraySlice

/**
 * Fast Binary Encoding RPathArraySlice model
 */
class RPathArraySliceModel extends fbe.Model {
  /**
   * Initialize model with the given buffer
   * @param {!fbe.ReadBuffer|!fbe.WriteBuffer} buffer Read/Write buffer, defaults is new fbe.WriteBuffer()
   * @constructor
   */
  constructor (buffer = new fbe.WriteBuffer()) {
    super(buffer)
    this._model = new FieldModelRPathArraySlice(this.buffer, 4)
  }

  /**
   * Get the RPathArraySlice model
   * @this {!RPathArraySliceModel}
   * @returns {!FieldModelRPathArraySlice} model RPathArraySlice model
   */
  get model () {
    return this._model
  }

  /**
   * Get the model size
   * @this {!RPathArraySliceModel}
   * @returns {!number} Model size
   */
  get fbeSize () {
    return this.model.fbeSize + this.model.fbeExtra
  }

  /**
   * Get the model type
   * @this {!RPathArraySliceModel}
   * @returns {!number} Model type
   */
  get fbeType () {
    return RPathArraySliceModel.fbeType
  }

  /**
   * Get the model type (static)
   * @this {!RPathArraySliceModel}
   * @returns {!number} Model type
   */
  static get fbeType () {
    return FieldModelRPathArraySlice.fbeType
  }

  /**
   * Check if the struct value is valid
   * @this {!RPathArraySliceModel}
   * @returns {!boolean} Model valid state
   */
  verify () {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return false
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    if (fbeFullSize < this.model.fbeSize) {
      return false
    }

    return this.model.verify()
  }

  /**
   * Create a new model (begin phase)
   * @this {!RPathArraySliceModel}
   * @returns {!number} Model begin offset
   */
  createBegin () {
    return this.buffer.allocate(4 + this.model.fbeSize)
  }

  /**
   * Create a new model (end phase)
   * @this {!RPathArraySliceModel}
   * @param {!number} fbeBegin Model begin offset
   */
  createEnd (fbeBegin) {
    let fbeEnd = this.buffer.size
    let fbeFullSize = fbeEnd - fbeBegin
    this.writeUInt32(this.model.fbeOffset - 4, fbeFullSize)
    return fbeFullSize
  }

  /**
   * Serialize the struct value
   * @this {!RPathArraySliceModel}
   * @param {!RPathArraySlice} value RPathArraySlice value
   * @return {!number} Model begin offset
   */
  serialize (value) {
    let fbeBegin = this.createBegin()
    this.model.set(value)
    return this.createEnd(fbeBegin)
  }

  /**
   * Deserialize the struct value
   * @this {!RPathArraySliceModel}
   * @param {!RPathArraySlice} value RPathArraySlice value, defaults is new RPathArraySlice()
   * @return {!object} Deserialized RPathArraySlice value and its size
   */
  deserialize (value = new RPathArraySlice()) {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return { value: new RPathArraySlice(), size: 0 }
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    console.assert((fbeFullSize >= this.model.fbeSize), 'Model is broken!')
    if (fbeFullSize < this.model.fbeSize) {
      return { value: new RPathArraySlice(), size: 0 }
    }

    this.model.get(value)
    return { value: value, size: fbeFullSize }
  }

  /**
   * Move to the next struct value
   * @this {!RPathArraySliceModel}
   * @param {!number} prev Previous RPathArraySlice model size
   */
  next (prev) {
    this.model.fbeShift(prev)
  }
}

exports.RPathArraySliceModel = RPathArraySliceModel

/**
 * RPathArrayIndexes struct
 */
class RPathArrayIndexes {
  /**
   * Copy struct (shallow copy)
   * @this {!RPathArrayIndexes}
   * @param {!RPathArrayIndexes} other Other struct
   * @returns {!RPathArrayIndexes} This struct
   */
  copy (other) {
    return this
  }

  /**
   * Clone struct (deep clone)
   * @this {!RPathArrayIndexes}
   * @returns {!RPathArrayIndexes} Cloned struct
   */
  clone () {
    // Serialize the struct to the FBE stream
    let writer = new RPathArrayIndexesModel(new fbe.WriteBuffer())
    writer.serialize(this)

    // Deserialize the struct from the FBE stream
    let reader = new RPathArrayIndexesModel(new fbe.ReadBuffer())
    reader.attachBuffer(writer.buffer)
    return reader.deserialize().value
  }

  /**
   * Is this struct equal to other one?
   * @this {!RPathArrayIndexes}
   * @param {!RPathArrayIndexes} other Other struct
   * @returns {boolean} Equal result
   */
  eq (other) {
    if (!(other instanceof RPathArrayIndexes)) {
      throw new TypeError('Instance of RPathArrayIndexes is required!')
    }
    return true
  }

  /**
   * Convert struct to string
   * @this {!RPathArrayIndexes}
   * @returns {!string} Struct value string
   */
  toString () {
    let result = ''
    result += 'RPathArrayIndexes('
    result += ')'
    return result
  }

  /**
   * Inspect struct
   * @this {!RPathArrayIndexes}
   * @returns {!string} Struct value string
   */
  [util.inspect.custom] () {
    return this.toString()
  }

  /**
   * Convert struct to JSON
   * @this {!RPathArrayIndexes}
   * @returns {!object} Struct value for JSON
   */
  toJSON () {
    return {
    }
  }

  /**
   * Convert JSON to struct
   * @param {!string} json JSON string
   * @returns {!object} Struct value for JSON
   */
  static fromJSON (json) {
    return RPathArrayIndexes.fromObject(JSON.parse(json))
  }

  /**
   * Create struct from object value
   * @param {!RPathArrayIndexes} other Object value
   * @returns {!RPathArrayIndexes} Created struct
   */
  static fromObject (other) {
    return new RPathArrayIndexes().copy(other)
  }

  /**
   * Get the FBE type
   * @this {!RPathArrayIndexes}
   * @returns {!number} FBE type
   */
  get fbeType () {
    return RPathArrayIndexes.fbeType
  }

  /**
   * Get the FBE type (static)
   * @this {!RPathArrayIndexes}
   * @returns {!number} FBE type
   */
  static get fbeType () {
    return 2
  }
}

exports.RPathArrayIndexes = RPathArrayIndexes

/**
 * Fast Binary Encoding RPathArrayIndexes field model
 */
class FieldModelRPathArrayIndexes extends fbe.FieldModel {
  /**
   * Get the field size
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field size
   */
  get fbeSize () {
    return 4
  }

  /**
   * Get the field body size
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field body size
   */
  get fbeBody () {
    return 4 + 4
  }

  /**
   * Get the field extra size
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field extra size
   */
  get fbeExtra () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4) > this._buffer.size)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)

    let fbeResult = this.fbeBody

    this._buffer.unshift(fbeStructOffset)

    return fbeResult
  }

  /**
   * Get the field type
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field type
   */
  get fbeType () {
    return FieldModelRPathArrayIndexes.fbeType
  }

  /**
   * Get the field type (static)
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field type
   */
  static get fbeType () {
    return 2
  }

  /**
   * Check if the struct value is valid
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!boolean} fbeVerifyType Verify model type flag, defaults is true
   * @returns {!boolean} Field model valid state
   */
  verify (fbeVerifyType = true) {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return true
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return false
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    if (fbeStructSize < (4 + 4)) {
      return false
    }

    let fbeStructType = this.readUInt32(fbeStructOffset + 4)
    if (fbeVerifyType && (fbeStructType !== this.fbeType)) {
      return false
    }

    this._buffer.shift(fbeStructOffset)
    let fbeResult = this.verifyFields(fbeStructSize)
    this._buffer.unshift(fbeStructOffset)
    return fbeResult
  }

  /**
   * Check if the struct fields are valid
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!number} fbeStructSize FBE struct size
   * @returns {!boolean} Field model valid state
   */
  verifyFields (fbeStructSize) {
    return true
  }

  /**
   * Get the struct value (begin phase)
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field model begin offset
   */
  getBegin () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + 4 + 4) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return 0
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    console.assert((fbeStructSize >= (4 + 4)), 'Model is broken!')
    if (fbeStructSize < (4 + 4)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Get the struct value (end phase)
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!number} fbeBegin Field model begin offset
   */
  getEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Get the struct value
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!RPathArrayIndexes} fbeValue Default value, defaults is new RPathArrayIndexes()
   * @returns {!RPathArrayIndexes} RPathArrayIndexes value
   */
  get (fbeValue = new RPathArrayIndexes()) {
    let fbeBegin = this.getBegin()
    if (fbeBegin === 0) {
      return fbeValue
    }

    let fbeStructSize = this.readUInt32(0)
    this.getFields(fbeValue, fbeStructSize)
    this.getEnd(fbeBegin)
    return fbeValue
  }

  /**
   * Get the struct fields values
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!RPathArrayIndexes} fbeValue RPathArrayIndexes value
   * @param {!number} fbeStructSize Struct size
   */
  getFields (fbeValue, fbeStructSize) {
  }

  /**
   * Set the struct value (begin phase)
   * @this {!FieldModelRPathArrayIndexes}
   * @returns {!number} Field model begin offset
   */
  setBegin () {
    console.assert(((this._buffer.offset + this.fbeOffset + this.fbeSize) <= this._buffer.size), 'Model is broken!')
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructSize = this.fbeBody
    let fbeStructOffset = this._buffer.allocate(fbeStructSize) - this._buffer.offset
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + fbeStructSize) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset <= 0) || ((this._buffer.offset + fbeStructOffset + fbeStructSize) > this._buffer.size)) {
      return 0
    }

    this.writeUInt32(this.fbeOffset, fbeStructOffset)
    this.writeUInt32(fbeStructOffset, fbeStructSize)
    this.writeUInt32(fbeStructOffset + 4, this.fbeType)

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Set the struct value (end phase)
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!number} fbeBegin Field model begin offset
   */
  setEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Set the struct value
   * @this {!FieldModelRPathArrayIndexes}
   * @param {!RPathArrayIndexes} fbeValue RPathArrayIndexes value
   */
  set (fbeValue) {
    let fbeBegin = this.setBegin()
    if (fbeBegin === 0) {
      return
    }

    this.setFields(fbeValue)
    this.setEnd(fbeBegin)
  }

  /**
   * Set the struct fields values
   * @this {!FieldModelRPathArrayIndexes}
   * @param {RPathArrayIndexes} fbeValue RPathArrayIndexes value
   */
  setFields (fbeValue) {
  }
}

exports.FieldModelRPathArrayIndexes = FieldModelRPathArrayIndexes

/**
 * Fast Binary Encoding RPathArrayIndexes model
 */
class RPathArrayIndexesModel extends fbe.Model {
  /**
   * Initialize model with the given buffer
   * @param {!fbe.ReadBuffer|!fbe.WriteBuffer} buffer Read/Write buffer, defaults is new fbe.WriteBuffer()
   * @constructor
   */
  constructor (buffer = new fbe.WriteBuffer()) {
    super(buffer)
    this._model = new FieldModelRPathArrayIndexes(this.buffer, 4)
  }

  /**
   * Get the RPathArrayIndexes model
   * @this {!RPathArrayIndexesModel}
   * @returns {!FieldModelRPathArrayIndexes} model RPathArrayIndexes model
   */
  get model () {
    return this._model
  }

  /**
   * Get the model size
   * @this {!RPathArrayIndexesModel}
   * @returns {!number} Model size
   */
  get fbeSize () {
    return this.model.fbeSize + this.model.fbeExtra
  }

  /**
   * Get the model type
   * @this {!RPathArrayIndexesModel}
   * @returns {!number} Model type
   */
  get fbeType () {
    return RPathArrayIndexesModel.fbeType
  }

  /**
   * Get the model type (static)
   * @this {!RPathArrayIndexesModel}
   * @returns {!number} Model type
   */
  static get fbeType () {
    return FieldModelRPathArrayIndexes.fbeType
  }

  /**
   * Check if the struct value is valid
   * @this {!RPathArrayIndexesModel}
   * @returns {!boolean} Model valid state
   */
  verify () {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return false
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    if (fbeFullSize < this.model.fbeSize) {
      return false
    }

    return this.model.verify()
  }

  /**
   * Create a new model (begin phase)
   * @this {!RPathArrayIndexesModel}
   * @returns {!number} Model begin offset
   */
  createBegin () {
    return this.buffer.allocate(4 + this.model.fbeSize)
  }

  /**
   * Create a new model (end phase)
   * @this {!RPathArrayIndexesModel}
   * @param {!number} fbeBegin Model begin offset
   */
  createEnd (fbeBegin) {
    let fbeEnd = this.buffer.size
    let fbeFullSize = fbeEnd - fbeBegin
    this.writeUInt32(this.model.fbeOffset - 4, fbeFullSize)
    return fbeFullSize
  }

  /**
   * Serialize the struct value
   * @this {!RPathArrayIndexesModel}
   * @param {!RPathArrayIndexes} value RPathArrayIndexes value
   * @return {!number} Model begin offset
   */
  serialize (value) {
    let fbeBegin = this.createBegin()
    this.model.set(value)
    return this.createEnd(fbeBegin)
  }

  /**
   * Deserialize the struct value
   * @this {!RPathArrayIndexesModel}
   * @param {!RPathArrayIndexes} value RPathArrayIndexes value, defaults is new RPathArrayIndexes()
   * @return {!object} Deserialized RPathArrayIndexes value and its size
   */
  deserialize (value = new RPathArrayIndexes()) {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return { value: new RPathArrayIndexes(), size: 0 }
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    console.assert((fbeFullSize >= this.model.fbeSize), 'Model is broken!')
    if (fbeFullSize < this.model.fbeSize) {
      return { value: new RPathArrayIndexes(), size: 0 }
    }

    this.model.get(value)
    return { value: value, size: fbeFullSize }
  }

  /**
   * Move to the next struct value
   * @this {!RPathArrayIndexesModel}
   * @param {!number} prev Previous RPathArrayIndexes model size
   */
  next (prev) {
    this.model.fbeShift(prev)
  }
}

exports.RPathArrayIndexesModel = RPathArrayIndexesModel

/**
 * RPathChildMember struct
 */
class RPathChildMember {
  /**
   * Copy struct (shallow copy)
   * @this {!RPathChildMember}
   * @param {!RPathChildMember} other Other struct
   * @returns {!RPathChildMember} This struct
   */
  copy (other) {
    return this
  }

  /**
   * Clone struct (deep clone)
   * @this {!RPathChildMember}
   * @returns {!RPathChildMember} Cloned struct
   */
  clone () {
    // Serialize the struct to the FBE stream
    let writer = new RPathChildMemberModel(new fbe.WriteBuffer())
    writer.serialize(this)

    // Deserialize the struct from the FBE stream
    let reader = new RPathChildMemberModel(new fbe.ReadBuffer())
    reader.attachBuffer(writer.buffer)
    return reader.deserialize().value
  }

  /**
   * Is this struct equal to other one?
   * @this {!RPathChildMember}
   * @param {!RPathChildMember} other Other struct
   * @returns {boolean} Equal result
   */
  eq (other) {
    if (!(other instanceof RPathChildMember)) {
      throw new TypeError('Instance of RPathChildMember is required!')
    }
    return true
  }

  /**
   * Convert struct to string
   * @this {!RPathChildMember}
   * @returns {!string} Struct value string
   */
  toString () {
    let result = ''
    result += 'RPathChildMember('
    result += ')'
    return result
  }

  /**
   * Inspect struct
   * @this {!RPathChildMember}
   * @returns {!string} Struct value string
   */
  [util.inspect.custom] () {
    return this.toString()
  }

  /**
   * Convert struct to JSON
   * @this {!RPathChildMember}
   * @returns {!object} Struct value for JSON
   */
  toJSON () {
    return {
    }
  }

  /**
   * Convert JSON to struct
   * @param {!string} json JSON string
   * @returns {!object} Struct value for JSON
   */
  static fromJSON (json) {
    return RPathChildMember.fromObject(JSON.parse(json))
  }

  /**
   * Create struct from object value
   * @param {!RPathChildMember} other Object value
   * @returns {!RPathChildMember} Created struct
   */
  static fromObject (other) {
    return new RPathChildMember().copy(other)
  }

  /**
   * Get the FBE type
   * @this {!RPathChildMember}
   * @returns {!number} FBE type
   */
  get fbeType () {
    return RPathChildMember.fbeType
  }

  /**
   * Get the FBE type (static)
   * @this {!RPathChildMember}
   * @returns {!number} FBE type
   */
  static get fbeType () {
    return 3
  }
}

exports.RPathChildMember = RPathChildMember

/**
 * Fast Binary Encoding RPathChildMember field model
 */
class FieldModelRPathChildMember extends fbe.FieldModel {
  /**
   * Get the field size
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field size
   */
  get fbeSize () {
    return 4
  }

  /**
   * Get the field body size
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field body size
   */
  get fbeBody () {
    return 4 + 4
  }

  /**
   * Get the field extra size
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field extra size
   */
  get fbeExtra () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4) > this._buffer.size)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)

    let fbeResult = this.fbeBody

    this._buffer.unshift(fbeStructOffset)

    return fbeResult
  }

  /**
   * Get the field type
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field type
   */
  get fbeType () {
    return FieldModelRPathChildMember.fbeType
  }

  /**
   * Get the field type (static)
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field type
   */
  static get fbeType () {
    return 3
  }

  /**
   * Check if the struct value is valid
   * @this {!FieldModelRPathChildMember}
   * @param {!boolean} fbeVerifyType Verify model type flag, defaults is true
   * @returns {!boolean} Field model valid state
   */
  verify (fbeVerifyType = true) {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return true
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return false
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    if (fbeStructSize < (4 + 4)) {
      return false
    }

    let fbeStructType = this.readUInt32(fbeStructOffset + 4)
    if (fbeVerifyType && (fbeStructType !== this.fbeType)) {
      return false
    }

    this._buffer.shift(fbeStructOffset)
    let fbeResult = this.verifyFields(fbeStructSize)
    this._buffer.unshift(fbeStructOffset)
    return fbeResult
  }

  /**
   * Check if the struct fields are valid
   * @this {!FieldModelRPathChildMember}
   * @param {!number} fbeStructSize FBE struct size
   * @returns {!boolean} Field model valid state
   */
  verifyFields (fbeStructSize) {
    return true
  }

  /**
   * Get the struct value (begin phase)
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field model begin offset
   */
  getBegin () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + 4 + 4) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return 0
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    console.assert((fbeStructSize >= (4 + 4)), 'Model is broken!')
    if (fbeStructSize < (4 + 4)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Get the struct value (end phase)
   * @this {!FieldModelRPathChildMember}
   * @param {!number} fbeBegin Field model begin offset
   */
  getEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Get the struct value
   * @this {!FieldModelRPathChildMember}
   * @param {!RPathChildMember} fbeValue Default value, defaults is new RPathChildMember()
   * @returns {!RPathChildMember} RPathChildMember value
   */
  get (fbeValue = new RPathChildMember()) {
    let fbeBegin = this.getBegin()
    if (fbeBegin === 0) {
      return fbeValue
    }

    let fbeStructSize = this.readUInt32(0)
    this.getFields(fbeValue, fbeStructSize)
    this.getEnd(fbeBegin)
    return fbeValue
  }

  /**
   * Get the struct fields values
   * @this {!FieldModelRPathChildMember}
   * @param {!RPathChildMember} fbeValue RPathChildMember value
   * @param {!number} fbeStructSize Struct size
   */
  getFields (fbeValue, fbeStructSize) {
  }

  /**
   * Set the struct value (begin phase)
   * @this {!FieldModelRPathChildMember}
   * @returns {!number} Field model begin offset
   */
  setBegin () {
    console.assert(((this._buffer.offset + this.fbeOffset + this.fbeSize) <= this._buffer.size), 'Model is broken!')
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructSize = this.fbeBody
    let fbeStructOffset = this._buffer.allocate(fbeStructSize) - this._buffer.offset
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + fbeStructSize) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset <= 0) || ((this._buffer.offset + fbeStructOffset + fbeStructSize) > this._buffer.size)) {
      return 0
    }

    this.writeUInt32(this.fbeOffset, fbeStructOffset)
    this.writeUInt32(fbeStructOffset, fbeStructSize)
    this.writeUInt32(fbeStructOffset + 4, this.fbeType)

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Set the struct value (end phase)
   * @this {!FieldModelRPathChildMember}
   * @param {!number} fbeBegin Field model begin offset
   */
  setEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Set the struct value
   * @this {!FieldModelRPathChildMember}
   * @param {!RPathChildMember} fbeValue RPathChildMember value
   */
  set (fbeValue) {
    let fbeBegin = this.setBegin()
    if (fbeBegin === 0) {
      return
    }

    this.setFields(fbeValue)
    this.setEnd(fbeBegin)
  }

  /**
   * Set the struct fields values
   * @this {!FieldModelRPathChildMember}
   * @param {RPathChildMember} fbeValue RPathChildMember value
   */
  setFields (fbeValue) {
  }
}

exports.FieldModelRPathChildMember = FieldModelRPathChildMember

/**
 * Fast Binary Encoding RPathChildMember model
 */
class RPathChildMemberModel extends fbe.Model {
  /**
   * Initialize model with the given buffer
   * @param {!fbe.ReadBuffer|!fbe.WriteBuffer} buffer Read/Write buffer, defaults is new fbe.WriteBuffer()
   * @constructor
   */
  constructor (buffer = new fbe.WriteBuffer()) {
    super(buffer)
    this._model = new FieldModelRPathChildMember(this.buffer, 4)
  }

  /**
   * Get the RPathChildMember model
   * @this {!RPathChildMemberModel}
   * @returns {!FieldModelRPathChildMember} model RPathChildMember model
   */
  get model () {
    return this._model
  }

  /**
   * Get the model size
   * @this {!RPathChildMemberModel}
   * @returns {!number} Model size
   */
  get fbeSize () {
    return this.model.fbeSize + this.model.fbeExtra
  }

  /**
   * Get the model type
   * @this {!RPathChildMemberModel}
   * @returns {!number} Model type
   */
  get fbeType () {
    return RPathChildMemberModel.fbeType
  }

  /**
   * Get the model type (static)
   * @this {!RPathChildMemberModel}
   * @returns {!number} Model type
   */
  static get fbeType () {
    return FieldModelRPathChildMember.fbeType
  }

  /**
   * Check if the struct value is valid
   * @this {!RPathChildMemberModel}
   * @returns {!boolean} Model valid state
   */
  verify () {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return false
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    if (fbeFullSize < this.model.fbeSize) {
      return false
    }

    return this.model.verify()
  }

  /**
   * Create a new model (begin phase)
   * @this {!RPathChildMemberModel}
   * @returns {!number} Model begin offset
   */
  createBegin () {
    return this.buffer.allocate(4 + this.model.fbeSize)
  }

  /**
   * Create a new model (end phase)
   * @this {!RPathChildMemberModel}
   * @param {!number} fbeBegin Model begin offset
   */
  createEnd (fbeBegin) {
    let fbeEnd = this.buffer.size
    let fbeFullSize = fbeEnd - fbeBegin
    this.writeUInt32(this.model.fbeOffset - 4, fbeFullSize)
    return fbeFullSize
  }

  /**
   * Serialize the struct value
   * @this {!RPathChildMemberModel}
   * @param {!RPathChildMember} value RPathChildMember value
   * @return {!number} Model begin offset
   */
  serialize (value) {
    let fbeBegin = this.createBegin()
    this.model.set(value)
    return this.createEnd(fbeBegin)
  }

  /**
   * Deserialize the struct value
   * @this {!RPathChildMemberModel}
   * @param {!RPathChildMember} value RPathChildMember value, defaults is new RPathChildMember()
   * @return {!object} Deserialized RPathChildMember value and its size
   */
  deserialize (value = new RPathChildMember()) {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return { value: new RPathChildMember(), size: 0 }
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    console.assert((fbeFullSize >= this.model.fbeSize), 'Model is broken!')
    if (fbeFullSize < this.model.fbeSize) {
      return { value: new RPathChildMember(), size: 0 }
    }

    this.model.get(value)
    return { value: value, size: fbeFullSize }
  }

  /**
   * Move to the next struct value
   * @this {!RPathChildMemberModel}
   * @param {!number} prev Previous RPathChildMember model size
   */
  next (prev) {
    this.model.fbeShift(prev)
  }
}

exports.RPathChildMemberModel = RPathChildMemberModel

/**
 * RPathDescendantMember struct
 */
class RPathDescendantMember {
  /**
   * Copy struct (shallow copy)
   * @this {!RPathDescendantMember}
   * @param {!RPathDescendantMember} other Other struct
   * @returns {!RPathDescendantMember} This struct
   */
  copy (other) {
    return this
  }

  /**
   * Clone struct (deep clone)
   * @this {!RPathDescendantMember}
   * @returns {!RPathDescendantMember} Cloned struct
   */
  clone () {
    // Serialize the struct to the FBE stream
    let writer = new RPathDescendantMemberModel(new fbe.WriteBuffer())
    writer.serialize(this)

    // Deserialize the struct from the FBE stream
    let reader = new RPathDescendantMemberModel(new fbe.ReadBuffer())
    reader.attachBuffer(writer.buffer)
    return reader.deserialize().value
  }

  /**
   * Is this struct equal to other one?
   * @this {!RPathDescendantMember}
   * @param {!RPathDescendantMember} other Other struct
   * @returns {boolean} Equal result
   */
  eq (other) {
    if (!(other instanceof RPathDescendantMember)) {
      throw new TypeError('Instance of RPathDescendantMember is required!')
    }
    return true
  }

  /**
   * Convert struct to string
   * @this {!RPathDescendantMember}
   * @returns {!string} Struct value string
   */
  toString () {
    let result = ''
    result += 'RPathDescendantMember('
    result += ')'
    return result
  }

  /**
   * Inspect struct
   * @this {!RPathDescendantMember}
   * @returns {!string} Struct value string
   */
  [util.inspect.custom] () {
    return this.toString()
  }

  /**
   * Convert struct to JSON
   * @this {!RPathDescendantMember}
   * @returns {!object} Struct value for JSON
   */
  toJSON () {
    return {
    }
  }

  /**
   * Convert JSON to struct
   * @param {!string} json JSON string
   * @returns {!object} Struct value for JSON
   */
  static fromJSON (json) {
    return RPathDescendantMember.fromObject(JSON.parse(json))
  }

  /**
   * Create struct from object value
   * @param {!RPathDescendantMember} other Object value
   * @returns {!RPathDescendantMember} Created struct
   */
  static fromObject (other) {
    return new RPathDescendantMember().copy(other)
  }

  /**
   * Get the FBE type
   * @this {!RPathDescendantMember}
   * @returns {!number} FBE type
   */
  get fbeType () {
    return RPathDescendantMember.fbeType
  }

  /**
   * Get the FBE type (static)
   * @this {!RPathDescendantMember}
   * @returns {!number} FBE type
   */
  static get fbeType () {
    return 4
  }
}

exports.RPathDescendantMember = RPathDescendantMember

/**
 * Fast Binary Encoding RPathDescendantMember field model
 */
class FieldModelRPathDescendantMember extends fbe.FieldModel {
  /**
   * Get the field size
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field size
   */
  get fbeSize () {
    return 4
  }

  /**
   * Get the field body size
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field body size
   */
  get fbeBody () {
    return 4 + 4
  }

  /**
   * Get the field extra size
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field extra size
   */
  get fbeExtra () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4) > this._buffer.size)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)

    let fbeResult = this.fbeBody

    this._buffer.unshift(fbeStructOffset)

    return fbeResult
  }

  /**
   * Get the field type
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field type
   */
  get fbeType () {
    return FieldModelRPathDescendantMember.fbeType
  }

  /**
   * Get the field type (static)
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field type
   */
  static get fbeType () {
    return 4
  }

  /**
   * Check if the struct value is valid
   * @this {!FieldModelRPathDescendantMember}
   * @param {!boolean} fbeVerifyType Verify model type flag, defaults is true
   * @returns {!boolean} Field model valid state
   */
  verify (fbeVerifyType = true) {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return true
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return false
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    if (fbeStructSize < (4 + 4)) {
      return false
    }

    let fbeStructType = this.readUInt32(fbeStructOffset + 4)
    if (fbeVerifyType && (fbeStructType !== this.fbeType)) {
      return false
    }

    this._buffer.shift(fbeStructOffset)
    let fbeResult = this.verifyFields(fbeStructSize)
    this._buffer.unshift(fbeStructOffset)
    return fbeResult
  }

  /**
   * Check if the struct fields are valid
   * @this {!FieldModelRPathDescendantMember}
   * @param {!number} fbeStructSize FBE struct size
   * @returns {!boolean} Field model valid state
   */
  verifyFields (fbeStructSize) {
    return true
  }

  /**
   * Get the struct value (begin phase)
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field model begin offset
   */
  getBegin () {
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructOffset = this.readUInt32(this.fbeOffset)
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + 4 + 4) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset === 0) || ((this._buffer.offset + fbeStructOffset + 4 + 4) > this._buffer.size)) {
      return 0
    }

    let fbeStructSize = this.readUInt32(fbeStructOffset)
    console.assert((fbeStructSize >= (4 + 4)), 'Model is broken!')
    if (fbeStructSize < (4 + 4)) {
      return 0
    }

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Get the struct value (end phase)
   * @this {!FieldModelRPathDescendantMember}
   * @param {!number} fbeBegin Field model begin offset
   */
  getEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Get the struct value
   * @this {!FieldModelRPathDescendantMember}
   * @param {!RPathDescendantMember} fbeValue Default value, defaults is new RPathDescendantMember()
   * @returns {!RPathDescendantMember} RPathDescendantMember value
   */
  get (fbeValue = new RPathDescendantMember()) {
    let fbeBegin = this.getBegin()
    if (fbeBegin === 0) {
      return fbeValue
    }

    let fbeStructSize = this.readUInt32(0)
    this.getFields(fbeValue, fbeStructSize)
    this.getEnd(fbeBegin)
    return fbeValue
  }

  /**
   * Get the struct fields values
   * @this {!FieldModelRPathDescendantMember}
   * @param {!RPathDescendantMember} fbeValue RPathDescendantMember value
   * @param {!number} fbeStructSize Struct size
   */
  getFields (fbeValue, fbeStructSize) {
  }

  /**
   * Set the struct value (begin phase)
   * @this {!FieldModelRPathDescendantMember}
   * @returns {!number} Field model begin offset
   */
  setBegin () {
    console.assert(((this._buffer.offset + this.fbeOffset + this.fbeSize) <= this._buffer.size), 'Model is broken!')
    if ((this._buffer.offset + this.fbeOffset + this.fbeSize) > this._buffer.size) {
      return 0
    }

    let fbeStructSize = this.fbeBody
    let fbeStructOffset = this._buffer.allocate(fbeStructSize) - this._buffer.offset
    console.assert((fbeStructOffset > 0) && ((this._buffer.offset + fbeStructOffset + fbeStructSize) <= this._buffer.size), 'Model is broken!')
    if ((fbeStructOffset <= 0) || ((this._buffer.offset + fbeStructOffset + fbeStructSize) > this._buffer.size)) {
      return 0
    }

    this.writeUInt32(this.fbeOffset, fbeStructOffset)
    this.writeUInt32(fbeStructOffset, fbeStructSize)
    this.writeUInt32(fbeStructOffset + 4, this.fbeType)

    this._buffer.shift(fbeStructOffset)
    return fbeStructOffset
  }

  /**
   * Set the struct value (end phase)
   * @this {!FieldModelRPathDescendantMember}
   * @param {!number} fbeBegin Field model begin offset
   */
  setEnd (fbeBegin) {
    this._buffer.unshift(fbeBegin)
  }

  /**
   * Set the struct value
   * @this {!FieldModelRPathDescendantMember}
   * @param {!RPathDescendantMember} fbeValue RPathDescendantMember value
   */
  set (fbeValue) {
    let fbeBegin = this.setBegin()
    if (fbeBegin === 0) {
      return
    }

    this.setFields(fbeValue)
    this.setEnd(fbeBegin)
  }

  /**
   * Set the struct fields values
   * @this {!FieldModelRPathDescendantMember}
   * @param {RPathDescendantMember} fbeValue RPathDescendantMember value
   */
  setFields (fbeValue) {
  }
}

exports.FieldModelRPathDescendantMember = FieldModelRPathDescendantMember

/**
 * Fast Binary Encoding RPathDescendantMember model
 */
class RPathDescendantMemberModel extends fbe.Model {
  /**
   * Initialize model with the given buffer
   * @param {!fbe.ReadBuffer|!fbe.WriteBuffer} buffer Read/Write buffer, defaults is new fbe.WriteBuffer()
   * @constructor
   */
  constructor (buffer = new fbe.WriteBuffer()) {
    super(buffer)
    this._model = new FieldModelRPathDescendantMember(this.buffer, 4)
  }

  /**
   * Get the RPathDescendantMember model
   * @this {!RPathDescendantMemberModel}
   * @returns {!FieldModelRPathDescendantMember} model RPathDescendantMember model
   */
  get model () {
    return this._model
  }

  /**
   * Get the model size
   * @this {!RPathDescendantMemberModel}
   * @returns {!number} Model size
   */
  get fbeSize () {
    return this.model.fbeSize + this.model.fbeExtra
  }

  /**
   * Get the model type
   * @this {!RPathDescendantMemberModel}
   * @returns {!number} Model type
   */
  get fbeType () {
    return RPathDescendantMemberModel.fbeType
  }

  /**
   * Get the model type (static)
   * @this {!RPathDescendantMemberModel}
   * @returns {!number} Model type
   */
  static get fbeType () {
    return FieldModelRPathDescendantMember.fbeType
  }

  /**
   * Check if the struct value is valid
   * @this {!RPathDescendantMemberModel}
   * @returns {!boolean} Model valid state
   */
  verify () {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return false
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    if (fbeFullSize < this.model.fbeSize) {
      return false
    }

    return this.model.verify()
  }

  /**
   * Create a new model (begin phase)
   * @this {!RPathDescendantMemberModel}
   * @returns {!number} Model begin offset
   */
  createBegin () {
    return this.buffer.allocate(4 + this.model.fbeSize)
  }

  /**
   * Create a new model (end phase)
   * @this {!RPathDescendantMemberModel}
   * @param {!number} fbeBegin Model begin offset
   */
  createEnd (fbeBegin) {
    let fbeEnd = this.buffer.size
    let fbeFullSize = fbeEnd - fbeBegin
    this.writeUInt32(this.model.fbeOffset - 4, fbeFullSize)
    return fbeFullSize
  }

  /**
   * Serialize the struct value
   * @this {!RPathDescendantMemberModel}
   * @param {!RPathDescendantMember} value RPathDescendantMember value
   * @return {!number} Model begin offset
   */
  serialize (value) {
    let fbeBegin = this.createBegin()
    this.model.set(value)
    return this.createEnd(fbeBegin)
  }

  /**
   * Deserialize the struct value
   * @this {!RPathDescendantMemberModel}
   * @param {!RPathDescendantMember} value RPathDescendantMember value, defaults is new RPathDescendantMember()
   * @return {!object} Deserialized RPathDescendantMember value and its size
   */
  deserialize (value = new RPathDescendantMember()) {
    if ((this.buffer.offset + this.model.fbeOffset - 4) > this.buffer.size) {
      return { value: new RPathDescendantMember(), size: 0 }
    }

    let fbeFullSize = this.readUInt32(this.model.fbeOffset - 4)
    console.assert((fbeFullSize >= this.model.fbeSize), 'Model is broken!')
    if (fbeFullSize < this.model.fbeSize) {
      return { value: new RPathDescendantMember(), size: 0 }
    }

    this.model.get(value)
    return { value: value, size: fbeFullSize }
  }

  /**
   * Move to the next struct value
   * @this {!RPathDescendantMemberModel}
   * @param {!number} prev Previous RPathDescendantMember model size
   */
  next (prev) {
    this.model.fbeShift(prev)
  }
}

exports.RPathDescendantMemberModel = RPathDescendantMemberModel
