/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tigon.proto.duckdb.SQLType');

goog.require('jspb.Message');

goog.forwardDeclare('proto.tigon.proto.duckdb.SQLTypeID');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tigon.proto.duckdb.SQLType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tigon.proto.duckdb.SQLType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tigon.proto.duckdb.SQLType.displayName = 'proto.tigon.proto.duckdb.SQLType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tigon.proto.duckdb.SQLType.prototype.toObject = function(opt_includeInstance) {
  return proto.tigon.proto.duckdb.SQLType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tigon.proto.duckdb.SQLType} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tigon.proto.duckdb.SQLType.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeId: msg.getTypeId(),
    width: msg.getWidth(),
    scale: msg.getScale()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tigon.proto.duckdb.SQLType} The clone.
 */
proto.tigon.proto.duckdb.SQLType.prototype.cloneMessage = function() {
  return /** @type {!proto.tigon.proto.duckdb.SQLType} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional SQLTypeID type_id = 1;
 * @return {!proto.tigon.proto.duckdb.SQLTypeID}
 */
proto.tigon.proto.duckdb.SQLType.prototype.getTypeId = function() {
  return /** @type {!proto.tigon.proto.duckdb.SQLTypeID} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.tigon.proto.duckdb.SQLTypeID} value  */
proto.tigon.proto.duckdb.SQLType.prototype.setTypeId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 width = 2;
 * @return {number}
 */
proto.tigon.proto.duckdb.SQLType.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.tigon.proto.duckdb.SQLType.prototype.setWidth = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 scale = 3;
 * @return {number}
 */
proto.tigon.proto.duckdb.SQLType.prototype.getScale = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.tigon.proto.duckdb.SQLType.prototype.setScale = function(value) {
  jspb.Message.setField(this, 3, value);
};


