// source: tql.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tigon.proto.tql.VizLayout');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.tigon.proto.tql.VizLength');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tigon.proto.tql.VizLayout = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tigon.proto.tql.VizLayout, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tigon.proto.tql.VizLayout.displayName = 'proto.tigon.proto.tql.VizLayout';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tigon.proto.tql.VizLayout.prototype.toObject = function(opt_includeInstance) {
  return proto.tigon.proto.tql.VizLayout.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tigon.proto.tql.VizLayout} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tigon.proto.tql.VizLayout.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: (f = msg.getWidth()) && proto.tigon.proto.tql.VizLength.toObject(includeInstance, f),
    height: (f = msg.getHeight()) && proto.tigon.proto.tql.VizLength.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tigon.proto.tql.VizLayout}
 */
proto.tigon.proto.tql.VizLayout.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tigon.proto.tql.VizLayout;
  return proto.tigon.proto.tql.VizLayout.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tigon.proto.tql.VizLayout} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tigon.proto.tql.VizLayout}
 */
proto.tigon.proto.tql.VizLayout.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tigon.proto.tql.VizLength;
      reader.readMessage(value,proto.tigon.proto.tql.VizLength.deserializeBinaryFromReader);
      msg.setWidth(value);
      break;
    case 2:
      var value = new proto.tigon.proto.tql.VizLength;
      reader.readMessage(value,proto.tigon.proto.tql.VizLength.deserializeBinaryFromReader);
      msg.setHeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tigon.proto.tql.VizLayout.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tigon.proto.tql.VizLayout.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tigon.proto.tql.VizLayout} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tigon.proto.tql.VizLayout.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tigon.proto.tql.VizLength.serializeBinaryToWriter
    );
  }
  f = message.getHeight();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.tigon.proto.tql.VizLength.serializeBinaryToWriter
    );
  }
};


/**
 * optional VizLength width = 1;
 * @return {?proto.tigon.proto.tql.VizLength}
 */
proto.tigon.proto.tql.VizLayout.prototype.getWidth = function() {
  return /** @type{?proto.tigon.proto.tql.VizLength} */ (
    jspb.Message.getWrapperField(this, proto.tigon.proto.tql.VizLength, 1));
};


/**
 * @param {?proto.tigon.proto.tql.VizLength|undefined} value
 * @return {!proto.tigon.proto.tql.VizLayout} returns this
*/
proto.tigon.proto.tql.VizLayout.prototype.setWidth = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tigon.proto.tql.VizLayout} returns this
 */
proto.tigon.proto.tql.VizLayout.prototype.clearWidth = function() {
  return this.setWidth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tigon.proto.tql.VizLayout.prototype.hasWidth = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional VizLength height = 2;
 * @return {?proto.tigon.proto.tql.VizLength}
 */
proto.tigon.proto.tql.VizLayout.prototype.getHeight = function() {
  return /** @type{?proto.tigon.proto.tql.VizLength} */ (
    jspb.Message.getWrapperField(this, proto.tigon.proto.tql.VizLength, 2));
};


/**
 * @param {?proto.tigon.proto.tql.VizLength|undefined} value
 * @return {!proto.tigon.proto.tql.VizLayout} returns this
*/
proto.tigon.proto.tql.VizLayout.prototype.setHeight = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tigon.proto.tql.VizLayout} returns this
 */
proto.tigon.proto.tql.VizLayout.prototype.clearHeight = function() {
  return this.setHeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tigon.proto.tql.VizLayout.prototype.hasHeight = function() {
  return jspb.Message.getField(this, 2) != null;
};


