{
 "title": "DashQL Bazel Cache Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total On Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazel_remote_disk_cache_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncompressed Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazel_remote_disk_cache_logical_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occupied On Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bazel_remote_disk_cache_size_bytes / on(instance) bazel_remote_disk_cache_size_bytes_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazel_remote_disk_cache_entry_bytes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(process_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(bazel_remote_incoming_requests_total{status=\"hit\",kind=\"cas\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(bazel_remote_incoming_requests_total{status=\"hit\",kind=\"ac\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(bazel_remote_incoming_requests_total{status=\"hit\",kind=\"cas\"}[$__rate_interval]))\n* 100) \n/\nsum (rate(bazel_remote_incoming_requests_total{kind=\"cas\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(bazel_remote_incoming_requests_total{status=\"hit\",kind=\"ac\"}[$__rate_interval]))\n* 100) \n/\nsum (rate(bazel_remote_incoming_requests_total{kind=\"ac\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}