// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QUERYPLAN_DUCKDB_WEBAPI_PROTO_H_
#define FLATBUFFERS_GENERATED_QUERYPLAN_DUCKDB_WEBAPI_PROTO_H_

#include "flatbuffers/flatbuffers.h"

namespace duckdb_webapi {
namespace proto {

struct QueryPlan;
struct QueryPlanBuilder;
struct QueryPlanT;

bool operator==(const QueryPlanT &lhs, const QueryPlanT &rhs);
bool operator!=(const QueryPlanT &lhs, const QueryPlanT &rhs);

inline const flatbuffers::TypeTable *QueryPlanTypeTable();

enum class OperatorType : uint8_t {
  INVALID = 0,
  PROJECTION = 1,
  FILTER = 2,
  AGGREGATE_AND_GROUP_BY = 3,
  WINDOW = 4,
  UNNEST = 5,
  LIMIT = 6,
  ORDER_BY = 7,
  TOP_N = 8,
  COPY_FROM_FILE = 9,
  COPY_TO_FILE = 10,
  DISTINCT = 11,
  INDEX_SCAN = 12,
  GET = 13,
  CHUNK_GET = 14,
  DELIM_GET = 15,
  EXPRESSION_GET = 16,
  TABLE_FUNCTION = 17,
  EMPTY_RESULT = 18,
  CTE_REF = 19,
  JOIN = 20,
  DELIM_JOIN = 21,
  COMPARISON_JOIN = 22,
  ANY_JOIN = 23,
  CROSS_PRODUCT = 24,
  UNION = 25,
  EXCEPT = 26,
  INTERSECT = 27,
  RECURSIVE_CTE = 28,
  INSERT = 29,
  DELETE = 30,
  UPDATE = 31,
  ALTER = 32,
  CREATE_TABLE = 33,
  CREATE_INDEX = 34,
  CREATE_SEQUENCE = 35,
  CREATE_VIEW = 36,
  CREATE_SCHEMA = 37,
  DROP = 38,
  PRAGMA = 39,
  TRANSACTION = 40,
  EXPLAIN = 41,
  PREPARE = 42,
  EXECUTE = 43,
  VACUUM = 44,
  MIN = INVALID,
  MAX = VACUUM
};

inline const OperatorType (&EnumValuesOperatorType())[45] {
  static const OperatorType values[] = {
    OperatorType::INVALID,
    OperatorType::PROJECTION,
    OperatorType::FILTER,
    OperatorType::AGGREGATE_AND_GROUP_BY,
    OperatorType::WINDOW,
    OperatorType::UNNEST,
    OperatorType::LIMIT,
    OperatorType::ORDER_BY,
    OperatorType::TOP_N,
    OperatorType::COPY_FROM_FILE,
    OperatorType::COPY_TO_FILE,
    OperatorType::DISTINCT,
    OperatorType::INDEX_SCAN,
    OperatorType::GET,
    OperatorType::CHUNK_GET,
    OperatorType::DELIM_GET,
    OperatorType::EXPRESSION_GET,
    OperatorType::TABLE_FUNCTION,
    OperatorType::EMPTY_RESULT,
    OperatorType::CTE_REF,
    OperatorType::JOIN,
    OperatorType::DELIM_JOIN,
    OperatorType::COMPARISON_JOIN,
    OperatorType::ANY_JOIN,
    OperatorType::CROSS_PRODUCT,
    OperatorType::UNION,
    OperatorType::EXCEPT,
    OperatorType::INTERSECT,
    OperatorType::RECURSIVE_CTE,
    OperatorType::INSERT,
    OperatorType::DELETE,
    OperatorType::UPDATE,
    OperatorType::ALTER,
    OperatorType::CREATE_TABLE,
    OperatorType::CREATE_INDEX,
    OperatorType::CREATE_SEQUENCE,
    OperatorType::CREATE_VIEW,
    OperatorType::CREATE_SCHEMA,
    OperatorType::DROP,
    OperatorType::PRAGMA,
    OperatorType::TRANSACTION,
    OperatorType::EXPLAIN,
    OperatorType::PREPARE,
    OperatorType::EXECUTE,
    OperatorType::VACUUM
  };
  return values;
}

inline const char * const *EnumNamesOperatorType() {
  static const char * const names[46] = {
    "INVALID",
    "PROJECTION",
    "FILTER",
    "AGGREGATE_AND_GROUP_BY",
    "WINDOW",
    "UNNEST",
    "LIMIT",
    "ORDER_BY",
    "TOP_N",
    "COPY_FROM_FILE",
    "COPY_TO_FILE",
    "DISTINCT",
    "INDEX_SCAN",
    "GET",
    "CHUNK_GET",
    "DELIM_GET",
    "EXPRESSION_GET",
    "TABLE_FUNCTION",
    "EMPTY_RESULT",
    "CTE_REF",
    "JOIN",
    "DELIM_JOIN",
    "COMPARISON_JOIN",
    "ANY_JOIN",
    "CROSS_PRODUCT",
    "UNION",
    "EXCEPT",
    "INTERSECT",
    "RECURSIVE_CTE",
    "INSERT",
    "DELETE",
    "UPDATE",
    "ALTER",
    "CREATE_TABLE",
    "CREATE_INDEX",
    "CREATE_SEQUENCE",
    "CREATE_VIEW",
    "CREATE_SCHEMA",
    "DROP",
    "PRAGMA",
    "TRANSACTION",
    "EXPLAIN",
    "PREPARE",
    "EXECUTE",
    "VACUUM",
    nullptr
  };
  return names;
}

inline const char *EnumNameOperatorType(OperatorType e) {
  if (flatbuffers::IsOutRange(e, OperatorType::INVALID, OperatorType::VACUUM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOperatorType()[index];
}

struct QueryPlanT : public flatbuffers::NativeTable {
  typedef QueryPlan TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.QueryPlanT";
  }
  std::vector<uint64_t> operator_children;
  std::vector<uint64_t> operator_child_offsets;
  std::vector<duckdb_webapi::proto::OperatorType> operator_types;
  QueryPlanT() {
  }
};

inline bool operator==(const QueryPlanT &lhs, const QueryPlanT &rhs) {
  return
      (lhs.operator_children == rhs.operator_children) &&
      (lhs.operator_child_offsets == rhs.operator_child_offsets) &&
      (lhs.operator_types == rhs.operator_types);
}

inline bool operator!=(const QueryPlanT &lhs, const QueryPlanT &rhs) {
    return !(lhs == rhs);
}


struct QueryPlan FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef QueryPlanT NativeTableType;
  typedef QueryPlanBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return QueryPlanTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.QueryPlan";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPERATOR_CHILDREN = 4,
    VT_OPERATOR_CHILD_OFFSETS = 6,
    VT_OPERATOR_TYPES = 8
  };
  const flatbuffers::Vector<uint64_t> *operator_children() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_OPERATOR_CHILDREN);
  }
  const flatbuffers::Vector<uint64_t> *operator_child_offsets() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_OPERATOR_CHILD_OFFSETS);
  }
  const flatbuffers::Vector<uint8_t> *operator_types() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_OPERATOR_TYPES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OPERATOR_CHILDREN) &&
           verifier.VerifyVector(operator_children()) &&
           VerifyOffset(verifier, VT_OPERATOR_CHILD_OFFSETS) &&
           verifier.VerifyVector(operator_child_offsets()) &&
           VerifyOffset(verifier, VT_OPERATOR_TYPES) &&
           verifier.VerifyVector(operator_types()) &&
           verifier.EndTable();
  }
  QueryPlanT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QueryPlanT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<QueryPlan> Pack(flatbuffers::FlatBufferBuilder &_fbb, const QueryPlanT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QueryPlanBuilder {
  typedef QueryPlan Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_operator_children(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> operator_children) {
    fbb_.AddOffset(QueryPlan::VT_OPERATOR_CHILDREN, operator_children);
  }
  void add_operator_child_offsets(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> operator_child_offsets) {
    fbb_.AddOffset(QueryPlan::VT_OPERATOR_CHILD_OFFSETS, operator_child_offsets);
  }
  void add_operator_types(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> operator_types) {
    fbb_.AddOffset(QueryPlan::VT_OPERATOR_TYPES, operator_types);
  }
  explicit QueryPlanBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<QueryPlan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<QueryPlan>(end);
    return o;
  }
};

inline flatbuffers::Offset<QueryPlan> CreateQueryPlan(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> operator_children = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> operator_child_offsets = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> operator_types = 0) {
  QueryPlanBuilder builder_(_fbb);
  builder_.add_operator_types(operator_types);
  builder_.add_operator_child_offsets(operator_child_offsets);
  builder_.add_operator_children(operator_children);
  return builder_.Finish();
}

inline flatbuffers::Offset<QueryPlan> CreateQueryPlanDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *operator_children = nullptr,
    const std::vector<uint64_t> *operator_child_offsets = nullptr,
    const std::vector<uint8_t> *operator_types = nullptr) {
  auto operator_children__ = operator_children ? _fbb.CreateVector<uint64_t>(*operator_children) : 0;
  auto operator_child_offsets__ = operator_child_offsets ? _fbb.CreateVector<uint64_t>(*operator_child_offsets) : 0;
  auto operator_types__ = operator_types ? _fbb.CreateVector<uint8_t>(*operator_types) : 0;
  return duckdb_webapi::proto::CreateQueryPlan(
      _fbb,
      operator_children__,
      operator_child_offsets__,
      operator_types__);
}

flatbuffers::Offset<QueryPlan> CreateQueryPlan(flatbuffers::FlatBufferBuilder &_fbb, const QueryPlanT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline QueryPlanT *QueryPlan::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<duckdb_webapi::proto::QueryPlanT> _o = std::unique_ptr<duckdb_webapi::proto::QueryPlanT>(new QueryPlanT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QueryPlan::UnPackTo(QueryPlanT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = operator_children(); if (_e) { _o->operator_children.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->operator_children[_i] = _e->Get(_i); } } }
  { auto _e = operator_child_offsets(); if (_e) { _o->operator_child_offsets.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->operator_child_offsets[_i] = _e->Get(_i); } } }
  { auto _e = operator_types(); if (_e) { _o->operator_types.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->operator_types[_i] = static_cast<duckdb_webapi::proto::OperatorType>(_e->Get(_i)); } } }
}

inline flatbuffers::Offset<QueryPlan> QueryPlan::Pack(flatbuffers::FlatBufferBuilder &_fbb, const QueryPlanT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQueryPlan(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<QueryPlan> CreateQueryPlan(flatbuffers::FlatBufferBuilder &_fbb, const QueryPlanT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const QueryPlanT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _operator_children = _o->operator_children.size() ? _fbb.CreateVector(_o->operator_children) : 0;
  auto _operator_child_offsets = _o->operator_child_offsets.size() ? _fbb.CreateVector(_o->operator_child_offsets) : 0;
  auto _operator_types = _o->operator_types.size() ? _fbb.CreateVectorScalarCast<uint8_t>(flatbuffers::data(_o->operator_types), _o->operator_types.size()) : 0;
  return duckdb_webapi::proto::CreateQueryPlan(
      _fbb,
      _operator_children,
      _operator_child_offsets,
      _operator_types);
}

inline const flatbuffers::TypeTable *OperatorTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::OperatorTypeTypeTable
  };
  static const char * const names[] = {
    "INVALID",
    "PROJECTION",
    "FILTER",
    "AGGREGATE_AND_GROUP_BY",
    "WINDOW",
    "UNNEST",
    "LIMIT",
    "ORDER_BY",
    "TOP_N",
    "COPY_FROM_FILE",
    "COPY_TO_FILE",
    "DISTINCT",
    "INDEX_SCAN",
    "GET",
    "CHUNK_GET",
    "DELIM_GET",
    "EXPRESSION_GET",
    "TABLE_FUNCTION",
    "EMPTY_RESULT",
    "CTE_REF",
    "JOIN",
    "DELIM_JOIN",
    "COMPARISON_JOIN",
    "ANY_JOIN",
    "CROSS_PRODUCT",
    "UNION",
    "EXCEPT",
    "INTERSECT",
    "RECURSIVE_CTE",
    "INSERT",
    "DELETE",
    "UPDATE",
    "ALTER",
    "CREATE_TABLE",
    "CREATE_INDEX",
    "CREATE_SEQUENCE",
    "CREATE_VIEW",
    "CREATE_SCHEMA",
    "DROP",
    "PRAGMA",
    "TRANSACTION",
    "EXPLAIN",
    "PREPARE",
    "EXECUTE",
    "VACUUM"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 45, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *QueryPlanTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_ULONG, 1, -1 },
    { flatbuffers::ET_ULONG, 1, -1 },
    { flatbuffers::ET_UCHAR, 1, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::OperatorTypeTypeTable
  };
  static const char * const names[] = {
    "operator_children",
    "operator_child_offsets",
    "operator_types"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace proto
}  // namespace duckdb_webapi

#endif  // FLATBUFFERS_GENERATED_QUERYPLAN_DUCKDB_WEBAPI_PROTO_H_
