// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TABLEGEN_DUCKDB_WEBAPI_PROTO_H_
#define FLATBUFFERS_GENERATED_TABLEGEN_DUCKDB_WEBAPI_PROTO_H_

#include "flatbuffers/flatbuffers.h"

#include "value_generated.h"

namespace duckdb_webapi {
namespace proto {

struct DataDistribution;
struct DataDistributionBuilder;
struct DataDistributionT;

struct ColumnSpec;
struct ColumnSpecBuilder;
struct ColumnSpecT;

struct TableSpec;
struct TableSpecBuilder;
struct TableSpecT;

bool operator==(const DataDistributionT &lhs, const DataDistributionT &rhs);
bool operator!=(const DataDistributionT &lhs, const DataDistributionT &rhs);
bool operator==(const ColumnSpecT &lhs, const ColumnSpecT &rhs);
bool operator!=(const ColumnSpecT &lhs, const ColumnSpecT &rhs);
bool operator==(const TableSpecT &lhs, const TableSpecT &rhs);
bool operator!=(const TableSpecT &lhs, const TableSpecT &rhs);

inline const flatbuffers::TypeTable *DataDistributionTypeTable();

inline const flatbuffers::TypeTable *ColumnSpecTypeTable();

inline const flatbuffers::TypeTable *TableSpecTypeTable();

/// A data distribution type
enum class DataDistributionType : uint8_t {
  UNIFORM = 0,
  BERNOULLI = 1,
  BINOMIAL = 2,
  GEOMETRIC = 3,
  NEGATIVE_BINOMIAL = 4,
  POISSON = 5,
  EXPONENTIAL = 6,
  GAMMA = 7,
  WEIBULL = 8,
  EXTREME_VALUE = 9,
  NORMAL = 10,
  LOG_NORMAL = 11,
  CHI_SQUARED = 12,
  CAUCHY = 13,
  FISHER_F = 14,
  STUDENT_T = 15,
  DISCRETE = 16,
  PIECEWISE_CONSTANT = 17,
  PIECEWISE_LINEAR = 18,
  MIN = UNIFORM,
  MAX = PIECEWISE_LINEAR
};

inline const DataDistributionType (&EnumValuesDataDistributionType())[19] {
  static const DataDistributionType values[] = {
    DataDistributionType::UNIFORM,
    DataDistributionType::BERNOULLI,
    DataDistributionType::BINOMIAL,
    DataDistributionType::GEOMETRIC,
    DataDistributionType::NEGATIVE_BINOMIAL,
    DataDistributionType::POISSON,
    DataDistributionType::EXPONENTIAL,
    DataDistributionType::GAMMA,
    DataDistributionType::WEIBULL,
    DataDistributionType::EXTREME_VALUE,
    DataDistributionType::NORMAL,
    DataDistributionType::LOG_NORMAL,
    DataDistributionType::CHI_SQUARED,
    DataDistributionType::CAUCHY,
    DataDistributionType::FISHER_F,
    DataDistributionType::STUDENT_T,
    DataDistributionType::DISCRETE,
    DataDistributionType::PIECEWISE_CONSTANT,
    DataDistributionType::PIECEWISE_LINEAR
  };
  return values;
}

inline const char * const *EnumNamesDataDistributionType() {
  static const char * const names[20] = {
    "UNIFORM",
    "BERNOULLI",
    "BINOMIAL",
    "GEOMETRIC",
    "NEGATIVE_BINOMIAL",
    "POISSON",
    "EXPONENTIAL",
    "GAMMA",
    "WEIBULL",
    "EXTREME_VALUE",
    "NORMAL",
    "LOG_NORMAL",
    "CHI_SQUARED",
    "CAUCHY",
    "FISHER_F",
    "STUDENT_T",
    "DISCRETE",
    "PIECEWISE_CONSTANT",
    "PIECEWISE_LINEAR",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataDistributionType(DataDistributionType e) {
  if (flatbuffers::IsOutRange(e, DataDistributionType::UNIFORM, DataDistributionType::PIECEWISE_LINEAR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataDistributionType()[index];
}

struct DataDistributionT : public flatbuffers::NativeTable {
  typedef DataDistribution TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.DataDistributionT";
  }
  duckdb_webapi::proto::DataDistributionType distribution_type;
  DataDistributionT()
      : distribution_type(duckdb_webapi::proto::DataDistributionType::UNIFORM) {
  }
};

inline bool operator==(const DataDistributionT &lhs, const DataDistributionT &rhs) {
  return
      (lhs.distribution_type == rhs.distribution_type);
}

inline bool operator!=(const DataDistributionT &lhs, const DataDistributionT &rhs) {
    return !(lhs == rhs);
}


/// A data distribution
struct DataDistribution FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DataDistributionT NativeTableType;
  typedef DataDistributionBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DataDistributionTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.DataDistribution";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DISTRIBUTION_TYPE = 4
  };
  duckdb_webapi::proto::DataDistributionType distribution_type() const {
    return static_cast<duckdb_webapi::proto::DataDistributionType>(GetField<uint8_t>(VT_DISTRIBUTION_TYPE, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DISTRIBUTION_TYPE) &&
           verifier.EndTable();
  }
  DataDistributionT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DataDistributionT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<DataDistribution> Pack(flatbuffers::FlatBufferBuilder &_fbb, const DataDistributionT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DataDistributionBuilder {
  typedef DataDistribution Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_distribution_type(duckdb_webapi::proto::DataDistributionType distribution_type) {
    fbb_.AddElement<uint8_t>(DataDistribution::VT_DISTRIBUTION_TYPE, static_cast<uint8_t>(distribution_type), 0);
  }
  explicit DataDistributionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<DataDistribution> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DataDistribution>(end);
    return o;
  }
};

inline flatbuffers::Offset<DataDistribution> CreateDataDistribution(
    flatbuffers::FlatBufferBuilder &_fbb,
    duckdb_webapi::proto::DataDistributionType distribution_type = duckdb_webapi::proto::DataDistributionType::UNIFORM) {
  DataDistributionBuilder builder_(_fbb);
  builder_.add_distribution_type(distribution_type);
  return builder_.Finish();
}

flatbuffers::Offset<DataDistribution> CreateDataDistribution(flatbuffers::FlatBufferBuilder &_fbb, const DataDistributionT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ColumnSpecT : public flatbuffers::NativeTable {
  typedef ColumnSpec TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.ColumnSpecT";
  }
  std::string name;
  std::unique_ptr<duckdb_webapi::proto::LogicalType> value_type;
  std::unique_ptr<duckdb_webapi::proto::DataDistributionT> value_distribution;
  std::unique_ptr<duckdb_webapi::proto::DataDistributionT> null_distribution;
  ColumnSpecT() {
  }
};

inline bool operator==(const ColumnSpecT &lhs, const ColumnSpecT &rhs) {
  return
      (lhs.name == rhs.name) &&
      (lhs.value_type == rhs.value_type) &&
      (lhs.value_distribution == rhs.value_distribution) &&
      (lhs.null_distribution == rhs.null_distribution);
}

inline bool operator!=(const ColumnSpecT &lhs, const ColumnSpecT &rhs) {
    return !(lhs == rhs);
}


/// A table specification
struct ColumnSpec FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ColumnSpecT NativeTableType;
  typedef ColumnSpecBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ColumnSpecTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.ColumnSpec";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE_DISTRIBUTION = 8,
    VT_NULL_DISTRIBUTION = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const duckdb_webapi::proto::LogicalType *value_type() const {
    return GetStruct<const duckdb_webapi::proto::LogicalType *>(VT_VALUE_TYPE);
  }
  const duckdb_webapi::proto::DataDistribution *value_distribution() const {
    return GetPointer<const duckdb_webapi::proto::DataDistribution *>(VT_VALUE_DISTRIBUTION);
  }
  const duckdb_webapi::proto::DataDistribution *null_distribution() const {
    return GetPointer<const duckdb_webapi::proto::DataDistribution *>(VT_NULL_DISTRIBUTION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<duckdb_webapi::proto::LogicalType>(verifier, VT_VALUE_TYPE) &&
           VerifyOffset(verifier, VT_VALUE_DISTRIBUTION) &&
           verifier.VerifyTable(value_distribution()) &&
           VerifyOffset(verifier, VT_NULL_DISTRIBUTION) &&
           verifier.VerifyTable(null_distribution()) &&
           verifier.EndTable();
  }
  ColumnSpecT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ColumnSpecT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ColumnSpec> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ColumnSpecT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ColumnSpecBuilder {
  typedef ColumnSpec Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(ColumnSpec::VT_NAME, name);
  }
  void add_value_type(const duckdb_webapi::proto::LogicalType *value_type) {
    fbb_.AddStruct(ColumnSpec::VT_VALUE_TYPE, value_type);
  }
  void add_value_distribution(flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> value_distribution) {
    fbb_.AddOffset(ColumnSpec::VT_VALUE_DISTRIBUTION, value_distribution);
  }
  void add_null_distribution(flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> null_distribution) {
    fbb_.AddOffset(ColumnSpec::VT_NULL_DISTRIBUTION, null_distribution);
  }
  explicit ColumnSpecBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ColumnSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ColumnSpec>(end);
    return o;
  }
};

inline flatbuffers::Offset<ColumnSpec> CreateColumnSpec(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    const duckdb_webapi::proto::LogicalType *value_type = 0,
    flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> value_distribution = 0,
    flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> null_distribution = 0) {
  ColumnSpecBuilder builder_(_fbb);
  builder_.add_null_distribution(null_distribution);
  builder_.add_value_distribution(value_distribution);
  builder_.add_value_type(value_type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<ColumnSpec> CreateColumnSpecDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const duckdb_webapi::proto::LogicalType *value_type = 0,
    flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> value_distribution = 0,
    flatbuffers::Offset<duckdb_webapi::proto::DataDistribution> null_distribution = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return duckdb_webapi::proto::CreateColumnSpec(
      _fbb,
      name__,
      value_type,
      value_distribution,
      null_distribution);
}

flatbuffers::Offset<ColumnSpec> CreateColumnSpec(flatbuffers::FlatBufferBuilder &_fbb, const ColumnSpecT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TableSpecT : public flatbuffers::NativeTable {
  typedef TableSpec TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.TableSpecT";
  }
  std::string name;
  std::vector<std::unique_ptr<duckdb_webapi::proto::ColumnSpecT>> columns;
  uint64_t rows;
  TableSpecT()
      : rows(0) {
  }
};

inline bool operator==(const TableSpecT &lhs, const TableSpecT &rhs) {
  return
      (lhs.name == rhs.name) &&
      (lhs.columns == rhs.columns) &&
      (lhs.rows == rhs.rows);
}

inline bool operator!=(const TableSpecT &lhs, const TableSpecT &rhs) {
    return !(lhs == rhs);
}


/// A table specification
struct TableSpec FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TableSpecT NativeTableType;
  typedef TableSpecBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TableSpecTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "duckdb_webapi.proto.TableSpec";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_COLUMNS = 6,
    VT_ROWS = 8
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>> *columns() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>> *>(VT_COLUMNS);
  }
  uint64_t rows() const {
    return GetField<uint64_t>(VT_ROWS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_COLUMNS) &&
           verifier.VerifyVector(columns()) &&
           verifier.VerifyVectorOfTables(columns()) &&
           VerifyField<uint64_t>(verifier, VT_ROWS) &&
           verifier.EndTable();
  }
  TableSpecT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TableSpecT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<TableSpec> Pack(flatbuffers::FlatBufferBuilder &_fbb, const TableSpecT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TableSpecBuilder {
  typedef TableSpec Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(TableSpec::VT_NAME, name);
  }
  void add_columns(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>>> columns) {
    fbb_.AddOffset(TableSpec::VT_COLUMNS, columns);
  }
  void add_rows(uint64_t rows) {
    fbb_.AddElement<uint64_t>(TableSpec::VT_ROWS, rows, 0);
  }
  explicit TableSpecBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TableSpec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TableSpec>(end);
    return o;
  }
};

inline flatbuffers::Offset<TableSpec> CreateTableSpec(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>>> columns = 0,
    uint64_t rows = 0) {
  TableSpecBuilder builder_(_fbb);
  builder_.add_rows(rows);
  builder_.add_columns(columns);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<TableSpec> CreateTableSpecDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>> *columns = nullptr,
    uint64_t rows = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto columns__ = columns ? _fbb.CreateVector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>>(*columns) : 0;
  return duckdb_webapi::proto::CreateTableSpec(
      _fbb,
      name__,
      columns__,
      rows);
}

flatbuffers::Offset<TableSpec> CreateTableSpec(flatbuffers::FlatBufferBuilder &_fbb, const TableSpecT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DataDistributionT *DataDistribution::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<duckdb_webapi::proto::DataDistributionT> _o = std::unique_ptr<duckdb_webapi::proto::DataDistributionT>(new DataDistributionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DataDistribution::UnPackTo(DataDistributionT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = distribution_type(); _o->distribution_type = _e; }
}

inline flatbuffers::Offset<DataDistribution> DataDistribution::Pack(flatbuffers::FlatBufferBuilder &_fbb, const DataDistributionT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDataDistribution(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<DataDistribution> CreateDataDistribution(flatbuffers::FlatBufferBuilder &_fbb, const DataDistributionT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const DataDistributionT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _distribution_type = _o->distribution_type;
  return duckdb_webapi::proto::CreateDataDistribution(
      _fbb,
      _distribution_type);
}

inline ColumnSpecT *ColumnSpec::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<duckdb_webapi::proto::ColumnSpecT> _o = std::unique_ptr<duckdb_webapi::proto::ColumnSpecT>(new ColumnSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ColumnSpec::UnPackTo(ColumnSpecT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = value_type(); if (_e) _o->value_type = std::unique_ptr<duckdb_webapi::proto::LogicalType>(new duckdb_webapi::proto::LogicalType(*_e)); }
  { auto _e = value_distribution(); if (_e) _o->value_distribution = std::unique_ptr<duckdb_webapi::proto::DataDistributionT>(_e->UnPack(_resolver)); }
  { auto _e = null_distribution(); if (_e) _o->null_distribution = std::unique_ptr<duckdb_webapi::proto::DataDistributionT>(_e->UnPack(_resolver)); }
}

inline flatbuffers::Offset<ColumnSpec> ColumnSpec::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ColumnSpecT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateColumnSpec(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ColumnSpec> CreateColumnSpec(flatbuffers::FlatBufferBuilder &_fbb, const ColumnSpecT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ColumnSpecT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _value_type = _o->value_type ? _o->value_type.get() : 0;
  auto _value_distribution = _o->value_distribution ? CreateDataDistribution(_fbb, _o->value_distribution.get(), _rehasher) : 0;
  auto _null_distribution = _o->null_distribution ? CreateDataDistribution(_fbb, _o->null_distribution.get(), _rehasher) : 0;
  return duckdb_webapi::proto::CreateColumnSpec(
      _fbb,
      _name,
      _value_type,
      _value_distribution,
      _null_distribution);
}

inline TableSpecT *TableSpec::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<duckdb_webapi::proto::TableSpecT> _o = std::unique_ptr<duckdb_webapi::proto::TableSpecT>(new TableSpecT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TableSpec::UnPackTo(TableSpecT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = columns(); if (_e) { _o->columns.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->columns[_i] = std::unique_ptr<duckdb_webapi::proto::ColumnSpecT>(_e->Get(_i)->UnPack(_resolver)); } } }
  { auto _e = rows(); _o->rows = _e; }
}

inline flatbuffers::Offset<TableSpec> TableSpec::Pack(flatbuffers::FlatBufferBuilder &_fbb, const TableSpecT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTableSpec(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<TableSpec> CreateTableSpec(flatbuffers::FlatBufferBuilder &_fbb, const TableSpecT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const TableSpecT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _columns = _o->columns.size() ? _fbb.CreateVector<flatbuffers::Offset<duckdb_webapi::proto::ColumnSpec>> (_o->columns.size(), [](size_t i, _VectorArgs *__va) { return CreateColumnSpec(*__va->__fbb, __va->__o->columns[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _rows = _o->rows;
  return duckdb_webapi::proto::CreateTableSpec(
      _fbb,
      _name,
      _columns,
      _rows);
}

inline const flatbuffers::TypeTable *DataDistributionTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::DataDistributionTypeTypeTable
  };
  static const char * const names[] = {
    "UNIFORM",
    "BERNOULLI",
    "BINOMIAL",
    "GEOMETRIC",
    "NEGATIVE_BINOMIAL",
    "POISSON",
    "EXPONENTIAL",
    "GAMMA",
    "WEIBULL",
    "EXTREME_VALUE",
    "NORMAL",
    "LOG_NORMAL",
    "CHI_SQUARED",
    "CAUCHY",
    "FISHER_F",
    "STUDENT_T",
    "DISCRETE",
    "PIECEWISE_CONSTANT",
    "PIECEWISE_LINEAR"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 19, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *DataDistributionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::DataDistributionTypeTypeTable
  };
  static const char * const names[] = {
    "distribution_type"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ColumnSpecTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::LogicalTypeTypeTable,
    duckdb_webapi::proto::DataDistributionTypeTable
  };
  static const char * const names[] = {
    "name",
    "value_type",
    "value_distribution",
    "null_distribution"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *TableSpecTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 0 },
    { flatbuffers::ET_ULONG, 0, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    duckdb_webapi::proto::ColumnSpecTypeTable
  };
  static const char * const names[] = {
    "name",
    "columns",
    "rows"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace proto
}  // namespace duckdb_webapi

#endif  // FLATBUFFERS_GENERATED_TABLEGEN_DUCKDB_WEBAPI_PROTO_H_
