#!/bin/bash
set -euo pipefail

PROJECT_ROOT="$(cd $(dirname "$BASH_SOURCE[0]") && cd .. && pwd)" &> /dev/null

npx prettier \
    --write "$PROJECT_ROOT/**/*.{js,json,ts,tsx,d.ts,css,scss}" \
    --config "$PROJECT_ROOT/.prettierrc" \
    --ignore-path "$PROJECT_ROOT/.prettierignore"
