use super::ast_nodes_dashql::*;
use super::ast_nodes_sql::*;
use super::dson::*;
use dashql_proto::syntax as sx;

#[derive(Clone, Copy, Debug, PartialEq, Hash)]
pub enum ASTNode<'a> {
    Null,

    Boolean(bool),
    UInt32(u32),
    UInt32Bitmap(u32),
    StringRef(&'a str),
    Array(&'a [ASTNode<'a>]),

    CharacterType(sx::CharacterType),
    ColumnConstraint(sx::ColumnConstraint),
    CombineModifier(sx::CombineModifier),
    CombineOperation(sx::CombineOperation),
    ConstType(sx::AConstType),
    ConstraintAttribute(sx::ConstraintAttribute),
    ExpressionOperator(sx::ExpressionOperator),
    ExtractTarget(sx::ExtractTarget),
    FetchMethodType(sx::FetchMethodType),
    GroupByItemType(sx::GroupByItemType),
    InputComponentType(sx::InputComponentType),
    IntervalType(sx::IntervalType),
    JoinType(sx::JoinType),
    KnownFunction(sx::KnownFunction),
    LoadMethodType(sx::LoadMethodType),
    NumericType(sx::NumericType),
    OnCommitOption(sx::OnCommitOption),
    OrderDirection(sx::OrderDirection),
    OrderNullRule(sx::OrderNullRule),
    RowLockingBlockBehavior(sx::RowLockingBlockBehavior),
    RowLockingStrength(sx::RowLockingStrength),
    SampleCountUnit(sx::SampleCountUnit),
    SubqueryQuantifier(sx::SubqueryQuantifier),
    TempType(sx::TempType),
    TrimDirection(sx::TrimDirection),
    VizComponentType(sx::VizComponentType),
    WindowBoundDirection(sx::WindowBoundDirection),
    WindowBoundMode(sx::WindowBoundMode),
    WindowExclusionMode(sx::WindowExclusionMode),
    WindowRangeMode(sx::WindowRangeMode),

    GenericTypeSpec(&'a GenericType<'a>),
    NumericTypeSpec(&'a NumericType<'a>),
    BitTypeSpec(&'a BitType<'a>),
    CharacterTypeSpec(&'a CharacterType<'a>),
    TimestampTypeSpec(&'a TimestampType<'a>),
    TimeTypeSpec(&'a TimeType<'a>),

    Sample(&'a Sample<'a>),
    Alias(&'a Alias<'a>),
    Into(&'a Into<'a>),

    ColumnConstraintArgument(&'a ColumnConstraintArgument<'a>),
    ColumnConstraintInfo(&'a ColumnConstraint<'a>),
    GenericOption(&'a GenericOption<'a>),
    RowsFromItem(&'a RowsFromItem<'a>),
    ColumnDefinition(&'a ColumnDefinition<'a>),
    FunctionTable(&'a FunctionTable<'a>),
    JoinedTable(&'a JoinedTable<'a>),
    TableRef(TableRef<'a>),
    ColumnRef(NamePath<'a>),

    TrimFunctionArguments(&'a TrimFunctionArguments<'a>),
    OverlayFunctionArguments(&'a OverlayFunctionArguments<'a>),
    SubstringFunctionArguments(&'a SubstringFunctionArguments<'a>),
    PositionFunctionArguments(&'a PositionFunctionArguments<'a>),
    ExtractFunctionArguments(&'a ExtractFunctionArguments<'a>),
    CastFunctionArguments(&'a CastFunctionArguments<'a>),
    TreatFunctionArguments(&'a TreatFunctionArguments<'a>),

    CaseExpression(&'a CaseExpression<'a>),
    CaseExpressionClause(&'a CaseExpressionClause<'a>),
    CommonTableExpression(&'a CommonTableExpression<'a>),
    ConstCastExpression(ConstCastExpression<'a>),
    ExistsExpression(&'a ExistsExpression<'a>),
    Expression(Expression<'a>),
    FunctionArgument(&'a FunctionArgument<'a>),
    FunctionExpression(&'a FunctionExpression<'a>),
    GroupByItem(GroupByItem<'a>),
    Indirection(Indirection<'a>),
    IndirectionExpression(&'a IndirectionExpression<'a>),
    IntervalSpecification(&'a IntervalSpecification<'a>),
    OrderSpecification(&'a OrderSpecification<'a>),
    ParameterRef(&'a ParameterRef<'a>),
    ResultTarget(&'a ResultTarget<'a>),
    RowLocking(&'a RowLocking<'a>),
    SQLType(&'a SQLType<'a>),
    SelectStatementExpression(&'a SelectStatementExpression<'a>),
    SubqueryExpression(&'a SubqueryExpression<'a>),
    TableSample(&'a TableSample<'a>),
    TypeCastExpression(&'a TypeCastExpression<'a>),
    TypeTestExpression(&'a TypeTestExpression<'a>),
    WindowDefinition(&'a WindowDefinition<'a>),
    WindowFrame(&'a WindowFrame<'a>),
    WindowFrameBound(&'a WindowFrameBound<'a>),

    Create(&'a CreateStatement<'a>),
    CreateAs(&'a CreateAsStatement<'a>),
    CreateView(&'a CreateViewStatement<'a>),
    SelectStatement(&'a SelectStatement<'a>),
    SetStatement(&'a SetStatement<'a>),
    FetchStatement(&'a FetchStatement<'a>),
    InputStatement(&'a InputStatement<'a>),
    LoadStatement(&'a LoadStatement<'a>),
    VizComponent(&'a VizComponent<'a>),
    VizStatement(&'a VizStatement<'a>),

    Dson(DsonValue<'a>),
}

impl<'a> Default for ASTNode<'a> {
    fn default() -> Self {
        ASTNode::Null
    }
}
