use super::ast_nodes_dashql::*;
use super::ast_nodes_sql::*;
use super::dson::*;
use dashql_proto as proto;

#[derive(Clone, Copy, Debug, PartialEq, Hash)]
pub enum ASTNode<'a> {
    Null,

    Boolean(bool),
    UInt32(u32),
    UInt32Bitmap(u32),
    Array(&'a [ASTNode<'a>], usize),

    Identifier(&'a str),
    LiteralFloat(&'a str),
    LiteralInteger(&'a str),
    LiteralNull(&'a str),
    LiteralString(&'a str),
    LiteralInterval(&'a str),

    CharacterType(proto::CharacterType),
    ColumnConstraint(proto::ColumnConstraint),
    CombineModifier(proto::CombineModifier),
    CombineOperation(proto::CombineOperation),
    ConstType(proto::AConstType),
    ConstraintAttribute(proto::ConstraintAttribute),
    ExpressionOperator(proto::ExpressionOperator),
    ExtractTarget(proto::ExtractTarget),
    ImportMethodType(proto::ImportMethodType),
    GroupByItemType(proto::GroupByItemType),
    InputComponentType(proto::InputComponentType),
    IntervalType(proto::IntervalType),
    JoinType(proto::JoinType),
    KeyMatch(proto::KeyMatch),
    KeyActionCommand(proto::KeyActionCommand),
    KeyActionTrigger(proto::KeyActionTrigger),
    KnownFunction(proto::KnownFunction),
    LoadMethodType(proto::LoadMethodType),
    NumericType(proto::NumericType),
    OnCommitOption(proto::OnCommitOption),
    OrderDirection(proto::OrderDirection),
    OrderNullRule(proto::OrderNullRule),
    RowLockingBlockBehavior(proto::RowLockingBlockBehavior),
    RowLockingStrength(proto::RowLockingStrength),
    SampleCountUnit(proto::SampleCountUnit),
    SubqueryQuantifier(proto::SubqueryQuantifier),
    TableConstraint(proto::TableConstraint),
    TempType(proto::TempType),
    TrimDirection(proto::TrimDirection),
    VizComponentType(proto::VizComponentType),
    WindowBoundDirection(proto::WindowBoundDirection),
    WindowBoundMode(proto::WindowBoundMode),
    WindowExclusionMode(proto::WindowExclusionMode),
    WindowRangeMode(proto::WindowRangeMode),

    GenericTypeSpec(&'a GenericType<'a>),
    NumericTypeSpec(&'a NumericType<'a>),
    BitTypeSpec(&'a BitType<'a>),
    CharacterTypeSpec(&'a CharacterType<'a>),
    TimestampTypeSpec(&'a TimestampType<'a>),
    TimeTypeSpec(&'a TimeType<'a>),

    Sample(&'a Sample<'a>),
    Alias(&'a Alias<'a>),
    Into(&'a Into<'a>),

    ColumnConstraintSpec(&'a ColumnConstraintSpec<'a>),
    TableConstraintSpec(&'a TableConstraintSpec<'a>),
    GenericDefinition(&'a GenericDefinition<'a>),
    GenericOption(&'a GenericOption<'a>),
    RowsFromItem(&'a RowsFromItem<'a>),
    ColumnDefinition(&'a ColumnDefinition<'a>),
    FunctionTable(&'a FunctionTable<'a>),
    JoinedTable(&'a JoinedTable<'a>),
    TableRef(TableRef<'a>),
    ColumnRef(NamePath<'a>),

    TrimFunctionArguments(&'a TrimFunctionArguments<'a>),
    OverlayFunctionArguments(&'a OverlayFunctionArguments<'a>),
    SubstringFunctionArguments(&'a SubstringFunctionArguments<'a>),
    PositionFunctionArguments(&'a PositionFunctionArguments<'a>),
    ExtractFunctionArguments(&'a ExtractFunctionArguments<'a>),
    CastFunctionArguments(&'a CastFunctionArguments<'a>),
    TreatFunctionArguments(&'a TreatFunctionArguments<'a>),

    CaseExpression(&'a CaseExpression<'a>),
    CaseExpressionClause(&'a CaseExpressionClause<'a>),
    CommonTableExpression(&'a CommonTableExpression<'a>),
    ConstCastExpression(ConstCastExpression<'a>),
    ExistsExpression(&'a ExistsExpression<'a>),
    Expression(Expression<'a>),
    FunctionArgument(&'a FunctionArgument<'a>),
    FunctionExpression(&'a FunctionExpression<'a>),
    GroupByItem(GroupByItem<'a>),
    Indirection(Indirection<'a>),
    IndirectionExpression(&'a IndirectionExpression<'a>),
    IntervalSpecification(&'a IntervalSpecification<'a>),
    KeyAction(&'a KeyAction),
    OrderSpecification(&'a OrderSpecification<'a>),
    ParameterRef(&'a ParameterRef<'a>),
    ResultTarget(&'a ResultTarget<'a>),
    RowLocking(&'a RowLocking<'a>),
    SQLType(&'a SQLType<'a>),
    SelectStatementExpression(&'a SelectStatementExpression<'a>),
    SubqueryExpression(&'a SubqueryExpression<'a>),
    TableSample(&'a TableSample<'a>),
    TypeCastExpression(&'a TypeCastExpression<'a>),
    TypeTestExpression(&'a TypeTestExpression<'a>),
    WindowDefinition(&'a WindowDefinition<'a>),
    WindowFrame(&'a WindowFrame<'a>),
    WindowFrameBound(&'a WindowFrameBound<'a>),

    Create(&'a CreateStatement<'a>),
    CreateAs(&'a CreateAsStatement<'a>),
    CreateView(&'a CreateViewStatement<'a>),
    DeclareStatement(&'a DeclareStatement<'a>),
    ImportStatement(&'a ImportStatement<'a>),
    SelectStatement(&'a SelectStatement<'a>),
    SetStatement(&'a SetStatement<'a>),
    LoadStatement(&'a LoadStatement<'a>),
    VizStatement(&'a VizStatement<'a>),

    Dson(DsonValue<'a>),
}

impl<'a> Default for ASTNode<'a> {
    fn default() -> Self {
        ASTNode::Null
    }
}
