/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Nov 19 23:02:03 2019. */

#include "rpath.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t tigon_proto_rpath_ArraySlice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t tigon_proto_rpath_ArrayIndexes_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t tigon_proto_rpath_ChildMember_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t tigon_proto_rpath_DescendantMember_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t tigon_proto_rpath_ComponentUnion_fields[5] = {
    PB_ONEOF_FIELD(component,   1, MESSAGE , ONEOF, STATIC  , FIRST, tigon_proto_rpath_ComponentUnion, arraySlice, arraySlice, &tigon_proto_rpath_ArraySlice_fields),
    PB_ONEOF_FIELD(component,   2, MESSAGE , ONEOF, STATIC  , UNION, tigon_proto_rpath_ComponentUnion, arrayIndexes, arrayIndexes, &tigon_proto_rpath_ArrayIndexes_fields),
    PB_ONEOF_FIELD(component,   3, MESSAGE , ONEOF, STATIC  , UNION, tigon_proto_rpath_ComponentUnion, childMember, childMember, &tigon_proto_rpath_ChildMember_fields),
    PB_ONEOF_FIELD(component,   4, MESSAGE , ONEOF, STATIC  , UNION, tigon_proto_rpath_ComponentUnion, descendantMember, descendantMember, &tigon_proto_rpath_DescendantMember_fields),
    PB_LAST_FIELD
};

const pb_field_t tigon_proto_rpath_Path_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, tigon_proto_rpath_Path, components, components, &tigon_proto_rpath_ComponentUnion_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(tigon_proto_rpath_ComponentUnion, component.arraySlice) < 65536 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.arrayIndexes) < 65536 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.childMember) < 65536 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.descendantMember) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_tigon_proto_rpath_ArraySlice_tigon_proto_rpath_ArrayIndexes_tigon_proto_rpath_ChildMember_tigon_proto_rpath_DescendantMember_tigon_proto_rpath_ComponentUnion_tigon_proto_rpath_Path)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(tigon_proto_rpath_ComponentUnion, component.arraySlice) < 256 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.arrayIndexes) < 256 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.childMember) < 256 && pb_membersize(tigon_proto_rpath_ComponentUnion, component.descendantMember) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_tigon_proto_rpath_ArraySlice_tigon_proto_rpath_ArrayIndexes_tigon_proto_rpath_ChildMember_tigon_proto_rpath_DescendantMember_tigon_proto_rpath_ComponentUnion_tigon_proto_rpath_Path)
#endif


/* @@protoc_insertion_point(eof) */
