/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Tue Nov 19 23:02:03 2019. */

#ifndef PB_TIGON_PROTO_RPATH_RPATH_PB_H_INCLUDED
#define PB_TIGON_PROTO_RPATH_RPATH_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _tigon_proto_rpath_ArrayIndexes {
    char dummy_field;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_ArrayIndexes) */
} tigon_proto_rpath_ArrayIndexes;

typedef struct _tigon_proto_rpath_ArraySlice {
    char dummy_field;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_ArraySlice) */
} tigon_proto_rpath_ArraySlice;

typedef struct _tigon_proto_rpath_ChildMember {
    char dummy_field;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_ChildMember) */
} tigon_proto_rpath_ChildMember;

typedef struct _tigon_proto_rpath_DescendantMember {
    char dummy_field;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_DescendantMember) */
} tigon_proto_rpath_DescendantMember;

typedef struct _tigon_proto_rpath_Path {
    pb_callback_t components;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_Path) */
} tigon_proto_rpath_Path;

typedef struct _tigon_proto_rpath_ComponentUnion {
    pb_size_t which_component;
    union {
        tigon_proto_rpath_ArraySlice arraySlice;
        tigon_proto_rpath_ArrayIndexes arrayIndexes;
        tigon_proto_rpath_ChildMember childMember;
        tigon_proto_rpath_DescendantMember descendantMember;
    } component;
/* @@protoc_insertion_point(struct:tigon_proto_rpath_ComponentUnion) */
} tigon_proto_rpath_ComponentUnion;

/* Default values for struct fields */

/* Initializer values for message structs */
#define tigon_proto_rpath_ArraySlice_init_default {0}
#define tigon_proto_rpath_ArrayIndexes_init_default {0}
#define tigon_proto_rpath_ChildMember_init_default {0}
#define tigon_proto_rpath_DescendantMember_init_default {0}
#define tigon_proto_rpath_ComponentUnion_init_default {0, {tigon_proto_rpath_ArraySlice_init_default}}
#define tigon_proto_rpath_Path_init_default      {{{NULL}, NULL}}
#define tigon_proto_rpath_ArraySlice_init_zero   {0}
#define tigon_proto_rpath_ArrayIndexes_init_zero {0}
#define tigon_proto_rpath_ChildMember_init_zero  {0}
#define tigon_proto_rpath_DescendantMember_init_zero {0}
#define tigon_proto_rpath_ComponentUnion_init_zero {0, {tigon_proto_rpath_ArraySlice_init_zero}}
#define tigon_proto_rpath_Path_init_zero         {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define tigon_proto_rpath_Path_components_tag    1
#define tigon_proto_rpath_ComponentUnion_arraySlice_tag 1
#define tigon_proto_rpath_ComponentUnion_arrayIndexes_tag 2
#define tigon_proto_rpath_ComponentUnion_childMember_tag 3
#define tigon_proto_rpath_ComponentUnion_descendantMember_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t tigon_proto_rpath_ArraySlice_fields[1];
extern const pb_field_t tigon_proto_rpath_ArrayIndexes_fields[1];
extern const pb_field_t tigon_proto_rpath_ChildMember_fields[1];
extern const pb_field_t tigon_proto_rpath_DescendantMember_fields[1];
extern const pb_field_t tigon_proto_rpath_ComponentUnion_fields[5];
extern const pb_field_t tigon_proto_rpath_Path_fields[2];

/* Maximum encoded size of messages (where known) */
#define tigon_proto_rpath_ArraySlice_size        0
#define tigon_proto_rpath_ArrayIndexes_size      0
#define tigon_proto_rpath_ChildMember_size       0
#define tigon_proto_rpath_DescendantMember_size  0
#define tigon_proto_rpath_ComponentUnion_size    2
/* tigon_proto_rpath_Path_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RPATH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
