// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: web_api.fbe
// Version: 1.3.0.0

#pragma once

#if defined(__clang__)
#pragma clang system_header
#elif defined(__GNUC__)
#pragma GCC system_header
#elif defined(_MSC_VER)
#pragma system_header
#endif

#include "fbe.h"

namespace web_api {
using namespace FBE;
} // namespace web_api

namespace FBE {
using namespace ::web_api;
} // namespace FBE

namespace web_api {

enum class RawTypeID : uint8_t
{
    INVALID = (uint8_t)0u,
    BOOLEAN = (uint8_t)1u,
    TINYINT = (uint8_t)2u,
    SMALLINT = (uint8_t)3u,
    INTEGER = (uint8_t)4u,
    BIGINT = (uint8_t)5u,
    HASH = (uint8_t)6u,
    POINTER = (uint8_t)7u,
    FLOAT = (uint8_t)8u,
    DOUBLE = (uint8_t)9u,
    VARCHAR = (uint8_t)10u,
    VARBINARY = (uint8_t)11u,
};

template <class TOutputStream>
inline TOutputStream& operator<<(TOutputStream& stream, RawTypeID value)
{
    if (value == RawTypeID::INVALID) { stream << "INVALID"; return stream; }
    if (value == RawTypeID::BOOLEAN) { stream << "BOOLEAN"; return stream; }
    if (value == RawTypeID::TINYINT) { stream << "TINYINT"; return stream; }
    if (value == RawTypeID::SMALLINT) { stream << "SMALLINT"; return stream; }
    if (value == RawTypeID::INTEGER) { stream << "INTEGER"; return stream; }
    if (value == RawTypeID::BIGINT) { stream << "BIGINT"; return stream; }
    if (value == RawTypeID::HASH) { stream << "HASH"; return stream; }
    if (value == RawTypeID::POINTER) { stream << "POINTER"; return stream; }
    if (value == RawTypeID::FLOAT) { stream << "FLOAT"; return stream; }
    if (value == RawTypeID::DOUBLE) { stream << "DOUBLE"; return stream; }
    if (value == RawTypeID::VARCHAR) { stream << "VARCHAR"; return stream; }
    if (value == RawTypeID::VARBINARY) { stream << "VARBINARY"; return stream; }
    stream << "<unknown>";
    return stream;
}

} // namespace web_api
