runs:
  using: "composite"
  steps:
    - name: Install libtinfo6
      shell: bash
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
        sudo dpkg -i libtinfo5_6.4-2_amd64.deb
        rm -f libtinfo5_6.4-2_amd64.deb

        wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb
        sudo dpkg -i libncurses5_6.4-2_amd64.deb
        rm -f libncurses5_6.4-2_amd64.deb

    - name: Cache llvm
      id: cache-llvm
      uses: actions/cache@v4
      with:
        path: |
          ./llvm
        key: llvm-19

    - name: Install llvm
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "19"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
