runs:
  using: "composite"
  steps:
    - name: Install libtinfo5
      shell: bash
      run: |
        sudo apt install libtinfo5

    - name: Cache llvm
      id: cache-llvm
      uses: actions/cache@v4
      with:
        path: |
          ./llvm
        key: llvm-18.1.3

    - name: Install llvm
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18.1.3"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
