runs:
  using: "composite"
  steps:
    - name: Install libtinfo6
      shell: bash
      run: |
        sudo apt install libtinfo6
        sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/libtinfo.so.5

    - name: Cache llvm
      id: cache-llvm
      uses: actions/cache@v4
      with:
        path: |
          ./llvm
        key: llvm-18

    - name: Install llvm
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
