[package]
name = "sqlynx-pack"
version = "0.0.2-dev.17"
description = "Packaging tool for get.sqlynx.app"
edition = "2021"
rust-version = "1.70"
workspace = "../../"

[dev-dependencies]
tauri-build = "2.0.0-beta"
tauri-plugin-updater = "2.0.0-beta"

[dependencies]
futures = "0.3.30"
chrono = "0.4.38"
anyhow = "1.0.86"
semver = "1.0.23"
aws-sdk-s3 = "1.34.0"
aws-credential-types = "1.2.0"
log = "0.4.21"
env_logger = "0.11.3"
git2 = "0.18.3"
regex = "1.10.5"
lazy_static = "1.4.0"
minisign = "0.7.6"

[dependencies.serde]
version = "1.0.203"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.117"
features = ["preserve_order"]

[dependencies.serde_with]
version = "3.8.1"
features = ["json"]

[dependencies.aws-config]
version = "1.5.1"

[dependencies.tokio]
version = "1.38.0"
features = ["full"]

[dependencies.clap]
version = "4.5.7"
features = ["derive"]

[dependencies.uuid]
version = "1.8.0"
features = ["v5"]

[dependencies.toml]
version = "0.8.14"
features = ["preserve_order"]
