mergeInto(LibraryManager.library, {
duckdb_web_fs_read: (blobId, buf, size) => globalThis.DuckDBTrampoline.duckdb_web_fs_read(blobId, buf, size),
duckdb_web_fs_write: (blobId, buf, size) => globalThis.DuckDBTrampoline.duckdb_web_fs_write(blobId, buf, size),
duckdb_web_fs_directory_exists: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_directory_exists(path, pathLen),
duckdb_web_fs_directory_create: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_directory_create(path, pathLen),
duckdb_web_fs_directory_remove: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_directory_remove(path, pathLen),
duckdb_web_fs_directory_list_files: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_directory_list_files(path, pathLen),
duckdb_web_fs_glob: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_glob(path, pathLen),
duckdb_web_fs_file_open: (path, pathLen, flags) => globalThis.DuckDBTrampoline.duckdb_web_fs_file_open(path, pathLen, flags),
duckdb_web_fs_file_close: blobId => globalThis.DuckDBTrampoline.duckdb_web_fs_file_close(blobId),
duckdb_web_fs_file_sync: blobId => globalThis.DuckDBTrampoline.duckdb_web_fs_file_sync(blobId),
duckdb_web_fs_file_get_size: blobId => globalThis.DuckDBTrampoline.duckdb_web_fs_file_get_size(blobId),
duckdb_web_fs_file_get_last_modified_time: blobId => globalThis.DuckDBTrampoline.duckdb_web_fs_file_get_last_modified_time(blobId),
duckdb_web_fs_file_move: (from, fromLen, to, toLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_file_move(from, fromLen, to, toLen),
duckdb_web_fs_file_set_pointer: (blobId, pos) => globalThis.DuckDBTrampoline.duckdb_web_fs_file_set_pointer(blobId, pos),
duckdb_web_fs_file_exists: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_file_exists(path, pathLen),
duckdb_web_fs_file_remove: (path, pathLen) => globalThis.DuckDBTrampoline.duckdb_web_fs_file_remove(path, pathLen),
});