mergeInto(LibraryManager.library, {
    dashql_blob_stream_underflow: (blobId, buf, size) => globalThis.WebDBTrampoline.dashql_blob_stream_underflow(blobId, buf, size),
    dashql_webdb_fs_read: (blobId, buf, size) => globalThis.WebDBTrampoline.dashql_webdb_fs_read(blobId, buf, size),
    dashql_webdb_fs_write: (blobId, buf, size) => globalThis.WebDBTrampoline.dashql_webdb_fs_write(blobId, buf, size),
    dashql_webdb_fs_directory_exists: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_directory_exists(path, pathLen),
    dashql_webdb_fs_directory_create: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_directory_create(path, pathLen),
    dashql_webdb_fs_directory_remove: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_directory_remove(path, pathLen),
    dashql_webdb_fs_directory_list_files: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_directory_list_files(path, pathLen),
    dashql_webdb_fs_glob: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_glob(path, pathLen),
    dashql_webdb_fs_file_open: (path, pathLen, flags) => globalThis.WebDBTrampoline.dashql_webdb_fs_file_open(path, pathLen, flags),
    dashql_webdb_fs_file_close: blobId => globalThis.WebDBTrampoline.dashql_webdb_fs_file_close(blobId),
    dashql_webdb_fs_file_get_size: blobId => globalThis.WebDBTrampoline.dashql_webdb_fs_file_get_size(blobId),
    dashql_webdb_fs_file_get_last_modified_time: blobId => globalThis.WebDBTrampoline.dashql_webdb_fs_file_get_last_modified_time(blobId),
    dashql_webdb_fs_file_move: (from, fromLen, to, toLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_file_move(from, fromLen, to, toLen),
    dashql_webdb_fs_file_set_pointer: (blobId, pos) => globalThis.WebDBTrampoline.dashql_webdb_fs_file_set_pointer(blobId, pos),
    dashql_webdb_fs_file_exists: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_file_exists(path, pathLen),
    dashql_webdb_fs_file_remove: (path, pathLen) => globalThis.WebDBTrampoline.dashql_webdb_fs_file_remove(path, pathLen),
});