# HTTPS – web UI and HTTP remote cache
server {
    listen 443 ssl;
    http2  on;
    server_name buildbuddy.dashql.app;

    ssl_certificate         /etc/letsencrypt/live/buildbuddy.dashql.app/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/buildbuddy.dashql.app/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/buildbuddy.dashql.app/chain.pem;
    ssl_stapling            on;
    ssl_stapling_verify     on;

    auth_basic           "BuildBuddy";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass             http://app:8080;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade $http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_set_header       Host $host;
        proxy_set_header       X-Real-IP $remote_addr;
        proxy_set_header       X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header       X-Forwarded-Proto https;
        proxy_read_timeout     3600s;
        proxy_send_timeout     3600s;
        client_max_body_size   0;
    }
}

# gRPC + TLS – Bazel remote cache / remote execution
server {
    listen 1985 ssl;
    http2  on;
    server_name buildbuddy.dashql.app;

    ssl_certificate         /etc/letsencrypt/live/buildbuddy.dashql.app/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/buildbuddy.dashql.app/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/buildbuddy.dashql.app/chain.pem;
    ssl_stapling            on;
    ssl_stapling_verify     on;

    auth_basic           "BuildBuddy";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        grpc_pass         grpc://app:1985;
        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
    }
}
