name: bazel-cache

services:
  server:
    image: buchgr/bazel-remote-cache:latest
    restart: unless-stopped
    ports:
      - "23032:9092"
      - "23033:8080"
    volumes:
      - /opt/dashql-bazel-cache/data:/opt/bazel-remote/data
      - /opt/dashql-bazel-cache/config/mtls:/opt/bazel-remote/mtls:ro
      - /opt/dashql-bazel-cache/config/bazel-remote.config.yaml:/opt/bazel-remote/config.yaml:ro
    command: ["--config_file=/opt/bazel-remote/config.yaml"]
