[package]
name = "dashql-compute"
version = "0.0.2-dev.17"
description = "Arrow-backed computations for DashQL"
edition = "2021"
rust-version = "1.70"
workspace = "../../"
publish = false

[lib]
crate-type = ["cdylib"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg getrandom_backend="wasm_js"']

[dependencies]
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.54"
console_error_panic_hook = "0.1.7"

log = "0.4.28"
chrono = { version = "0.4.42", features = ["wasmbind"] }
anyhow = "1.0.100"

getrandom_2 = { package = "getrandom", version = "0.2", features = ["js"] }
getrandom_3 = { package = "getrandom", version = "0.3.4", features = ["wasm_js"] }

prost = "0.13.3"

tokio = { version = "1.47.1", features = ["macros", "rt", "sync"] }
arrow = { version = "55.2.0", default-features = false, features = ["ipc"] }

datafusion-common = { version = "48.0.1", default-features = false }
datafusion-expr = { version = "48.0.1", default-features = false }
datafusion-execution = { version = "48.0.1", default-features = false }
datafusion-datasource = { version = "48.0.1", default-features = false }
datafusion-functions = { version = "48.0.1", default-features = false }
datafusion-functions-aggregate = { version = "48.0.1", default-features = false }
datafusion-functions-nested = { version = "48.0.1", default-features = false }
datafusion-functions-window = { version = "48.0.1", default-features = false }
datafusion-physical-expr = { version = "48.0.1", default-features = false }
datafusion-physical-plan = { version = "48.0.1", default-features = false }

[dependencies.uuid]
version = "1.18.1"
features = ["v5", "rng-getrandom"]

[dependencies.web-sys]
version = "0.3.81"
features = [
  'console',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.54"
pretty_assertions = "1.4.1"
indoc = "2.0.7"

[build-dependencies]
anyhow = "1.0.100"
regex = "1.12.2"
prost-build = "0.13.3"

[profile.release]
strip = true
lto = true
opt-level = "s"
