include "dashql/parsed_script.fbs";

namespace dashql.buffers.execution;

enum ScriptCompilationStatementKind: uint8 {
    QUERY,
    VISUALIZE,
}

enum CompiledScriptStatementKind: uint8 {
    COMMAND,
    OUTPUT,
    VISUALIZE,
}

enum ScriptCompilationErrorCode: uint8 {
    SCANNER_ERROR,
    PARSER_ERROR,
    EMPTY_SCRIPT,
    LAST_STATEMENT_NOT_EXECUTABLE,
    EXTENSIONS_DISABLED,
    VISUALIZATION_METADATA_UNAVAILABLE,
    FORMAT_ERROR,
    OUTPUT_STATEMENT_NOT_LAST,
}

table ScriptCompilationError {
    code: ScriptCompilationErrorCode;
    statement_id: uint32 = 4294967295;
    ast_node_id: uint32 = 4294967295;
    text_span: parser.TextSpan;
    message: string;
}

table CompiledVisualization {
    renderer: string;
    vegalite_spec: string;
    umap_spec: string;
}

table CompiledScriptStatement {
    statement_id: uint32 = 4294967295;
    statement_type: parser.StatementType = NONE;
    kind: CompiledScriptStatementKind = COMMAND;
    sql: string;
    visualization: CompiledVisualization;
}

table ScriptCompilationResult {
    kind: ScriptCompilationStatementKind = QUERY;
    terminal_statement_id: uint32 = 4294967295;
    sql: string;
    visualization: CompiledVisualization;
    errors: [ScriptCompilationError];
    statements: [CompiledScriptStatement];
}
