// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
#define FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_

#include "flatbuffers/flatbuffers.h"


namespace dashql {
namespace proto {
namespace syntax_sql {

enum class CombineModifier : uint8_t {
  NONE = 0,
  ALL = 1,
  DISTINCT = 2,
  MIN = NONE,
  MAX = DISTINCT
};

inline const CombineModifier (&EnumValuesCombineModifier())[3] {
  static const CombineModifier values[] = {
    CombineModifier::NONE,
    CombineModifier::ALL,
    CombineModifier::DISTINCT
  };
  return values;
}

inline const char * const *EnumNamesCombineModifier() {
  static const char * const names[4] = {
    "NONE",
    "ALL",
    "DISTINCT",
    nullptr
  };
  return names;
}

inline const char *EnumNameCombineModifier(CombineModifier e) {
  if (flatbuffers::IsOutRange(e, CombineModifier::NONE, CombineModifier::DISTINCT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCombineModifier()[index];
}

enum class CombineOperation : uint8_t {
  NONE = 0,
  INTERSECT = 1,
  UNION = 2,
  EXCEPT = 3,
  MIN = NONE,
  MAX = EXCEPT
};

inline const CombineOperation (&EnumValuesCombineOperation())[4] {
  static const CombineOperation values[] = {
    CombineOperation::NONE,
    CombineOperation::INTERSECT,
    CombineOperation::UNION,
    CombineOperation::EXCEPT
  };
  return values;
}

inline const char * const *EnumNamesCombineOperation() {
  static const char * const names[5] = {
    "NONE",
    "INTERSECT",
    "UNION",
    "EXCEPT",
    nullptr
  };
  return names;
}

inline const char *EnumNameCombineOperation(CombineOperation e) {
  if (flatbuffers::IsOutRange(e, CombineOperation::NONE, CombineOperation::EXCEPT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCombineOperation()[index];
}

enum class AConstType : uint8_t {
  INTEGER = 0,
  FLOAT = 1,
  STRING = 2,
  BITSTRING = 3,
  NULL_ = 4,
  MIN = INTEGER,
  MAX = NULL_
};

inline const AConstType (&EnumValuesAConstType())[5] {
  static const AConstType values[] = {
    AConstType::INTEGER,
    AConstType::FLOAT,
    AConstType::STRING,
    AConstType::BITSTRING,
    AConstType::NULL_
  };
  return values;
}

inline const char * const *EnumNamesAConstType() {
  static const char * const names[6] = {
    "INTEGER",
    "FLOAT",
    "STRING",
    "BITSTRING",
    "NULL_",
    nullptr
  };
  return names;
}

inline const char *EnumNameAConstType(AConstType e) {
  if (flatbuffers::IsOutRange(e, AConstType::INTEGER, AConstType::NULL_)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAConstType()[index];
}

enum class AExprKind : uint8_t {
  AEXPR_OP = 0,
  AEXPR_OP_ANY = 1,
  AEXPR_OP_ALL = 2,
  AEXPR_DISTINCT = 3,
  AEXPR_NOT_DISTINCT = 4,
  AEXPR_NULLIF = 5,
  AEXPR_OF = 6,
  AEXPR_IN = 7,
  AEXPR_LIKE = 8,
  AEXPR_ILIKE = 9,
  AEXPR_GLOB = 10,
  AEXPR_SIMILAR = 11,
  AEXPR_BETWEEN = 12,
  AEXPR_NOT_BETWEEN = 13,
  AEXPR_BETWEEN_SYM = 14,
  AEXPR_NOT_BETWEEN_SYM = 15,
  AEXPR_PAREN = 16,
  MIN = AEXPR_OP,
  MAX = AEXPR_PAREN
};

inline const AExprKind (&EnumValuesAExprKind())[17] {
  static const AExprKind values[] = {
    AExprKind::AEXPR_OP,
    AExprKind::AEXPR_OP_ANY,
    AExprKind::AEXPR_OP_ALL,
    AExprKind::AEXPR_DISTINCT,
    AExprKind::AEXPR_NOT_DISTINCT,
    AExprKind::AEXPR_NULLIF,
    AExprKind::AEXPR_OF,
    AExprKind::AEXPR_IN,
    AExprKind::AEXPR_LIKE,
    AExprKind::AEXPR_ILIKE,
    AExprKind::AEXPR_GLOB,
    AExprKind::AEXPR_SIMILAR,
    AExprKind::AEXPR_BETWEEN,
    AExprKind::AEXPR_NOT_BETWEEN,
    AExprKind::AEXPR_BETWEEN_SYM,
    AExprKind::AEXPR_NOT_BETWEEN_SYM,
    AExprKind::AEXPR_PAREN
  };
  return values;
}

inline const char * const *EnumNamesAExprKind() {
  static const char * const names[18] = {
    "AEXPR_OP",
    "AEXPR_OP_ANY",
    "AEXPR_OP_ALL",
    "AEXPR_DISTINCT",
    "AEXPR_NOT_DISTINCT",
    "AEXPR_NULLIF",
    "AEXPR_OF",
    "AEXPR_IN",
    "AEXPR_LIKE",
    "AEXPR_ILIKE",
    "AEXPR_GLOB",
    "AEXPR_SIMILAR",
    "AEXPR_BETWEEN",
    "AEXPR_NOT_BETWEEN",
    "AEXPR_BETWEEN_SYM",
    "AEXPR_NOT_BETWEEN_SYM",
    "AEXPR_PAREN",
    nullptr
  };
  return names;
}

inline const char *EnumNameAExprKind(AExprKind e) {
  if (flatbuffers::IsOutRange(e, AExprKind::AEXPR_OP, AExprKind::AEXPR_PAREN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAExprKind()[index];
}

enum class TempType : uint8_t {
  TEMP_DEFAULT = 0,
  TEMP_GLOBAL = 1,
  TEMP_LOCAL = 2,
  TEMP_UNLOGGED = 3,
  MIN = TEMP_DEFAULT,
  MAX = TEMP_UNLOGGED
};

inline const TempType (&EnumValuesTempType())[4] {
  static const TempType values[] = {
    TempType::TEMP_DEFAULT,
    TempType::TEMP_GLOBAL,
    TempType::TEMP_LOCAL,
    TempType::TEMP_UNLOGGED
  };
  return values;
}

inline const char * const *EnumNamesTempType() {
  static const char * const names[5] = {
    "TEMP_DEFAULT",
    "TEMP_GLOBAL",
    "TEMP_LOCAL",
    "TEMP_UNLOGGED",
    nullptr
  };
  return names;
}

inline const char *EnumNameTempType(TempType e) {
  if (flatbuffers::IsOutRange(e, TempType::TEMP_DEFAULT, TempType::TEMP_UNLOGGED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTempType()[index];
}

enum class WindowBoundMode : uint8_t {
  NONE = 0,
  UNBOUNDED = 1,
  CURRENT_ROW = 2,
  VALUE = 3,
  MIN = NONE,
  MAX = VALUE
};

inline const WindowBoundMode (&EnumValuesWindowBoundMode())[4] {
  static const WindowBoundMode values[] = {
    WindowBoundMode::NONE,
    WindowBoundMode::UNBOUNDED,
    WindowBoundMode::CURRENT_ROW,
    WindowBoundMode::VALUE
  };
  return values;
}

inline const char * const *EnumNamesWindowBoundMode() {
  static const char * const names[5] = {
    "NONE",
    "UNBOUNDED",
    "CURRENT_ROW",
    "VALUE",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowBoundMode(WindowBoundMode e) {
  if (flatbuffers::IsOutRange(e, WindowBoundMode::NONE, WindowBoundMode::VALUE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowBoundMode()[index];
}

enum class WindowBoundDirection : uint8_t {
  NONE = 0,
  PRECEDING = 1,
  FOLLOWING = 2,
  MIN = NONE,
  MAX = FOLLOWING
};

inline const WindowBoundDirection (&EnumValuesWindowBoundDirection())[3] {
  static const WindowBoundDirection values[] = {
    WindowBoundDirection::NONE,
    WindowBoundDirection::PRECEDING,
    WindowBoundDirection::FOLLOWING
  };
  return values;
}

inline const char * const *EnumNamesWindowBoundDirection() {
  static const char * const names[4] = {
    "NONE",
    "PRECEDING",
    "FOLLOWING",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowBoundDirection(WindowBoundDirection e) {
  if (flatbuffers::IsOutRange(e, WindowBoundDirection::NONE, WindowBoundDirection::FOLLOWING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowBoundDirection()[index];
}

enum class WindowRangeMode : uint8_t {
  NONE = 0,
  RANGE = 1,
  ROWS = 2,
  GROUPS = 3,
  MIN = NONE,
  MAX = GROUPS
};

inline const WindowRangeMode (&EnumValuesWindowRangeMode())[4] {
  static const WindowRangeMode values[] = {
    WindowRangeMode::NONE,
    WindowRangeMode::RANGE,
    WindowRangeMode::ROWS,
    WindowRangeMode::GROUPS
  };
  return values;
}

inline const char * const *EnumNamesWindowRangeMode() {
  static const char * const names[5] = {
    "NONE",
    "RANGE",
    "ROWS",
    "GROUPS",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowRangeMode(WindowRangeMode e) {
  if (flatbuffers::IsOutRange(e, WindowRangeMode::NONE, WindowRangeMode::GROUPS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowRangeMode()[index];
}

enum class WindowExclusionMode : uint8_t {
  NONE = 0,
  CURRENT_ROW = 1,
  GROUP = 2,
  TIES = 3,
  MIN = NONE,
  MAX = TIES
};

inline const WindowExclusionMode (&EnumValuesWindowExclusionMode())[4] {
  static const WindowExclusionMode values[] = {
    WindowExclusionMode::NONE,
    WindowExclusionMode::CURRENT_ROW,
    WindowExclusionMode::GROUP,
    WindowExclusionMode::TIES
  };
  return values;
}

inline const char * const *EnumNamesWindowExclusionMode() {
  static const char * const names[5] = {
    "NONE",
    "CURRENT_ROW",
    "GROUP",
    "TIES",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowExclusionMode(WindowExclusionMode e) {
  if (flatbuffers::IsOutRange(e, WindowExclusionMode::NONE, WindowExclusionMode::TIES)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowExclusionMode()[index];
}

inline const flatbuffers::TypeTable *CombineModifierTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::CombineModifierTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "ALL",
    "DISTINCT"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *CombineOperationTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::CombineOperationTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "INTERSECT",
    "UNION",
    "EXCEPT"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AConstTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::AConstTypeTypeTable
  };
  static const char * const names[] = {
    "INTEGER",
    "FLOAT",
    "STRING",
    "BITSTRING",
    "NULL_"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AExprKindTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::AExprKindTypeTable
  };
  static const char * const names[] = {
    "AEXPR_OP",
    "AEXPR_OP_ANY",
    "AEXPR_OP_ALL",
    "AEXPR_DISTINCT",
    "AEXPR_NOT_DISTINCT",
    "AEXPR_NULLIF",
    "AEXPR_OF",
    "AEXPR_IN",
    "AEXPR_LIKE",
    "AEXPR_ILIKE",
    "AEXPR_GLOB",
    "AEXPR_SIMILAR",
    "AEXPR_BETWEEN",
    "AEXPR_NOT_BETWEEN",
    "AEXPR_BETWEEN_SYM",
    "AEXPR_NOT_BETWEEN_SYM",
    "AEXPR_PAREN"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 17, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *TempTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::TempTypeTypeTable
  };
  static const char * const names[] = {
    "TEMP_DEFAULT",
    "TEMP_GLOBAL",
    "TEMP_LOCAL",
    "TEMP_UNLOGGED"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowBoundModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowBoundModeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "UNBOUNDED",
    "CURRENT_ROW",
    "VALUE"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowBoundDirectionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowBoundDirectionTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "PRECEDING",
    "FOLLOWING"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowRangeModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowRangeModeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "RANGE",
    "ROWS",
    "GROUPS"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowExclusionModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowExclusionModeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "CURRENT_ROW",
    "GROUP",
    "TIES"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace syntax_sql
}  // namespace proto
}  // namespace dashql

#endif  // FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
