// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
#define FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_

#include "flatbuffers/flatbuffers.h"


#endif  // FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
