// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
#define FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_

#include "flatbuffers/flatbuffers.h"


namespace dashql {
namespace proto {
namespace syntax_sql {

enum class ExpressionFunction : uint8_t {
  NEGATE = 0,
  PLUS = 1,
  MINUS = 2,
  MULTIPLY = 3,
  DIVIDE = 4,
  MODULUS = 5,
  XOR = 6,
  COMPARE_LESS_THAN = 7,
  COMPARE_LESS_EQUAL = 8,
  COMPARE_GREATER_THAN = 9,
  COMPARE_GREATER_EQUAL = 10,
  COMPARE_EQUAL = 11,
  COMPARE_NOT_EQUAL = 12,
  MIN = NEGATE,
  MAX = COMPARE_NOT_EQUAL
};

inline const ExpressionFunction (&EnumValuesExpressionFunction())[13] {
  static const ExpressionFunction values[] = {
    ExpressionFunction::NEGATE,
    ExpressionFunction::PLUS,
    ExpressionFunction::MINUS,
    ExpressionFunction::MULTIPLY,
    ExpressionFunction::DIVIDE,
    ExpressionFunction::MODULUS,
    ExpressionFunction::XOR,
    ExpressionFunction::COMPARE_LESS_THAN,
    ExpressionFunction::COMPARE_LESS_EQUAL,
    ExpressionFunction::COMPARE_GREATER_THAN,
    ExpressionFunction::COMPARE_GREATER_EQUAL,
    ExpressionFunction::COMPARE_EQUAL,
    ExpressionFunction::COMPARE_NOT_EQUAL
  };
  return values;
}

inline const char * const *EnumNamesExpressionFunction() {
  static const char * const names[14] = {
    "NEGATE",
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "MODULUS",
    "XOR",
    "COMPARE_LESS_THAN",
    "COMPARE_LESS_EQUAL",
    "COMPARE_GREATER_THAN",
    "COMPARE_GREATER_EQUAL",
    "COMPARE_EQUAL",
    "COMPARE_NOT_EQUAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameExpressionFunction(ExpressionFunction e) {
  if (flatbuffers::IsOutRange(e, ExpressionFunction::NEGATE, ExpressionFunction::COMPARE_NOT_EQUAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExpressionFunction()[index];
}

enum class CombineModifier : uint8_t {
  NONE = 0,
  ALL = 1,
  DISTINCT = 2,
  MIN = NONE,
  MAX = DISTINCT
};

inline const CombineModifier (&EnumValuesCombineModifier())[3] {
  static const CombineModifier values[] = {
    CombineModifier::NONE,
    CombineModifier::ALL,
    CombineModifier::DISTINCT
  };
  return values;
}

inline const char * const *EnumNamesCombineModifier() {
  static const char * const names[4] = {
    "NONE",
    "ALL",
    "DISTINCT",
    nullptr
  };
  return names;
}

inline const char *EnumNameCombineModifier(CombineModifier e) {
  if (flatbuffers::IsOutRange(e, CombineModifier::NONE, CombineModifier::DISTINCT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCombineModifier()[index];
}

enum class CombineOperation : uint8_t {
  NONE = 0,
  INTERSECT = 1,
  UNION = 2,
  EXCEPT = 3,
  MIN = NONE,
  MAX = EXCEPT
};

inline const CombineOperation (&EnumValuesCombineOperation())[4] {
  static const CombineOperation values[] = {
    CombineOperation::NONE,
    CombineOperation::INTERSECT,
    CombineOperation::UNION,
    CombineOperation::EXCEPT
  };
  return values;
}

inline const char * const *EnumNamesCombineOperation() {
  static const char * const names[5] = {
    "NONE",
    "INTERSECT",
    "UNION",
    "EXCEPT",
    nullptr
  };
  return names;
}

inline const char *EnumNameCombineOperation(CombineOperation e) {
  if (flatbuffers::IsOutRange(e, CombineOperation::NONE, CombineOperation::EXCEPT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCombineOperation()[index];
}

enum class AConstType : uint8_t {
  INTEGER = 0,
  FLOAT = 1,
  STRING = 2,
  BITSTRING = 3,
  NULL_ = 4,
  MIN = INTEGER,
  MAX = NULL_
};

inline const AConstType (&EnumValuesAConstType())[5] {
  static const AConstType values[] = {
    AConstType::INTEGER,
    AConstType::FLOAT,
    AConstType::STRING,
    AConstType::BITSTRING,
    AConstType::NULL_
  };
  return values;
}

inline const char * const *EnumNamesAConstType() {
  static const char * const names[6] = {
    "INTEGER",
    "FLOAT",
    "STRING",
    "BITSTRING",
    "NULL_",
    nullptr
  };
  return names;
}

inline const char *EnumNameAConstType(AConstType e) {
  if (flatbuffers::IsOutRange(e, AConstType::INTEGER, AConstType::NULL_)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAConstType()[index];
}

enum class TempType : uint8_t {
  DEFAULT = 0,
  GLOBAL = 1,
  LOCAL = 2,
  UNLOGGED = 3,
  MIN = DEFAULT,
  MAX = UNLOGGED
};

inline const TempType (&EnumValuesTempType())[4] {
  static const TempType values[] = {
    TempType::DEFAULT,
    TempType::GLOBAL,
    TempType::LOCAL,
    TempType::UNLOGGED
  };
  return values;
}

inline const char * const *EnumNamesTempType() {
  static const char * const names[5] = {
    "DEFAULT",
    "GLOBAL",
    "LOCAL",
    "UNLOGGED",
    nullptr
  };
  return names;
}

inline const char *EnumNameTempType(TempType e) {
  if (flatbuffers::IsOutRange(e, TempType::DEFAULT, TempType::UNLOGGED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTempType()[index];
}

enum class WindowBoundMode : uint8_t {
  UNBOUNDED = 0,
  CURRENT_ROW = 1,
  VALUE = 2,
  MIN = UNBOUNDED,
  MAX = VALUE
};

inline const WindowBoundMode (&EnumValuesWindowBoundMode())[3] {
  static const WindowBoundMode values[] = {
    WindowBoundMode::UNBOUNDED,
    WindowBoundMode::CURRENT_ROW,
    WindowBoundMode::VALUE
  };
  return values;
}

inline const char * const *EnumNamesWindowBoundMode() {
  static const char * const names[4] = {
    "UNBOUNDED",
    "CURRENT_ROW",
    "VALUE",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowBoundMode(WindowBoundMode e) {
  if (flatbuffers::IsOutRange(e, WindowBoundMode::UNBOUNDED, WindowBoundMode::VALUE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowBoundMode()[index];
}

enum class WindowBoundDirection : uint8_t {
  PRECEDING = 0,
  FOLLOWING = 1,
  MIN = PRECEDING,
  MAX = FOLLOWING
};

inline const WindowBoundDirection (&EnumValuesWindowBoundDirection())[2] {
  static const WindowBoundDirection values[] = {
    WindowBoundDirection::PRECEDING,
    WindowBoundDirection::FOLLOWING
  };
  return values;
}

inline const char * const *EnumNamesWindowBoundDirection() {
  static const char * const names[3] = {
    "PRECEDING",
    "FOLLOWING",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowBoundDirection(WindowBoundDirection e) {
  if (flatbuffers::IsOutRange(e, WindowBoundDirection::PRECEDING, WindowBoundDirection::FOLLOWING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowBoundDirection()[index];
}

enum class WindowRangeMode : uint8_t {
  RANGE = 0,
  ROWS = 1,
  GROUPS = 2,
  MIN = RANGE,
  MAX = GROUPS
};

inline const WindowRangeMode (&EnumValuesWindowRangeMode())[3] {
  static const WindowRangeMode values[] = {
    WindowRangeMode::RANGE,
    WindowRangeMode::ROWS,
    WindowRangeMode::GROUPS
  };
  return values;
}

inline const char * const *EnumNamesWindowRangeMode() {
  static const char * const names[4] = {
    "RANGE",
    "ROWS",
    "GROUPS",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowRangeMode(WindowRangeMode e) {
  if (flatbuffers::IsOutRange(e, WindowRangeMode::RANGE, WindowRangeMode::GROUPS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowRangeMode()[index];
}

enum class WindowExclusionMode : uint8_t {
  CURRENT_ROW = 0,
  GROUP = 1,
  TIES = 2,
  MIN = CURRENT_ROW,
  MAX = TIES
};

inline const WindowExclusionMode (&EnumValuesWindowExclusionMode())[3] {
  static const WindowExclusionMode values[] = {
    WindowExclusionMode::CURRENT_ROW,
    WindowExclusionMode::GROUP,
    WindowExclusionMode::TIES
  };
  return values;
}

inline const char * const *EnumNamesWindowExclusionMode() {
  static const char * const names[4] = {
    "CURRENT_ROW",
    "GROUP",
    "TIES",
    nullptr
  };
  return names;
}

inline const char *EnumNameWindowExclusionMode(WindowExclusionMode e) {
  if (flatbuffers::IsOutRange(e, WindowExclusionMode::CURRENT_ROW, WindowExclusionMode::TIES)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWindowExclusionMode()[index];
}

enum class OrderDirection : uint8_t {
  ASCENDING = 0,
  DESCENDING = 1,
  MIN = ASCENDING,
  MAX = DESCENDING
};

inline const OrderDirection (&EnumValuesOrderDirection())[2] {
  static const OrderDirection values[] = {
    OrderDirection::ASCENDING,
    OrderDirection::DESCENDING
  };
  return values;
}

inline const char * const *EnumNamesOrderDirection() {
  static const char * const names[3] = {
    "ASCENDING",
    "DESCENDING",
    nullptr
  };
  return names;
}

inline const char *EnumNameOrderDirection(OrderDirection e) {
  if (flatbuffers::IsOutRange(e, OrderDirection::ASCENDING, OrderDirection::DESCENDING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOrderDirection()[index];
}

enum class OrderNullRule : uint8_t {
  NULLS_FIRST = 0,
  NULLS_LAST = 1,
  MIN = NULLS_FIRST,
  MAX = NULLS_LAST
};

inline const OrderNullRule (&EnumValuesOrderNullRule())[2] {
  static const OrderNullRule values[] = {
    OrderNullRule::NULLS_FIRST,
    OrderNullRule::NULLS_LAST
  };
  return values;
}

inline const char * const *EnumNamesOrderNullRule() {
  static const char * const names[3] = {
    "NULLS_FIRST",
    "NULLS_LAST",
    nullptr
  };
  return names;
}

inline const char *EnumNameOrderNullRule(OrderNullRule e) {
  if (flatbuffers::IsOutRange(e, OrderNullRule::NULLS_FIRST, OrderNullRule::NULLS_LAST)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOrderNullRule()[index];
}

enum class NumericTypeTag : uint8_t {
  INT2 = 0,
  INT4 = 1,
  INT8 = 2,
  FLOAT4 = 3,
  FLOAT8 = 4,
  NUMERIC = 5,
  BOOL = 6,
  MIN = INT2,
  MAX = BOOL
};

inline const NumericTypeTag (&EnumValuesNumericTypeTag())[7] {
  static const NumericTypeTag values[] = {
    NumericTypeTag::INT2,
    NumericTypeTag::INT4,
    NumericTypeTag::INT8,
    NumericTypeTag::FLOAT4,
    NumericTypeTag::FLOAT8,
    NumericTypeTag::NUMERIC,
    NumericTypeTag::BOOL
  };
  return values;
}

inline const char * const *EnumNamesNumericTypeTag() {
  static const char * const names[8] = {
    "INT2",
    "INT4",
    "INT8",
    "FLOAT4",
    "FLOAT8",
    "NUMERIC",
    "BOOL",
    nullptr
  };
  return names;
}

inline const char *EnumNameNumericTypeTag(NumericTypeTag e) {
  if (flatbuffers::IsOutRange(e, NumericTypeTag::INT2, NumericTypeTag::BOOL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNumericTypeTag()[index];
}

inline const flatbuffers::TypeTable *ExpressionFunctionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::ExpressionFunctionTypeTable
  };
  static const char * const names[] = {
    "NEGATE",
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "MODULUS",
    "XOR",
    "COMPARE_LESS_THAN",
    "COMPARE_LESS_EQUAL",
    "COMPARE_GREATER_THAN",
    "COMPARE_GREATER_EQUAL",
    "COMPARE_EQUAL",
    "COMPARE_NOT_EQUAL"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 13, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *CombineModifierTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::CombineModifierTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "ALL",
    "DISTINCT"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *CombineOperationTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::CombineOperationTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "INTERSECT",
    "UNION",
    "EXCEPT"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AConstTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::AConstTypeTypeTable
  };
  static const char * const names[] = {
    "INTEGER",
    "FLOAT",
    "STRING",
    "BITSTRING",
    "NULL_"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *TempTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::TempTypeTypeTable
  };
  static const char * const names[] = {
    "DEFAULT",
    "GLOBAL",
    "LOCAL",
    "UNLOGGED"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowBoundModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowBoundModeTypeTable
  };
  static const char * const names[] = {
    "UNBOUNDED",
    "CURRENT_ROW",
    "VALUE"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowBoundDirectionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowBoundDirectionTypeTable
  };
  static const char * const names[] = {
    "PRECEDING",
    "FOLLOWING"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowRangeModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowRangeModeTypeTable
  };
  static const char * const names[] = {
    "RANGE",
    "ROWS",
    "GROUPS"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *WindowExclusionModeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::WindowExclusionModeTypeTable
  };
  static const char * const names[] = {
    "CURRENT_ROW",
    "GROUP",
    "TIES"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *OrderDirectionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::OrderDirectionTypeTable
  };
  static const char * const names[] = {
    "ASCENDING",
    "DESCENDING"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *OrderNullRuleTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::OrderNullRuleTypeTable
  };
  static const char * const names[] = {
    "NULLS_FIRST",
    "NULLS_LAST"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *NumericTypeTagTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_sql::NumericTypeTagTypeTable
  };
  static const char * const names[] = {
    "INT2",
    "INT4",
    "INT8",
    "FLOAT4",
    "FLOAT8",
    "NUMERIC",
    "BOOL"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace syntax_sql
}  // namespace proto
}  // namespace dashql

#endif  // FLATBUFFERS_GENERATED_SYNTAXSQL_DASHQL_PROTO_SYNTAX_SQL_H_
