// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNTAX_DASHQL_PROTO_SYNTAX_H_
#define FLATBUFFERS_GENERATED_SYNTAX_DASHQL_PROTO_SYNTAX_H_

#include "flatbuffers/flatbuffers.h"

namespace dashql {
namespace proto {
namespace syntax {

struct Location;

struct Span;

struct Value;

struct Array;

struct Attribute;

struct Object;

struct Document;
struct DocumentBuilder;
struct DocumentT;

struct Error;
struct ErrorBuilder;
struct ErrorT;

struct Module;
struct ModuleBuilder;
struct ModuleT;

bool operator==(const Location &lhs, const Location &rhs);
bool operator!=(const Location &lhs, const Location &rhs);
bool operator==(const Span &lhs, const Span &rhs);
bool operator!=(const Span &lhs, const Span &rhs);
bool operator==(const Value &lhs, const Value &rhs);
bool operator!=(const Value &lhs, const Value &rhs);
bool operator==(const Array &lhs, const Array &rhs);
bool operator!=(const Array &lhs, const Array &rhs);
bool operator==(const Attribute &lhs, const Attribute &rhs);
bool operator!=(const Attribute &lhs, const Attribute &rhs);
bool operator==(const Object &lhs, const Object &rhs);
bool operator!=(const Object &lhs, const Object &rhs);
bool operator==(const DocumentT &lhs, const DocumentT &rhs);
bool operator!=(const DocumentT &lhs, const DocumentT &rhs);
bool operator==(const ErrorT &lhs, const ErrorT &rhs);
bool operator!=(const ErrorT &lhs, const ErrorT &rhs);
bool operator==(const ModuleT &lhs, const ModuleT &rhs);
bool operator!=(const ModuleT &lhs, const ModuleT &rhs);

inline const flatbuffers::TypeTable *LocationTypeTable();

inline const flatbuffers::TypeTable *SpanTypeTable();

inline const flatbuffers::TypeTable *ValueTypeTable();

inline const flatbuffers::TypeTable *ArrayTypeTable();

inline const flatbuffers::TypeTable *AttributeTypeTable();

inline const flatbuffers::TypeTable *ObjectTypeTable();

inline const flatbuffers::TypeTable *DocumentTypeTable();

inline const flatbuffers::TypeTable *ErrorTypeTable();

inline const flatbuffers::TypeTable *ModuleTypeTable();

enum class ObjectType : uint8_t {
  NONE = 0,
  DASHQL_LOAD = 1,
  DASHQL_PARAMTER = 2,
  DASHQL_EXTRACT = 3,
  DASHQL_QUERY = 4,
  DASHQL_VIZ = 5,
  SQL_SELECT = 6,
  SQL_ACONST = 7,
  SQL_RESULT_TARGET = 8,
  MIN = NONE,
  MAX = SQL_RESULT_TARGET
};

inline const ObjectType (&EnumValuesObjectType())[9] {
  static const ObjectType values[] = {
    ObjectType::NONE,
    ObjectType::DASHQL_LOAD,
    ObjectType::DASHQL_PARAMTER,
    ObjectType::DASHQL_EXTRACT,
    ObjectType::DASHQL_QUERY,
    ObjectType::DASHQL_VIZ,
    ObjectType::SQL_SELECT,
    ObjectType::SQL_ACONST,
    ObjectType::SQL_RESULT_TARGET
  };
  return values;
}

inline const char * const *EnumNamesObjectType() {
  static const char * const names[10] = {
    "NONE",
    "DASHQL_LOAD",
    "DASHQL_PARAMTER",
    "DASHQL_EXTRACT",
    "DASHQL_QUERY",
    "DASHQL_VIZ",
    "SQL_SELECT",
    "SQL_ACONST",
    "SQL_RESULT_TARGET",
    nullptr
  };
  return names;
}

inline const char *EnumNameObjectType(ObjectType e) {
  if (flatbuffers::IsOutRange(e, ObjectType::NONE, ObjectType::SQL_RESULT_TARGET)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesObjectType()[index];
}

enum class AttributeKey : uint8_t {
  NONE = 0,
  DASHQL_PARAMETER_IDENTIFIER = 1,
  DASHQL_PARAMETER_ALIAS = 2,
  DASHQL_PARAMETER_TYPE = 3,
  DASHQL_LOAD_NAME = 4,
  DASHQL_FILE_LABEL = 5,
  DASHQL_HTTP_LOAD_NAME = 6,
  DASHQL_HTTP_LOAD_VERB = 7,
  DASHQL_HTTP_LOAD_URL = 8,
  DASHQL_HTTP_LOAD_HEADER = 9,
  DASHQL_EXTRACT_NAME = 10,
  DASHQL_EXTRACT_DATA = 11,
  DASHQL_EXTRACT_METHOD = 12,
  DASHQL_CSV_EXTRACT_ENCODING = 13,
  DASHQL_CSV_EXTRACT_HEADER = 14,
  DASHQL_CSV_EXTRACT_HEADER_COLUMNS = 15,
  DASHQL_CSV_EXTRACT_DELIMITER = 16,
  DASHQL_CSV_EXTRACT_QUOTE = 17,
  DASHQL_CSV_EXTRACT_DATE_FORMAT = 18,
  DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT = 19,
  DASHQL_QUERY_NAME = 20,
  DASHQL_QUERY_STATEMENT = 21,
  DASHQL_VIZ_TYPE = 22,
  DASHQL_VIZ_NAME = 23,
  DASHQL_VIZ_QUERY = 24,
  SQL_SELECT_TARGETS = 25,
  SQL_ACONST_TYPE = 26,
  SQL_ACONST_VALUE = 27,
  SQL_RESULT_TARGET_NAME = 28,
  SQL_RESULT_TARGET_VALUE = 29,
  MIN = NONE,
  MAX = SQL_RESULT_TARGET_VALUE
};

inline const AttributeKey (&EnumValuesAttributeKey())[30] {
  static const AttributeKey values[] = {
    AttributeKey::NONE,
    AttributeKey::DASHQL_PARAMETER_IDENTIFIER,
    AttributeKey::DASHQL_PARAMETER_ALIAS,
    AttributeKey::DASHQL_PARAMETER_TYPE,
    AttributeKey::DASHQL_LOAD_NAME,
    AttributeKey::DASHQL_FILE_LABEL,
    AttributeKey::DASHQL_HTTP_LOAD_NAME,
    AttributeKey::DASHQL_HTTP_LOAD_VERB,
    AttributeKey::DASHQL_HTTP_LOAD_URL,
    AttributeKey::DASHQL_HTTP_LOAD_HEADER,
    AttributeKey::DASHQL_EXTRACT_NAME,
    AttributeKey::DASHQL_EXTRACT_DATA,
    AttributeKey::DASHQL_EXTRACT_METHOD,
    AttributeKey::DASHQL_CSV_EXTRACT_ENCODING,
    AttributeKey::DASHQL_CSV_EXTRACT_HEADER,
    AttributeKey::DASHQL_CSV_EXTRACT_HEADER_COLUMNS,
    AttributeKey::DASHQL_CSV_EXTRACT_DELIMITER,
    AttributeKey::DASHQL_CSV_EXTRACT_QUOTE,
    AttributeKey::DASHQL_CSV_EXTRACT_DATE_FORMAT,
    AttributeKey::DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT,
    AttributeKey::DASHQL_QUERY_NAME,
    AttributeKey::DASHQL_QUERY_STATEMENT,
    AttributeKey::DASHQL_VIZ_TYPE,
    AttributeKey::DASHQL_VIZ_NAME,
    AttributeKey::DASHQL_VIZ_QUERY,
    AttributeKey::SQL_SELECT_TARGETS,
    AttributeKey::SQL_ACONST_TYPE,
    AttributeKey::SQL_ACONST_VALUE,
    AttributeKey::SQL_RESULT_TARGET_NAME,
    AttributeKey::SQL_RESULT_TARGET_VALUE
  };
  return values;
}

inline const char * const *EnumNamesAttributeKey() {
  static const char * const names[31] = {
    "NONE",
    "DASHQL_PARAMETER_IDENTIFIER",
    "DASHQL_PARAMETER_ALIAS",
    "DASHQL_PARAMETER_TYPE",
    "DASHQL_LOAD_NAME",
    "DASHQL_FILE_LABEL",
    "DASHQL_HTTP_LOAD_NAME",
    "DASHQL_HTTP_LOAD_VERB",
    "DASHQL_HTTP_LOAD_URL",
    "DASHQL_HTTP_LOAD_HEADER",
    "DASHQL_EXTRACT_NAME",
    "DASHQL_EXTRACT_DATA",
    "DASHQL_EXTRACT_METHOD",
    "DASHQL_CSV_EXTRACT_ENCODING",
    "DASHQL_CSV_EXTRACT_HEADER",
    "DASHQL_CSV_EXTRACT_HEADER_COLUMNS",
    "DASHQL_CSV_EXTRACT_DELIMITER",
    "DASHQL_CSV_EXTRACT_QUOTE",
    "DASHQL_CSV_EXTRACT_DATE_FORMAT",
    "DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT",
    "DASHQL_QUERY_NAME",
    "DASHQL_QUERY_STATEMENT",
    "DASHQL_VIZ_TYPE",
    "DASHQL_VIZ_NAME",
    "DASHQL_VIZ_QUERY",
    "SQL_SELECT_TARGETS",
    "SQL_ACONST_TYPE",
    "SQL_ACONST_VALUE",
    "SQL_RESULT_TARGET_NAME",
    "SQL_RESULT_TARGET_VALUE",
    nullptr
  };
  return names;
}

inline const char *EnumNameAttributeKey(AttributeKey e) {
  if (flatbuffers::IsOutRange(e, AttributeKey::NONE, AttributeKey::SQL_RESULT_TARGET_VALUE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAttributeKey()[index];
}

enum class ValueType : uint8_t {
  NONE = 0,
  I64 = 1,
  STRING = 2,
  OBJECT = 3,
  ARRAY = 4,
  MIN = NONE,
  MAX = ARRAY
};

inline const ValueType (&EnumValuesValueType())[5] {
  static const ValueType values[] = {
    ValueType::NONE,
    ValueType::I64,
    ValueType::STRING,
    ValueType::OBJECT,
    ValueType::ARRAY
  };
  return values;
}

inline const char * const *EnumNamesValueType() {
  static const char * const names[6] = {
    "NONE",
    "I64",
    "STRING",
    "OBJECT",
    "ARRAY",
    nullptr
  };
  return names;
}

inline const char *EnumNameValueType(ValueType e) {
  if (flatbuffers::IsOutRange(e, ValueType::NONE, ValueType::ARRAY)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValueType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Location FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t offset_;
  uint32_t length_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LocationTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Location";
  }
  Location()
      : offset_(0),
        length_(0) {
  }
  Location(uint32_t _offset, uint32_t _length)
      : offset_(flatbuffers::EndianScalar(_offset)),
        length_(flatbuffers::EndianScalar(_length)) {
  }
  uint32_t offset() const {
    return flatbuffers::EndianScalar(offset_);
  }
  uint32_t length() const {
    return flatbuffers::EndianScalar(length_);
  }
};
FLATBUFFERS_STRUCT_END(Location, 8);

inline bool operator==(const Location &lhs, const Location &rhs) {
  return
      (lhs.offset() == rhs.offset()) &&
      (lhs.length() == rhs.length());
}

inline bool operator!=(const Location &lhs, const Location &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Span FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t offset_;
  uint32_t length_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SpanTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Span";
  }
  Span()
      : offset_(0),
        length_(0) {
  }
  Span(uint32_t _offset, uint32_t _length)
      : offset_(flatbuffers::EndianScalar(_offset)),
        length_(flatbuffers::EndianScalar(_length)) {
  }
  uint32_t offset() const {
    return flatbuffers::EndianScalar(offset_);
  }
  uint32_t length() const {
    return flatbuffers::EndianScalar(length_);
  }
};
FLATBUFFERS_STRUCT_END(Span, 8);

inline bool operator==(const Span &lhs, const Span &rhs) {
  return
      (lhs.offset() == rhs.offset()) &&
      (lhs.length() == rhs.length());
}

inline bool operator!=(const Span &lhs, const Span &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Value FLATBUFFERS_FINAL_CLASS {
 private:
  dashql::proto::syntax::Location location_;
  uint8_t type_;
  int8_t padding0__;  int16_t padding1__;  int32_t padding2__;
  int64_t value_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ValueTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Value";
  }
  Value()
      : location_(),
        type_(0),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        value_(0) {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
  }
  Value(const dashql::proto::syntax::Location &_location, dashql::proto::syntax::ValueType _type, int64_t _value)
      : location_(_location),
        type_(flatbuffers::EndianScalar(static_cast<uint8_t>(_type))),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        value_(flatbuffers::EndianScalar(_value)) {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
  }
  const dashql::proto::syntax::Location &location() const {
    return location_;
  }
  dashql::proto::syntax::ValueType type() const {
    return static_cast<dashql::proto::syntax::ValueType>(flatbuffers::EndianScalar(type_));
  }
  int64_t value() const {
    return flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Value, 24);

inline bool operator==(const Value &lhs, const Value &rhs) {
  return
      (lhs.location() == rhs.location()) &&
      (lhs.type() == rhs.type()) &&
      (lhs.value() == rhs.value());
}

inline bool operator!=(const Value &lhs, const Value &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Array FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t type_;
  int8_t padding0__;  int16_t padding1__;
  uint32_t offset_;
  uint32_t length_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ArrayTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Array";
  }
  Array()
      : type_(0),
        padding0__(0),
        padding1__(0),
        offset_(0),
        length_(0) {
    (void)padding0__;
    (void)padding1__;
  }
  Array(dashql::proto::syntax::ValueType _type, uint32_t _offset, uint32_t _length)
      : type_(flatbuffers::EndianScalar(static_cast<uint8_t>(_type))),
        padding0__(0),
        padding1__(0),
        offset_(flatbuffers::EndianScalar(_offset)),
        length_(flatbuffers::EndianScalar(_length)) {
    (void)padding0__;
    (void)padding1__;
  }
  dashql::proto::syntax::ValueType type() const {
    return static_cast<dashql::proto::syntax::ValueType>(flatbuffers::EndianScalar(type_));
  }
  uint32_t offset() const {
    return flatbuffers::EndianScalar(offset_);
  }
  uint32_t length() const {
    return flatbuffers::EndianScalar(length_);
  }
};
FLATBUFFERS_STRUCT_END(Array, 12);

inline bool operator==(const Array &lhs, const Array &rhs) {
  return
      (lhs.type() == rhs.type()) &&
      (lhs.offset() == rhs.offset()) &&
      (lhs.length() == rhs.length());
}

inline bool operator!=(const Array &lhs, const Array &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Attribute FLATBUFFERS_FINAL_CLASS {
 private:
  dashql::proto::syntax::Location location_;
  uint8_t key_;
  int8_t padding0__;  int16_t padding1__;  int32_t padding2__;
  dashql::proto::syntax::Value value_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AttributeTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Attribute";
  }
  Attribute()
      : location_(),
        key_(0),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        value_() {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
  }
  Attribute(const dashql::proto::syntax::Location &_location, dashql::proto::syntax::AttributeKey _key, const dashql::proto::syntax::Value &_value)
      : location_(_location),
        key_(flatbuffers::EndianScalar(static_cast<uint8_t>(_key))),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        value_(_value) {
    (void)padding0__;
    (void)padding1__;
    (void)padding2__;
  }
  const dashql::proto::syntax::Location &location() const {
    return location_;
  }
  dashql::proto::syntax::AttributeKey key() const {
    return static_cast<dashql::proto::syntax::AttributeKey>(flatbuffers::EndianScalar(key_));
  }
  const dashql::proto::syntax::Value &value() const {
    return value_;
  }
};
FLATBUFFERS_STRUCT_END(Attribute, 40);

inline bool operator==(const Attribute &lhs, const Attribute &rhs) {
  return
      (lhs.location() == rhs.location()) &&
      (lhs.key() == rhs.key()) &&
      (lhs.value() == rhs.value());
}

inline bool operator!=(const Attribute &lhs, const Attribute &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Object FLATBUFFERS_FINAL_CLASS {
 private:
  dashql::proto::syntax::Location location_;
  uint8_t type_;
  int8_t padding0__;  int16_t padding1__;
  dashql::proto::syntax::Span attributes_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ObjectTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Object";
  }
  Object()
      : location_(),
        type_(0),
        padding0__(0),
        padding1__(0),
        attributes_() {
    (void)padding0__;
    (void)padding1__;
  }
  Object(const dashql::proto::syntax::Location &_location, dashql::proto::syntax::ObjectType _type, const dashql::proto::syntax::Span &_attributes)
      : location_(_location),
        type_(flatbuffers::EndianScalar(static_cast<uint8_t>(_type))),
        padding0__(0),
        padding1__(0),
        attributes_(_attributes) {
    (void)padding0__;
    (void)padding1__;
  }
  const dashql::proto::syntax::Location &location() const {
    return location_;
  }
  dashql::proto::syntax::ObjectType type() const {
    return static_cast<dashql::proto::syntax::ObjectType>(flatbuffers::EndianScalar(type_));
  }
  const dashql::proto::syntax::Span &attributes() const {
    return attributes_;
  }
};
FLATBUFFERS_STRUCT_END(Object, 20);

inline bool operator==(const Object &lhs, const Object &rhs) {
  return
      (lhs.location() == rhs.location()) &&
      (lhs.type() == rhs.type()) &&
      (lhs.attributes() == rhs.attributes());
}

inline bool operator!=(const Object &lhs, const Object &rhs) {
    return !(lhs == rhs);
}


struct DocumentT : public flatbuffers::NativeTable {
  typedef Document TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.DocumentT";
  }
  std::vector<uint32_t> entries;
  std::vector<dashql::proto::syntax::Object> objects;
  std::vector<dashql::proto::syntax::Attribute> attributes;
  std::vector<dashql::proto::syntax::Array> arrays;
  std::vector<int32_t> values_i64;
  std::vector<dashql::proto::syntax::Location> values_string;
  DocumentT() {
  }
};

inline bool operator==(const DocumentT &lhs, const DocumentT &rhs) {
  return
      (lhs.entries == rhs.entries) &&
      (lhs.objects == rhs.objects) &&
      (lhs.attributes == rhs.attributes) &&
      (lhs.arrays == rhs.arrays) &&
      (lhs.values_i64 == rhs.values_i64) &&
      (lhs.values_string == rhs.values_string);
}

inline bool operator!=(const DocumentT &lhs, const DocumentT &rhs) {
    return !(lhs == rhs);
}


struct Document FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DocumentT NativeTableType;
  typedef DocumentBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DocumentTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Document";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4,
    VT_OBJECTS = 6,
    VT_ATTRIBUTES = 8,
    VT_ARRAYS = 10,
    VT_VALUES_I64 = 12,
    VT_VALUES_STRING = 14
  };
  const flatbuffers::Vector<uint32_t> *entries() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_ENTRIES);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Object *> *objects() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Object *> *>(VT_OBJECTS);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Attribute *> *attributes() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Attribute *> *>(VT_ATTRIBUTES);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Array *> *arrays() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Array *> *>(VT_ARRAYS);
  }
  const flatbuffers::Vector<int32_t> *values_i64() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_VALUES_I64);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Location *> *values_string() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Location *> *>(VT_VALUES_STRING);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           VerifyOffset(verifier, VT_OBJECTS) &&
           verifier.VerifyVector(objects()) &&
           VerifyOffset(verifier, VT_ATTRIBUTES) &&
           verifier.VerifyVector(attributes()) &&
           VerifyOffset(verifier, VT_ARRAYS) &&
           verifier.VerifyVector(arrays()) &&
           VerifyOffset(verifier, VT_VALUES_I64) &&
           verifier.VerifyVector(values_i64()) &&
           VerifyOffset(verifier, VT_VALUES_STRING) &&
           verifier.VerifyVector(values_string()) &&
           verifier.EndTable();
  }
  DocumentT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DocumentT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Document> Pack(flatbuffers::FlatBufferBuilder &_fbb, const DocumentT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DocumentBuilder {
  typedef Document Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_entries(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> entries) {
    fbb_.AddOffset(Document::VT_ENTRIES, entries);
  }
  void add_objects(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Object *>> objects) {
    fbb_.AddOffset(Document::VT_OBJECTS, objects);
  }
  void add_attributes(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Attribute *>> attributes) {
    fbb_.AddOffset(Document::VT_ATTRIBUTES, attributes);
  }
  void add_arrays(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Array *>> arrays) {
    fbb_.AddOffset(Document::VT_ARRAYS, arrays);
  }
  void add_values_i64(flatbuffers::Offset<flatbuffers::Vector<int32_t>> values_i64) {
    fbb_.AddOffset(Document::VT_VALUES_I64, values_i64);
  }
  void add_values_string(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> values_string) {
    fbb_.AddOffset(Document::VT_VALUES_STRING, values_string);
  }
  explicit DocumentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Document> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Document>(end);
    return o;
  }
};

inline flatbuffers::Offset<Document> CreateDocument(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> entries = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Object *>> objects = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Attribute *>> attributes = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Array *>> arrays = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> values_i64 = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> values_string = 0) {
  DocumentBuilder builder_(_fbb);
  builder_.add_values_string(values_string);
  builder_.add_values_i64(values_i64);
  builder_.add_arrays(arrays);
  builder_.add_attributes(attributes);
  builder_.add_objects(objects);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline flatbuffers::Offset<Document> CreateDocumentDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *entries = nullptr,
    const std::vector<dashql::proto::syntax::Object> *objects = nullptr,
    const std::vector<dashql::proto::syntax::Attribute> *attributes = nullptr,
    const std::vector<dashql::proto::syntax::Array> *arrays = nullptr,
    const std::vector<int32_t> *values_i64 = nullptr,
    const std::vector<dashql::proto::syntax::Location> *values_string = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<uint32_t>(*entries) : 0;
  auto objects__ = objects ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Object>(*objects) : 0;
  auto attributes__ = attributes ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Attribute>(*attributes) : 0;
  auto arrays__ = arrays ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Array>(*arrays) : 0;
  auto values_i64__ = values_i64 ? _fbb.CreateVector<int32_t>(*values_i64) : 0;
  auto values_string__ = values_string ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Location>(*values_string) : 0;
  return dashql::proto::syntax::CreateDocument(
      _fbb,
      entries__,
      objects__,
      attributes__,
      arrays__,
      values_i64__,
      values_string__);
}

flatbuffers::Offset<Document> CreateDocument(flatbuffers::FlatBufferBuilder &_fbb, const DocumentT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ErrorT : public flatbuffers::NativeTable {
  typedef Error TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.ErrorT";
  }
  std::unique_ptr<dashql::proto::syntax::Location> location;
  std::string message;
  ErrorT() {
  }
};

inline bool operator==(const ErrorT &lhs, const ErrorT &rhs) {
  return
      (lhs.location == rhs.location) &&
      (lhs.message == rhs.message);
}

inline bool operator!=(const ErrorT &lhs, const ErrorT &rhs) {
    return !(lhs == rhs);
}


struct Error FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ErrorT NativeTableType;
  typedef ErrorBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ErrorTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Error";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOCATION = 4,
    VT_MESSAGE = 6
  };
  const dashql::proto::syntax::Location *location() const {
    return GetStruct<const dashql::proto::syntax::Location *>(VT_LOCATION);
  }
  const flatbuffers::String *message() const {
    return GetPointer<const flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<dashql::proto::syntax::Location>(verifier, VT_LOCATION) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  ErrorT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ErrorT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Error> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ErrorT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ErrorBuilder {
  typedef Error Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_location(const dashql::proto::syntax::Location *location) {
    fbb_.AddStruct(Error::VT_LOCATION, location);
  }
  void add_message(flatbuffers::Offset<flatbuffers::String> message) {
    fbb_.AddOffset(Error::VT_MESSAGE, message);
  }
  explicit ErrorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Error> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Error>(end);
    return o;
  }
};

inline flatbuffers::Offset<Error> CreateError(
    flatbuffers::FlatBufferBuilder &_fbb,
    const dashql::proto::syntax::Location *location = 0,
    flatbuffers::Offset<flatbuffers::String> message = 0) {
  ErrorBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_location(location);
  return builder_.Finish();
}

inline flatbuffers::Offset<Error> CreateErrorDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const dashql::proto::syntax::Location *location = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return dashql::proto::syntax::CreateError(
      _fbb,
      location,
      message__);
}

flatbuffers::Offset<Error> CreateError(flatbuffers::FlatBufferBuilder &_fbb, const ErrorT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModuleT : public flatbuffers::NativeTable {
  typedef Module TableType;
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.ModuleT";
  }
  std::unique_ptr<dashql::proto::syntax::DocumentT> statements;
  std::vector<std::unique_ptr<dashql::proto::syntax::ErrorT>> errors;
  std::vector<dashql::proto::syntax::Location> line_breaks;
  std::vector<dashql::proto::syntax::Location> comments;
  ModuleT() {
  }
};

inline bool operator==(const ModuleT &lhs, const ModuleT &rhs) {
  return
      (lhs.statements == rhs.statements) &&
      (lhs.errors == rhs.errors) &&
      (lhs.line_breaks == rhs.line_breaks) &&
      (lhs.comments == rhs.comments);
}

inline bool operator!=(const ModuleT &lhs, const ModuleT &rhs) {
    return !(lhs == rhs);
}


struct Module FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ModuleT NativeTableType;
  typedef ModuleBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ModuleTypeTable();
  }
  static FLATBUFFERS_CONSTEXPR const char *GetFullyQualifiedName() {
    return "dashql.proto.syntax.Module";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATEMENTS = 4,
    VT_ERRORS = 6,
    VT_LINE_BREAKS = 8,
    VT_COMMENTS = 10
  };
  const dashql::proto::syntax::Document *statements() const {
    return GetPointer<const dashql::proto::syntax::Document *>(VT_STATEMENTS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<dashql::proto::syntax::Error>> *errors() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<dashql::proto::syntax::Error>> *>(VT_ERRORS);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Location *> *line_breaks() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Location *> *>(VT_LINE_BREAKS);
  }
  const flatbuffers::Vector<const dashql::proto::syntax::Location *> *comments() const {
    return GetPointer<const flatbuffers::Vector<const dashql::proto::syntax::Location *> *>(VT_COMMENTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STATEMENTS) &&
           verifier.VerifyTable(statements()) &&
           VerifyOffset(verifier, VT_ERRORS) &&
           verifier.VerifyVector(errors()) &&
           verifier.VerifyVectorOfTables(errors()) &&
           VerifyOffset(verifier, VT_LINE_BREAKS) &&
           verifier.VerifyVector(line_breaks()) &&
           VerifyOffset(verifier, VT_COMMENTS) &&
           verifier.VerifyVector(comments()) &&
           verifier.EndTable();
  }
  ModuleT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModuleT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Module> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ModuleT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModuleBuilder {
  typedef Module Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_statements(flatbuffers::Offset<dashql::proto::syntax::Document> statements) {
    fbb_.AddOffset(Module::VT_STATEMENTS, statements);
  }
  void add_errors(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<dashql::proto::syntax::Error>>> errors) {
    fbb_.AddOffset(Module::VT_ERRORS, errors);
  }
  void add_line_breaks(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> line_breaks) {
    fbb_.AddOffset(Module::VT_LINE_BREAKS, line_breaks);
  }
  void add_comments(flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> comments) {
    fbb_.AddOffset(Module::VT_COMMENTS, comments);
  }
  explicit ModuleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Module> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Module>(end);
    return o;
  }
};

inline flatbuffers::Offset<Module> CreateModule(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<dashql::proto::syntax::Document> statements = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<dashql::proto::syntax::Error>>> errors = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> line_breaks = 0,
    flatbuffers::Offset<flatbuffers::Vector<const dashql::proto::syntax::Location *>> comments = 0) {
  ModuleBuilder builder_(_fbb);
  builder_.add_comments(comments);
  builder_.add_line_breaks(line_breaks);
  builder_.add_errors(errors);
  builder_.add_statements(statements);
  return builder_.Finish();
}

inline flatbuffers::Offset<Module> CreateModuleDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<dashql::proto::syntax::Document> statements = 0,
    const std::vector<flatbuffers::Offset<dashql::proto::syntax::Error>> *errors = nullptr,
    const std::vector<dashql::proto::syntax::Location> *line_breaks = nullptr,
    const std::vector<dashql::proto::syntax::Location> *comments = nullptr) {
  auto errors__ = errors ? _fbb.CreateVector<flatbuffers::Offset<dashql::proto::syntax::Error>>(*errors) : 0;
  auto line_breaks__ = line_breaks ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Location>(*line_breaks) : 0;
  auto comments__ = comments ? _fbb.CreateVectorOfStructs<dashql::proto::syntax::Location>(*comments) : 0;
  return dashql::proto::syntax::CreateModule(
      _fbb,
      statements,
      errors__,
      line_breaks__,
      comments__);
}

flatbuffers::Offset<Module> CreateModule(flatbuffers::FlatBufferBuilder &_fbb, const ModuleT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DocumentT *Document::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<dashql::proto::syntax::DocumentT> _o = std::unique_ptr<dashql::proto::syntax::DocumentT>(new DocumentT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Document::UnPackTo(DocumentT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = entries(); if (_e) { _o->entries.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->entries[_i] = _e->Get(_i); } } }
  { auto _e = objects(); if (_e) { _o->objects.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->objects[_i] = *_e->Get(_i); } } }
  { auto _e = attributes(); if (_e) { _o->attributes.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->attributes[_i] = *_e->Get(_i); } } }
  { auto _e = arrays(); if (_e) { _o->arrays.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->arrays[_i] = *_e->Get(_i); } } }
  { auto _e = values_i64(); if (_e) { _o->values_i64.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->values_i64[_i] = _e->Get(_i); } } }
  { auto _e = values_string(); if (_e) { _o->values_string.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->values_string[_i] = *_e->Get(_i); } } }
}

inline flatbuffers::Offset<Document> Document::Pack(flatbuffers::FlatBufferBuilder &_fbb, const DocumentT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDocument(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Document> CreateDocument(flatbuffers::FlatBufferBuilder &_fbb, const DocumentT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const DocumentT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _entries = _o->entries.size() ? _fbb.CreateVector(_o->entries) : 0;
  auto _objects = _o->objects.size() ? _fbb.CreateVectorOfStructs(_o->objects) : 0;
  auto _attributes = _o->attributes.size() ? _fbb.CreateVectorOfStructs(_o->attributes) : 0;
  auto _arrays = _o->arrays.size() ? _fbb.CreateVectorOfStructs(_o->arrays) : 0;
  auto _values_i64 = _o->values_i64.size() ? _fbb.CreateVector(_o->values_i64) : 0;
  auto _values_string = _o->values_string.size() ? _fbb.CreateVectorOfStructs(_o->values_string) : 0;
  return dashql::proto::syntax::CreateDocument(
      _fbb,
      _entries,
      _objects,
      _attributes,
      _arrays,
      _values_i64,
      _values_string);
}

inline ErrorT *Error::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<dashql::proto::syntax::ErrorT> _o = std::unique_ptr<dashql::proto::syntax::ErrorT>(new ErrorT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Error::UnPackTo(ErrorT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = location(); if (_e) _o->location = std::unique_ptr<dashql::proto::syntax::Location>(new dashql::proto::syntax::Location(*_e)); }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline flatbuffers::Offset<Error> Error::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ErrorT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateError(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Error> CreateError(flatbuffers::FlatBufferBuilder &_fbb, const ErrorT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ErrorT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _location = _o->location ? _o->location.get() : 0;
  auto _message = _o->message.empty() ? 0 : _fbb.CreateString(_o->message);
  return dashql::proto::syntax::CreateError(
      _fbb,
      _location,
      _message);
}

inline ModuleT *Module::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<dashql::proto::syntax::ModuleT> _o = std::unique_ptr<dashql::proto::syntax::ModuleT>(new ModuleT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Module::UnPackTo(ModuleT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = statements(); if (_e) _o->statements = std::unique_ptr<dashql::proto::syntax::DocumentT>(_e->UnPack(_resolver)); }
  { auto _e = errors(); if (_e) { _o->errors.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->errors[_i] = std::unique_ptr<dashql::proto::syntax::ErrorT>(_e->Get(_i)->UnPack(_resolver)); } } }
  { auto _e = line_breaks(); if (_e) { _o->line_breaks.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->line_breaks[_i] = *_e->Get(_i); } } }
  { auto _e = comments(); if (_e) { _o->comments.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->comments[_i] = *_e->Get(_i); } } }
}

inline flatbuffers::Offset<Module> Module::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ModuleT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModule(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Module> CreateModule(flatbuffers::FlatBufferBuilder &_fbb, const ModuleT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ModuleT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _statements = _o->statements ? CreateDocument(_fbb, _o->statements.get(), _rehasher) : 0;
  auto _errors = _o->errors.size() ? _fbb.CreateVector<flatbuffers::Offset<dashql::proto::syntax::Error>> (_o->errors.size(), [](size_t i, _VectorArgs *__va) { return CreateError(*__va->__fbb, __va->__o->errors[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _line_breaks = _o->line_breaks.size() ? _fbb.CreateVectorOfStructs(_o->line_breaks) : 0;
  auto _comments = _o->comments.size() ? _fbb.CreateVectorOfStructs(_o->comments) : 0;
  return dashql::proto::syntax::CreateModule(
      _fbb,
      _statements,
      _errors,
      _line_breaks,
      _comments);
}

inline const flatbuffers::TypeTable *ObjectTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::ObjectTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "DASHQL_LOAD",
    "DASHQL_PARAMTER",
    "DASHQL_EXTRACT",
    "DASHQL_QUERY",
    "DASHQL_VIZ",
    "SQL_SELECT",
    "SQL_ACONST",
    "SQL_RESULT_TARGET"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 9, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AttributeKeyTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::AttributeKeyTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "DASHQL_PARAMETER_IDENTIFIER",
    "DASHQL_PARAMETER_ALIAS",
    "DASHQL_PARAMETER_TYPE",
    "DASHQL_LOAD_NAME",
    "DASHQL_FILE_LABEL",
    "DASHQL_HTTP_LOAD_NAME",
    "DASHQL_HTTP_LOAD_VERB",
    "DASHQL_HTTP_LOAD_URL",
    "DASHQL_HTTP_LOAD_HEADER",
    "DASHQL_EXTRACT_NAME",
    "DASHQL_EXTRACT_DATA",
    "DASHQL_EXTRACT_METHOD",
    "DASHQL_CSV_EXTRACT_ENCODING",
    "DASHQL_CSV_EXTRACT_HEADER",
    "DASHQL_CSV_EXTRACT_HEADER_COLUMNS",
    "DASHQL_CSV_EXTRACT_DELIMITER",
    "DASHQL_CSV_EXTRACT_QUOTE",
    "DASHQL_CSV_EXTRACT_DATE_FORMAT",
    "DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT",
    "DASHQL_QUERY_NAME",
    "DASHQL_QUERY_STATEMENT",
    "DASHQL_VIZ_TYPE",
    "DASHQL_VIZ_NAME",
    "DASHQL_VIZ_QUERY",
    "SQL_SELECT_TARGETS",
    "SQL_ACONST_TYPE",
    "SQL_ACONST_VALUE",
    "SQL_RESULT_TARGET_NAME",
    "SQL_RESULT_TARGET_VALUE"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 30, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ValueTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::ValueTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "I64",
    "STRING",
    "OBJECT",
    "ARRAY"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *LocationTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "offset",
    "length"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *SpanTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "offset",
    "length"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ValueTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 1 },
    { flatbuffers::ET_LONG, 0, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::LocationTypeTable,
    dashql::proto::syntax::ValueTypeTypeTable
  };
  static const int64_t values[] = { 0, 8, 16, 24 };
  static const char * const names[] = {
    "location",
    "type",
    "value"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ArrayTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::ValueTypeTypeTable
  };
  static const int64_t values[] = { 0, 4, 8, 12 };
  static const char * const names[] = {
    "type",
    "offset",
    "length"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AttributeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 2 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::LocationTypeTable,
    dashql::proto::syntax::AttributeKeyTypeTable,
    dashql::proto::syntax::ValueTypeTable
  };
  static const int64_t values[] = { 0, 8, 16, 40 };
  static const char * const names[] = {
    "location",
    "key",
    "value"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ObjectTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 2 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::LocationTypeTable,
    dashql::proto::syntax::ObjectTypeTypeTable,
    dashql::proto::syntax::SpanTypeTable
  };
  static const int64_t values[] = { 0, 8, 12, 20 };
  static const char * const names[] = {
    "location",
    "type",
    "attributes"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *DocumentTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UINT, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 0 },
    { flatbuffers::ET_SEQUENCE, 1, 1 },
    { flatbuffers::ET_SEQUENCE, 1, 2 },
    { flatbuffers::ET_INT, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 3 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::ObjectTypeTable,
    dashql::proto::syntax::AttributeTypeTable,
    dashql::proto::syntax::ArrayTypeTable,
    dashql::proto::syntax::LocationTypeTable
  };
  static const char * const names[] = {
    "entries",
    "objects",
    "attributes",
    "arrays",
    "values_i64",
    "values_string"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ErrorTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_STRING, 0, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::LocationTypeTable
  };
  static const char * const names[] = {
    "location",
    "message"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ModuleTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 1, 1 },
    { flatbuffers::ET_SEQUENCE, 1, 2 },
    { flatbuffers::ET_SEQUENCE, 1, 2 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax::DocumentTypeTable,
    dashql::proto::syntax::ErrorTypeTable,
    dashql::proto::syntax::LocationTypeTable
  };
  static const char * const names[] = {
    "statements",
    "errors",
    "line_breaks",
    "comments"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace syntax
}  // namespace proto
}  // namespace dashql

#endif  // FLATBUFFERS_GENERATED_SYNTAX_DASHQL_PROTO_SYNTAX_H_
