events {}

http {
    include mime.types;

    index   index.html;

    server {
        root    /usr/share/nginx/html;

        error_page 404 /404.html;

        location / {
            try_files   $uri $uri/ $uri.html =404;
        }
    }
}
