/* eslint-disable */
import { flatbuffers } from "flatbuffers";
// automatically generated by the FlatBuffers compiler, do not modify
/**
 * @enum {number}
 */
export var SQLTypeID;
(function (SQLTypeID) {
    SQLTypeID[SQLTypeID["SQL_INVALID"] = 0] = "SQL_INVALID";
    SQLTypeID[SQLTypeID["SQL_NULL"] = 1] = "SQL_NULL";
    SQLTypeID[SQLTypeID["SQL_UNKNOWN"] = 2] = "SQL_UNKNOWN";
    SQLTypeID[SQLTypeID["SQL_ANY"] = 3] = "SQL_ANY";
    SQLTypeID[SQLTypeID["SQL_BOOLEAN"] = 10] = "SQL_BOOLEAN";
    SQLTypeID[SQLTypeID["SQL_TINYINT"] = 11] = "SQL_TINYINT";
    SQLTypeID[SQLTypeID["SQL_SMALLINT"] = 12] = "SQL_SMALLINT";
    SQLTypeID[SQLTypeID["SQL_INTEGER"] = 13] = "SQL_INTEGER";
    SQLTypeID[SQLTypeID["SQL_BIGINT"] = 14] = "SQL_BIGINT";
    SQLTypeID[SQLTypeID["SQL_DATE"] = 15] = "SQL_DATE";
    SQLTypeID[SQLTypeID["SQL_TIME"] = 16] = "SQL_TIME";
    SQLTypeID[SQLTypeID["SQL_TIMESTAMP"] = 17] = "SQL_TIMESTAMP";
    SQLTypeID[SQLTypeID["SQL_FLOAT"] = 18] = "SQL_FLOAT";
    SQLTypeID[SQLTypeID["SQL_DOUBLE"] = 19] = "SQL_DOUBLE";
    SQLTypeID[SQLTypeID["SQL_DECIMAL"] = 20] = "SQL_DECIMAL";
    SQLTypeID[SQLTypeID["SQL_CHAR"] = 21] = "SQL_CHAR";
    SQLTypeID[SQLTypeID["SQL_VARCHAR"] = 22] = "SQL_VARCHAR";
    SQLTypeID[SQLTypeID["SQL_VARBINARY"] = 23] = "SQL_VARBINARY";
    SQLTypeID[SQLTypeID["SQL_BLOB"] = 24] = "SQL_BLOB";
    SQLTypeID[SQLTypeID["SQL_STRUCT"] = 100] = "SQL_STRUCT";
    SQLTypeID[SQLTypeID["SQL_LIST"] = 101] = "SQL_LIST";
})(SQLTypeID || (SQLTypeID = {}));
;
/**
 * @constructor
 */
var SQLType = /** @class */ (function () {
    function SQLType() {
        this.bb = null;
        this.bb_pos = 0;
    }
    /**
     * @param number i
     * @param flatbuffers.ByteBuffer bb
     * @returns SQLType
     */
    SQLType.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    ;
    /**
     * @param flatbuffers.ByteBuffer bb
     * @param SQLType= obj
     * @returns SQLType
     */
    SQLType.getRootAsSQLType = function (bb, obj) {
        return (obj || new SQLType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ;
    /**
     * @param flatbuffers.ByteBuffer bb
     * @param SQLType= obj
     * @returns SQLType
     */
    SQLType.getSizePrefixedRootAsSQLType = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SQLType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ;
    /**
     * @returns SQLTypeID
     */
    SQLType.prototype.typeId = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? /**  */ (this.bb.readUint8(this.bb_pos + offset)) : SQLTypeID.SQL_INVALID;
    };
    ;
    /**
     * @returns number
     */
    SQLType.prototype.width = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
    };
    ;
    /**
     * @returns number
     */
    SQLType.prototype.scale = function () {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
    };
    ;
    SQLType.prototype.collation = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     */
    SQLType.startSQLType = function (builder) {
        builder.startObject(4);
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     * @param SQLTypeID typeId
     */
    SQLType.addTypeId = function (builder, typeId) {
        builder.addFieldInt8(0, typeId, SQLTypeID.SQL_INVALID);
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     * @param number width
     */
    SQLType.addWidth = function (builder, width) {
        builder.addFieldInt16(1, width, 0);
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     * @param number scale
     */
    SQLType.addScale = function (builder, scale) {
        builder.addFieldInt8(2, scale, 0);
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset collationOffset
     */
    SQLType.addCollation = function (builder, collationOffset) {
        builder.addFieldOffset(3, collationOffset, 0);
    };
    ;
    /**
     * @param flatbuffers.Builder builder
     * @returns flatbuffers.Offset
     */
    SQLType.endSQLType = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    ;
    SQLType.createSQLType = function (builder, typeId, width, scale, collationOffset) {
        SQLType.startSQLType(builder);
        SQLType.addTypeId(builder, typeId);
        SQLType.addWidth(builder, width);
        SQLType.addScale(builder, scale);
        SQLType.addCollation(builder, collationOffset);
        return SQLType.endSQLType(builder);
    };
    return SQLType;
}());
export { SQLType };
//# sourceMappingURL=sql_type_generated.js.map