// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNTAXDASHQL_DASHQL_PROTO_SYNTAX_DASHQL_H_
#define FLATBUFFERS_GENERATED_SYNTAXDASHQL_DASHQL_PROTO_SYNTAX_DASHQL_H_

#include "flatbuffers/flatbuffers.h"


namespace dashql {
namespace proto {
namespace syntax_dashql {

enum class ParameterType : uint8_t {
  NONE = 0,
  INTEGER = 1,
  FLOAT = 2,
  TEXT = 3,
  DATE = 4,
  DATETIME = 5,
  TIME = 6,
  FILE = 7,
  MIN = NONE,
  MAX = FILE
};

inline const ParameterType (&EnumValuesParameterType())[8] {
  static const ParameterType values[] = {
    ParameterType::NONE,
    ParameterType::INTEGER,
    ParameterType::FLOAT,
    ParameterType::TEXT,
    ParameterType::DATE,
    ParameterType::DATETIME,
    ParameterType::TIME,
    ParameterType::FILE
  };
  return values;
}

inline const char * const *EnumNamesParameterType() {
  static const char * const names[9] = {
    "NONE",
    "INTEGER",
    "FLOAT",
    "TEXT",
    "DATE",
    "DATETIME",
    "TIME",
    "FILE",
    nullptr
  };
  return names;
}

inline const char *EnumNameParameterType(ParameterType e) {
  if (flatbuffers::IsOutRange(e, ParameterType::NONE, ParameterType::FILE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesParameterType()[index];
}

enum class LoadMethodType : uint8_t {
  NONE = 0,
  HTTP = 1,
  FILE = 2,
  MIN = NONE,
  MAX = FILE
};

inline const LoadMethodType (&EnumValuesLoadMethodType())[3] {
  static const LoadMethodType values[] = {
    LoadMethodType::NONE,
    LoadMethodType::HTTP,
    LoadMethodType::FILE
  };
  return values;
}

inline const char * const *EnumNamesLoadMethodType() {
  static const char * const names[4] = {
    "NONE",
    "HTTP",
    "FILE",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoadMethodType(LoadMethodType e) {
  if (flatbuffers::IsOutRange(e, LoadMethodType::NONE, LoadMethodType::FILE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoadMethodType()[index];
}

enum class ExtractMethodType : uint8_t {
  NONE = 0,
  CSV = 1,
  JSON = 2,
  MIN = NONE,
  MAX = JSON
};

inline const ExtractMethodType (&EnumValuesExtractMethodType())[3] {
  static const ExtractMethodType values[] = {
    ExtractMethodType::NONE,
    ExtractMethodType::CSV,
    ExtractMethodType::JSON
  };
  return values;
}

inline const char * const *EnumNamesExtractMethodType() {
  static const char * const names[4] = {
    "NONE",
    "CSV",
    "JSON",
    nullptr
  };
  return names;
}

inline const char *EnumNameExtractMethodType(ExtractMethodType e) {
  if (flatbuffers::IsOutRange(e, ExtractMethodType::NONE, ExtractMethodType::JSON)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExtractMethodType()[index];
}

enum class VizType : uint8_t {
  NONE = 0,
  AREA = 1,
  BAR = 2,
  BOX = 3,
  BUBBLE = 4,
  GRID = 5,
  HISTOGRAM = 6,
  LINE = 7,
  NUMBER = 8,
  PIE = 9,
  POINT = 10,
  SCATTER = 11,
  TABLE = 12,
  TEXT = 13,
  MIN = NONE,
  MAX = TEXT
};

inline const VizType (&EnumValuesVizType())[14] {
  static const VizType values[] = {
    VizType::NONE,
    VizType::AREA,
    VizType::BAR,
    VizType::BOX,
    VizType::BUBBLE,
    VizType::GRID,
    VizType::HISTOGRAM,
    VizType::LINE,
    VizType::NUMBER,
    VizType::PIE,
    VizType::POINT,
    VizType::SCATTER,
    VizType::TABLE,
    VizType::TEXT
  };
  return values;
}

inline const char * const *EnumNamesVizType() {
  static const char * const names[15] = {
    "NONE",
    "AREA",
    "BAR",
    "BOX",
    "BUBBLE",
    "GRID",
    "HISTOGRAM",
    "LINE",
    "NUMBER",
    "PIE",
    "POINT",
    "SCATTER",
    "TABLE",
    "TEXT",
    nullptr
  };
  return names;
}

inline const char *EnumNameVizType(VizType e) {
  if (flatbuffers::IsOutRange(e, VizType::NONE, VizType::TEXT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVizType()[index];
}

inline const flatbuffers::TypeTable *ParameterTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_dashql::ParameterTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "INTEGER",
    "FLOAT",
    "TEXT",
    "DATE",
    "DATETIME",
    "TIME",
    "FILE"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *LoadMethodTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_dashql::LoadMethodTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "HTTP",
    "FILE"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ExtractMethodTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_dashql::ExtractMethodTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "CSV",
    "JSON"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *VizTypeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    dashql::proto::syntax_dashql::VizTypeTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "AREA",
    "BAR",
    "BOX",
    "BUBBLE",
    "GRID",
    "HISTOGRAM",
    "LINE",
    "NUMBER",
    "PIE",
    "POINT",
    "SCATTER",
    "TABLE",
    "TEXT"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 14, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace syntax_dashql
}  // namespace proto
}  // namespace dashql

#endif  // FLATBUFFERS_GENERATED_SYNTAXDASHQL_DASHQL_PROTO_SYNTAX_DASHQL_H_
