// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(unused_imports, dead_code)]
pub mod dashql {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;
#[allow(unused_imports, dead_code)]
pub mod proto {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;
#[allow(unused_imports, dead_code)]
pub mod syntax {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;

#[allow(non_camel_case_types)]
#[repr(u16)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum NodeType {
  NONE = 0,
  BOOL = 1,
  UI32 = 2,
  STRING = 3,
  ARRAY = 4,
  ENUM_MIN = 5,
  ENUM_DASHQL_HTTP_VERB = 6,
  ENUM_DASHQL_LOAD_METHOD_TYPE = 7,
  ENUM_DASHQL_PARAMETER_TYPE = 8,
  ENUM_DASHQL_VIZ_TYPE = 9,
  ENUM_SQL_ACONST_TYPE = 10,
  ENUM_SQL_COMBINE_MODIFIER = 11,
  ENUM_SQL_COMBINE_OPERATION = 12,
  ENUM_SQL_EXPRESSION_FUNCTION = 13,
  ENUM_SQL_NUMERIC_TYPE_TAG = 14,
  ENUM_SQL_ORDER_DIRECTION = 15,
  ENUM_SQL_ORDER_NULL_RULE = 16,
  ENUM_SQL_TEMP_TYPE = 17,
  ENUM_SQL_WINDOW_BOUND_DIRECTION = 18,
  ENUM_SQL_WINDOW_BOUND_MODE = 19,
  ENUM_SQL_WINDOW_EXCLUSION_MODE = 20,
  ENUM_SQL_WINDOW_RANGE_MODE = 21,
  OBJECT_MIN = 22,
  OBJECT_DASHQL_LOAD = 23,
  OBJECT_DASHQL_PARAMTER = 24,
  OBJECT_DASHQL_EXTRACT = 25,
  OBJECT_DASHQL_QUERY = 26,
  OBJECT_DASHQL_VIZ = 27,
  OBJECT_SQL_ACONST = 28,
  OBJECT_SQL_AEXPR = 29,
  OBJECT_SQL_ALIAS = 30,
  OBJECT_SQL_COLUMN_REF = 31,
  OBJECT_SQL_COMBINE = 32,
  OBJECT_SQL_CTE = 33,
  OBJECT_SQL_EXPRESSION = 34,
  OBJECT_SQL_INDIRECTION = 35,
  OBJECT_SQL_INTO = 36,
  OBJECT_SQL_NUMERIC_TYPE = 37,
  OBJECT_SQL_ORDER = 38,
  OBJECT_SQL_QUALIFIED_NAME = 39,
  OBJECT_SQL_RELATION_EXPR = 40,
  OBJECT_SQL_RESULT_TARGET = 41,
  OBJECT_SQL_SELECT = 42,
  OBJECT_SQL_TABLE_REF = 43,
  OBJECT_SQL_TYPENAME = 44,
  OBJECT_SQL_WINDOW_BOUND = 45,
  OBJECT_SQL_WINDOW_DEF = 46,
  OBJECT_SQL_WINDOW_FRAME = 47,
  OBJECT_SQL_WITH = 48,

}

pub const ENUM_MIN_NODE_TYPE: u16 = 0;
pub const ENUM_MAX_NODE_TYPE: u16 = 48;

impl<'a> flatbuffers::Follow<'a> for NodeType {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for NodeType {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u16::to_le(self as u16);
    let p = &n as *const u16 as *const NodeType;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u16::from_le(self as u16);
    let p = &n as *const u16 as *const NodeType;
    unsafe { *p }
  }
}

impl flatbuffers::Push for NodeType {
    type Output = NodeType;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<NodeType>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_NODE_TYPE: [NodeType; 49] = [
  NodeType::NONE,
  NodeType::BOOL,
  NodeType::UI32,
  NodeType::STRING,
  NodeType::ARRAY,
  NodeType::ENUM_MIN,
  NodeType::ENUM_DASHQL_HTTP_VERB,
  NodeType::ENUM_DASHQL_LOAD_METHOD_TYPE,
  NodeType::ENUM_DASHQL_PARAMETER_TYPE,
  NodeType::ENUM_DASHQL_VIZ_TYPE,
  NodeType::ENUM_SQL_ACONST_TYPE,
  NodeType::ENUM_SQL_COMBINE_MODIFIER,
  NodeType::ENUM_SQL_COMBINE_OPERATION,
  NodeType::ENUM_SQL_EXPRESSION_FUNCTION,
  NodeType::ENUM_SQL_NUMERIC_TYPE_TAG,
  NodeType::ENUM_SQL_ORDER_DIRECTION,
  NodeType::ENUM_SQL_ORDER_NULL_RULE,
  NodeType::ENUM_SQL_TEMP_TYPE,
  NodeType::ENUM_SQL_WINDOW_BOUND_DIRECTION,
  NodeType::ENUM_SQL_WINDOW_BOUND_MODE,
  NodeType::ENUM_SQL_WINDOW_EXCLUSION_MODE,
  NodeType::ENUM_SQL_WINDOW_RANGE_MODE,
  NodeType::OBJECT_MIN,
  NodeType::OBJECT_DASHQL_LOAD,
  NodeType::OBJECT_DASHQL_PARAMTER,
  NodeType::OBJECT_DASHQL_EXTRACT,
  NodeType::OBJECT_DASHQL_QUERY,
  NodeType::OBJECT_DASHQL_VIZ,
  NodeType::OBJECT_SQL_ACONST,
  NodeType::OBJECT_SQL_AEXPR,
  NodeType::OBJECT_SQL_ALIAS,
  NodeType::OBJECT_SQL_COLUMN_REF,
  NodeType::OBJECT_SQL_COMBINE,
  NodeType::OBJECT_SQL_CTE,
  NodeType::OBJECT_SQL_EXPRESSION,
  NodeType::OBJECT_SQL_INDIRECTION,
  NodeType::OBJECT_SQL_INTO,
  NodeType::OBJECT_SQL_NUMERIC_TYPE,
  NodeType::OBJECT_SQL_ORDER,
  NodeType::OBJECT_SQL_QUALIFIED_NAME,
  NodeType::OBJECT_SQL_RELATION_EXPR,
  NodeType::OBJECT_SQL_RESULT_TARGET,
  NodeType::OBJECT_SQL_SELECT,
  NodeType::OBJECT_SQL_TABLE_REF,
  NodeType::OBJECT_SQL_TYPENAME,
  NodeType::OBJECT_SQL_WINDOW_BOUND,
  NodeType::OBJECT_SQL_WINDOW_DEF,
  NodeType::OBJECT_SQL_WINDOW_FRAME,
  NodeType::OBJECT_SQL_WITH
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_NODE_TYPE: [&str; 49] = [
    "NONE",
    "BOOL",
    "UI32",
    "STRING",
    "ARRAY",
    "ENUM_MIN",
    "ENUM_DASHQL_HTTP_VERB",
    "ENUM_DASHQL_LOAD_METHOD_TYPE",
    "ENUM_DASHQL_PARAMETER_TYPE",
    "ENUM_DASHQL_VIZ_TYPE",
    "ENUM_SQL_ACONST_TYPE",
    "ENUM_SQL_COMBINE_MODIFIER",
    "ENUM_SQL_COMBINE_OPERATION",
    "ENUM_SQL_EXPRESSION_FUNCTION",
    "ENUM_SQL_NUMERIC_TYPE_TAG",
    "ENUM_SQL_ORDER_DIRECTION",
    "ENUM_SQL_ORDER_NULL_RULE",
    "ENUM_SQL_TEMP_TYPE",
    "ENUM_SQL_WINDOW_BOUND_DIRECTION",
    "ENUM_SQL_WINDOW_BOUND_MODE",
    "ENUM_SQL_WINDOW_EXCLUSION_MODE",
    "ENUM_SQL_WINDOW_RANGE_MODE",
    "OBJECT_MIN",
    "OBJECT_DASHQL_LOAD",
    "OBJECT_DASHQL_PARAMTER",
    "OBJECT_DASHQL_EXTRACT",
    "OBJECT_DASHQL_QUERY",
    "OBJECT_DASHQL_VIZ",
    "OBJECT_SQL_ACONST",
    "OBJECT_SQL_AEXPR",
    "OBJECT_SQL_ALIAS",
    "OBJECT_SQL_COLUMN_REF",
    "OBJECT_SQL_COMBINE",
    "OBJECT_SQL_CTE",
    "OBJECT_SQL_EXPRESSION",
    "OBJECT_SQL_INDIRECTION",
    "OBJECT_SQL_INTO",
    "OBJECT_SQL_NUMERIC_TYPE",
    "OBJECT_SQL_ORDER",
    "OBJECT_SQL_QUALIFIED_NAME",
    "OBJECT_SQL_RELATION_EXPR",
    "OBJECT_SQL_RESULT_TARGET",
    "OBJECT_SQL_SELECT",
    "OBJECT_SQL_TABLE_REF",
    "OBJECT_SQL_TYPENAME",
    "OBJECT_SQL_WINDOW_BOUND",
    "OBJECT_SQL_WINDOW_DEF",
    "OBJECT_SQL_WINDOW_FRAME",
    "OBJECT_SQL_WITH"
];

pub fn enum_name_node_type(e: NodeType) -> &'static str {
  let index = e as u16;
  ENUM_NAMES_NODE_TYPE[index as usize]
}

#[allow(non_camel_case_types)]
#[repr(u16)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum AttributeKey {
  NONE = 0,
  DASHQL_PARAMETER_IDENTIFIER = 1,
  DASHQL_PARAMETER_ALIAS = 2,
  DASHQL_PARAMETER_TYPE = 3,
  DASHQL_LOAD_NAME = 4,
  DASHQL_FILE_LABEL = 5,
  DASHQL_HTTP_LOAD_NAME = 6,
  DASHQL_HTTP_LOAD_VERB = 7,
  DASHQL_HTTP_LOAD_URL = 8,
  DASHQL_HTTP_LOAD_HEADER = 9,
  DASHQL_EXTRACT_NAME = 10,
  DASHQL_EXTRACT_DATA = 11,
  DASHQL_EXTRACT_METHOD = 12,
  DASHQL_CSV_EXTRACT_ENCODING = 13,
  DASHQL_CSV_EXTRACT_HEADER = 14,
  DASHQL_CSV_EXTRACT_HEADER_COLUMNS = 15,
  DASHQL_CSV_EXTRACT_DELIMITER = 16,
  DASHQL_CSV_EXTRACT_QUOTE = 17,
  DASHQL_CSV_EXTRACT_DATE_FORMAT = 18,
  DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT = 19,
  DASHQL_QUERY_NAME = 20,
  DASHQL_QUERY_STATEMENT = 21,
  DASHQL_VIZ_TYPE = 22,
  DASHQL_VIZ_NAME = 23,
  DASHQL_VIZ_QUERY = 24,
  SQL_ACONST_TYPE = 25,
  SQL_ACONST_VALUE = 26,
  SQL_ALIAS_COLUMNS = 27,
  SQL_ALIAS_NAME = 28,
  SQL_COLUMN_REF_PATH = 29,
  SQL_COMBINE_INPUT = 30,
  SQL_COMBINE_MODIFIER = 31,
  SQL_COMBINE_OPERATION = 32,
  SQL_CTE_COLUMNS = 33,
  SQL_CTE_NAME = 34,
  SQL_CTE_STATEMENT = 35,
  SQL_EXPRESSION_ARG0 = 36,
  SQL_EXPRESSION_ARG1 = 37,
  SQL_EXPRESSION_ARG2 = 38,
  SQL_EXPRESSION_ARGS = 39,
  SQL_EXPRESSION_FUNCTION = 40,
  SQL_EXPRESSION_INVERTED = 41,
  SQL_INDIRECTION_INDEX = 42,
  SQL_INDIRECTION_LOWER_BOUND = 43,
  SQL_INDIRECTION_UPPER_BOUND = 44,
  SQL_NUMERIC_TYPE_MODIFIERS = 45,
  SQL_NUMERIC_TYPE_TAG = 46,
  SQL_ORDER_DIRECTION = 47,
  SQL_ORDER_NULLRULE = 48,
  SQL_ORDER_VALUE = 49,
  SQL_QUALIFIED_NAME_CATALOG = 50,
  SQL_QUALIFIED_NAME_RELATION = 51,
  SQL_QUALIFIED_NAME_SCHEMA = 52,
  SQL_RESULT_TARGET_INDIRECTION = 53,
  SQL_RESULT_TARGET_NAME = 54,
  SQL_RESULT_TARGET_VALUE = 55,
  SQL_SELECT_ALL = 56,
  SQL_SELECT_DISTINCT = 57,
  SQL_SELECT_FROM = 58,
  SQL_SELECT_GROUPS = 59,
  SQL_SELECT_HAVING = 60,
  SQL_SELECT_INTO = 61,
  SQL_SELECT_LIMIT = 62,
  SQL_SELECT_OFFSET = 63,
  SQL_SELECT_ORDER = 64,
  SQL_SELECT_TABLE = 65,
  SQL_SELECT_TARGETS = 66,
  SQL_SELECT_VALUES = 67,
  SQL_SELECT_WHERE = 68,
  SQL_SELECT_WINDOWS = 69,
  SQL_SELECT_WITH_CTES = 70,
  SQL_SELECT_WITH_RECURSIVE = 71,
  SQL_TABLE_ALIAS = 72,
  SQL_TABLE_INHERIT = 73,
  SQL_TABLE_NAME = 74,
  SQL_TEMP_NAME = 75,
  SQL_TEMP_TYPE = 76,
  SQL_TYPENAME_ARRAY = 77,
  SQL_TYPENAME_SETOF = 78,
  SQL_TYPENAME_TYPE = 79,
  SQL_WINDOW_BOUND_DIRECTION = 80,
  SQL_WINDOW_BOUND_MODE = 81,
  SQL_WINDOW_BOUND_VALUE = 82,
  SQL_WINDOW_DEF_FRAME = 83,
  SQL_WINDOW_DEF_NAME = 84,
  SQL_WINDOW_FRAME_BOUNDS = 85,
  SQL_WINDOW_FRAME_EXCLUDE = 86,
  SQL_WINDOW_FRAME_MODE = 87,
  SQL_WINDOW_FRAME_NAME = 88,
  SQL_WINDOW_FRAME_PARTITION = 89,

}

pub const ENUM_MIN_ATTRIBUTE_KEY: u16 = 0;
pub const ENUM_MAX_ATTRIBUTE_KEY: u16 = 89;

impl<'a> flatbuffers::Follow<'a> for AttributeKey {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for AttributeKey {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u16::to_le(self as u16);
    let p = &n as *const u16 as *const AttributeKey;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u16::from_le(self as u16);
    let p = &n as *const u16 as *const AttributeKey;
    unsafe { *p }
  }
}

impl flatbuffers::Push for AttributeKey {
    type Output = AttributeKey;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<AttributeKey>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ATTRIBUTE_KEY: [AttributeKey; 90] = [
  AttributeKey::NONE,
  AttributeKey::DASHQL_PARAMETER_IDENTIFIER,
  AttributeKey::DASHQL_PARAMETER_ALIAS,
  AttributeKey::DASHQL_PARAMETER_TYPE,
  AttributeKey::DASHQL_LOAD_NAME,
  AttributeKey::DASHQL_FILE_LABEL,
  AttributeKey::DASHQL_HTTP_LOAD_NAME,
  AttributeKey::DASHQL_HTTP_LOAD_VERB,
  AttributeKey::DASHQL_HTTP_LOAD_URL,
  AttributeKey::DASHQL_HTTP_LOAD_HEADER,
  AttributeKey::DASHQL_EXTRACT_NAME,
  AttributeKey::DASHQL_EXTRACT_DATA,
  AttributeKey::DASHQL_EXTRACT_METHOD,
  AttributeKey::DASHQL_CSV_EXTRACT_ENCODING,
  AttributeKey::DASHQL_CSV_EXTRACT_HEADER,
  AttributeKey::DASHQL_CSV_EXTRACT_HEADER_COLUMNS,
  AttributeKey::DASHQL_CSV_EXTRACT_DELIMITER,
  AttributeKey::DASHQL_CSV_EXTRACT_QUOTE,
  AttributeKey::DASHQL_CSV_EXTRACT_DATE_FORMAT,
  AttributeKey::DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT,
  AttributeKey::DASHQL_QUERY_NAME,
  AttributeKey::DASHQL_QUERY_STATEMENT,
  AttributeKey::DASHQL_VIZ_TYPE,
  AttributeKey::DASHQL_VIZ_NAME,
  AttributeKey::DASHQL_VIZ_QUERY,
  AttributeKey::SQL_ACONST_TYPE,
  AttributeKey::SQL_ACONST_VALUE,
  AttributeKey::SQL_ALIAS_COLUMNS,
  AttributeKey::SQL_ALIAS_NAME,
  AttributeKey::SQL_COLUMN_REF_PATH,
  AttributeKey::SQL_COMBINE_INPUT,
  AttributeKey::SQL_COMBINE_MODIFIER,
  AttributeKey::SQL_COMBINE_OPERATION,
  AttributeKey::SQL_CTE_COLUMNS,
  AttributeKey::SQL_CTE_NAME,
  AttributeKey::SQL_CTE_STATEMENT,
  AttributeKey::SQL_EXPRESSION_ARG0,
  AttributeKey::SQL_EXPRESSION_ARG1,
  AttributeKey::SQL_EXPRESSION_ARG2,
  AttributeKey::SQL_EXPRESSION_ARGS,
  AttributeKey::SQL_EXPRESSION_FUNCTION,
  AttributeKey::SQL_EXPRESSION_INVERTED,
  AttributeKey::SQL_INDIRECTION_INDEX,
  AttributeKey::SQL_INDIRECTION_LOWER_BOUND,
  AttributeKey::SQL_INDIRECTION_UPPER_BOUND,
  AttributeKey::SQL_NUMERIC_TYPE_MODIFIERS,
  AttributeKey::SQL_NUMERIC_TYPE_TAG,
  AttributeKey::SQL_ORDER_DIRECTION,
  AttributeKey::SQL_ORDER_NULLRULE,
  AttributeKey::SQL_ORDER_VALUE,
  AttributeKey::SQL_QUALIFIED_NAME_CATALOG,
  AttributeKey::SQL_QUALIFIED_NAME_RELATION,
  AttributeKey::SQL_QUALIFIED_NAME_SCHEMA,
  AttributeKey::SQL_RESULT_TARGET_INDIRECTION,
  AttributeKey::SQL_RESULT_TARGET_NAME,
  AttributeKey::SQL_RESULT_TARGET_VALUE,
  AttributeKey::SQL_SELECT_ALL,
  AttributeKey::SQL_SELECT_DISTINCT,
  AttributeKey::SQL_SELECT_FROM,
  AttributeKey::SQL_SELECT_GROUPS,
  AttributeKey::SQL_SELECT_HAVING,
  AttributeKey::SQL_SELECT_INTO,
  AttributeKey::SQL_SELECT_LIMIT,
  AttributeKey::SQL_SELECT_OFFSET,
  AttributeKey::SQL_SELECT_ORDER,
  AttributeKey::SQL_SELECT_TABLE,
  AttributeKey::SQL_SELECT_TARGETS,
  AttributeKey::SQL_SELECT_VALUES,
  AttributeKey::SQL_SELECT_WHERE,
  AttributeKey::SQL_SELECT_WINDOWS,
  AttributeKey::SQL_SELECT_WITH_CTES,
  AttributeKey::SQL_SELECT_WITH_RECURSIVE,
  AttributeKey::SQL_TABLE_ALIAS,
  AttributeKey::SQL_TABLE_INHERIT,
  AttributeKey::SQL_TABLE_NAME,
  AttributeKey::SQL_TEMP_NAME,
  AttributeKey::SQL_TEMP_TYPE,
  AttributeKey::SQL_TYPENAME_ARRAY,
  AttributeKey::SQL_TYPENAME_SETOF,
  AttributeKey::SQL_TYPENAME_TYPE,
  AttributeKey::SQL_WINDOW_BOUND_DIRECTION,
  AttributeKey::SQL_WINDOW_BOUND_MODE,
  AttributeKey::SQL_WINDOW_BOUND_VALUE,
  AttributeKey::SQL_WINDOW_DEF_FRAME,
  AttributeKey::SQL_WINDOW_DEF_NAME,
  AttributeKey::SQL_WINDOW_FRAME_BOUNDS,
  AttributeKey::SQL_WINDOW_FRAME_EXCLUDE,
  AttributeKey::SQL_WINDOW_FRAME_MODE,
  AttributeKey::SQL_WINDOW_FRAME_NAME,
  AttributeKey::SQL_WINDOW_FRAME_PARTITION
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_ATTRIBUTE_KEY: [&str; 90] = [
    "NONE",
    "DASHQL_PARAMETER_IDENTIFIER",
    "DASHQL_PARAMETER_ALIAS",
    "DASHQL_PARAMETER_TYPE",
    "DASHQL_LOAD_NAME",
    "DASHQL_FILE_LABEL",
    "DASHQL_HTTP_LOAD_NAME",
    "DASHQL_HTTP_LOAD_VERB",
    "DASHQL_HTTP_LOAD_URL",
    "DASHQL_HTTP_LOAD_HEADER",
    "DASHQL_EXTRACT_NAME",
    "DASHQL_EXTRACT_DATA",
    "DASHQL_EXTRACT_METHOD",
    "DASHQL_CSV_EXTRACT_ENCODING",
    "DASHQL_CSV_EXTRACT_HEADER",
    "DASHQL_CSV_EXTRACT_HEADER_COLUMNS",
    "DASHQL_CSV_EXTRACT_DELIMITER",
    "DASHQL_CSV_EXTRACT_QUOTE",
    "DASHQL_CSV_EXTRACT_DATE_FORMAT",
    "DASHQL_CSV_EXTRACT_TIMESTAMP_FORMAT",
    "DASHQL_QUERY_NAME",
    "DASHQL_QUERY_STATEMENT",
    "DASHQL_VIZ_TYPE",
    "DASHQL_VIZ_NAME",
    "DASHQL_VIZ_QUERY",
    "SQL_ACONST_TYPE",
    "SQL_ACONST_VALUE",
    "SQL_ALIAS_COLUMNS",
    "SQL_ALIAS_NAME",
    "SQL_COLUMN_REF_PATH",
    "SQL_COMBINE_INPUT",
    "SQL_COMBINE_MODIFIER",
    "SQL_COMBINE_OPERATION",
    "SQL_CTE_COLUMNS",
    "SQL_CTE_NAME",
    "SQL_CTE_STATEMENT",
    "SQL_EXPRESSION_ARG0",
    "SQL_EXPRESSION_ARG1",
    "SQL_EXPRESSION_ARG2",
    "SQL_EXPRESSION_ARGS",
    "SQL_EXPRESSION_FUNCTION",
    "SQL_EXPRESSION_INVERTED",
    "SQL_INDIRECTION_INDEX",
    "SQL_INDIRECTION_LOWER_BOUND",
    "SQL_INDIRECTION_UPPER_BOUND",
    "SQL_NUMERIC_TYPE_MODIFIERS",
    "SQL_NUMERIC_TYPE_TAG",
    "SQL_ORDER_DIRECTION",
    "SQL_ORDER_NULLRULE",
    "SQL_ORDER_VALUE",
    "SQL_QUALIFIED_NAME_CATALOG",
    "SQL_QUALIFIED_NAME_RELATION",
    "SQL_QUALIFIED_NAME_SCHEMA",
    "SQL_RESULT_TARGET_INDIRECTION",
    "SQL_RESULT_TARGET_NAME",
    "SQL_RESULT_TARGET_VALUE",
    "SQL_SELECT_ALL",
    "SQL_SELECT_DISTINCT",
    "SQL_SELECT_FROM",
    "SQL_SELECT_GROUPS",
    "SQL_SELECT_HAVING",
    "SQL_SELECT_INTO",
    "SQL_SELECT_LIMIT",
    "SQL_SELECT_OFFSET",
    "SQL_SELECT_ORDER",
    "SQL_SELECT_TABLE",
    "SQL_SELECT_TARGETS",
    "SQL_SELECT_VALUES",
    "SQL_SELECT_WHERE",
    "SQL_SELECT_WINDOWS",
    "SQL_SELECT_WITH_CTES",
    "SQL_SELECT_WITH_RECURSIVE",
    "SQL_TABLE_ALIAS",
    "SQL_TABLE_INHERIT",
    "SQL_TABLE_NAME",
    "SQL_TEMP_NAME",
    "SQL_TEMP_TYPE",
    "SQL_TYPENAME_ARRAY",
    "SQL_TYPENAME_SETOF",
    "SQL_TYPENAME_TYPE",
    "SQL_WINDOW_BOUND_DIRECTION",
    "SQL_WINDOW_BOUND_MODE",
    "SQL_WINDOW_BOUND_VALUE",
    "SQL_WINDOW_DEF_FRAME",
    "SQL_WINDOW_DEF_NAME",
    "SQL_WINDOW_FRAME_BOUNDS",
    "SQL_WINDOW_FRAME_EXCLUDE",
    "SQL_WINDOW_FRAME_MODE",
    "SQL_WINDOW_FRAME_NAME",
    "SQL_WINDOW_FRAME_PARTITION"
];

pub fn enum_name_attribute_key(e: AttributeKey) -> &'static str {
  let index = e as u16;
  ENUM_NAMES_ATTRIBUTE_KEY[index as usize]
}

#[allow(non_camel_case_types)]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum DependencyType {
  TABLE_REF = 0,

}

pub const ENUM_MIN_DEPENDENCY_TYPE: u8 = 0;
pub const ENUM_MAX_DEPENDENCY_TYPE: u8 = 0;

impl<'a> flatbuffers::Follow<'a> for DependencyType {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for DependencyType {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u8::to_le(self as u8);
    let p = &n as *const u8 as *const DependencyType;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u8::from_le(self as u8);
    let p = &n as *const u8 as *const DependencyType;
    unsafe { *p }
  }
}

impl flatbuffers::Push for DependencyType {
    type Output = DependencyType;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<DependencyType>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DEPENDENCY_TYPE: [DependencyType; 1] = [
  DependencyType::TABLE_REF
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_DEPENDENCY_TYPE: [&str; 1] = [
    "TABLE_REF"
];

pub fn enum_name_dependency_type(e: DependencyType) -> &'static str {
  let index = e as u8;
  ENUM_NAMES_DEPENDENCY_TYPE[index as usize]
}

// struct Location, aligned to 4
#[repr(C, align(4))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Location {
  pub offset_: u32,
  pub length_: u32,
} // pub struct Location
impl flatbuffers::SafeSliceAccess for Location {}
impl<'a> flatbuffers::Follow<'a> for Location {
  type Inner = &'a Location;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Location>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Location {
  type Inner = &'a Location;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Location>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Location {
    type Output = Location;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const Location as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Location {
    type Output = Location;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const Location as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl Location {
  pub fn new(_offset: u32, _length: u32) -> Self {
    Location {
      offset_: _offset.to_little_endian(),
      length_: _length.to_little_endian(),

    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "dashql.proto.syntax.Location"
    }

  pub fn offset(&self) -> u32 {
    self.offset_.from_little_endian()
  }
  pub fn length(&self) -> u32 {
    self.length_.from_little_endian()
  }
}

// struct Node, aligned to 4
#[repr(C, align(4))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Node {
  pub location_: Location,
  pub node_type_: NodeType,
  pub attribute_key_: AttributeKey,
  pub children_begin_or_value_: u32,
  pub children_count_: u32,
} // pub struct Node
impl flatbuffers::SafeSliceAccess for Node {}
impl<'a> flatbuffers::Follow<'a> for Node {
  type Inner = &'a Node;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Node>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Node {
  type Inner = &'a Node;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Node>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Node {
    type Output = Node;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const Node as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Node {
    type Output = Node;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const Node as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl Node {
  pub fn new(_location: &Location, _node_type: NodeType, _attribute_key: AttributeKey, _children_begin_or_value: u32, _children_count: u32) -> Self {
    Node {
      location_: *_location,
      node_type_: _node_type.to_little_endian(),
      attribute_key_: _attribute_key.to_little_endian(),
      children_begin_or_value_: _children_begin_or_value.to_little_endian(),
      children_count_: _children_count.to_little_endian(),

    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "dashql.proto.syntax.Node"
    }

  pub fn location(&self) -> &Location {
    &self.location_
  }
  pub fn node_type(&self) -> NodeType {
    self.node_type_.from_little_endian()
  }
  pub fn attribute_key(&self) -> AttributeKey {
    self.attribute_key_.from_little_endian()
  }
  pub fn children_begin_or_value(&self) -> u32 {
    self.children_begin_or_value_.from_little_endian()
  }
  pub fn children_count(&self) -> u32 {
    self.children_count_.from_little_endian()
  }
}

// struct Dependency, aligned to 4
#[repr(C, align(4))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Dependency {
  pub type__: DependencyType,
  padding0__: u8,  padding1__: u16,
  pub source_statement_: u32,
  pub target_statement_: u32,
  pub target_value_: u32,
} // pub struct Dependency
impl flatbuffers::SafeSliceAccess for Dependency {}
impl<'a> flatbuffers::Follow<'a> for Dependency {
  type Inner = &'a Dependency;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Dependency>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Dependency {
  type Inner = &'a Dependency;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Dependency>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Dependency {
    type Output = Dependency;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const Dependency as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Dependency {
    type Output = Dependency;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const Dependency as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl Dependency {
  pub fn new(_type_: DependencyType, _source_statement: u32, _target_statement: u32, _target_value: u32) -> Self {
    Dependency {
      type__: _type_.to_little_endian(),
      source_statement_: _source_statement.to_little_endian(),
      target_statement_: _target_statement.to_little_endian(),
      target_value_: _target_value.to_little_endian(),

      padding0__: 0,padding1__: 0,
    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "dashql.proto.syntax.Dependency"
    }

  pub fn type_(&self) -> DependencyType {
    self.type__.from_little_endian()
  }
  pub fn source_statement(&self) -> u32 {
    self.source_statement_.from_little_endian()
  }
  pub fn target_statement(&self) -> u32 {
    self.target_statement_.from_little_endian()
  }
  pub fn target_value(&self) -> u32 {
    self.target_value_.from_little_endian()
  }
}

pub enum ErrorOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct Error<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Error<'a> {
    type Inner = Error<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> Error<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "dashql.proto.syntax.Error"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Error {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args ErrorArgs<'args>) -> flatbuffers::WIPOffset<Error<'bldr>> {
      let mut builder = ErrorBuilder::new(_fbb);
      if let Some(x) = args.message { builder.add_message(x); }
      if let Some(x) = args.location { builder.add_location(x); }
      builder.finish()
    }

    pub const VT_LOCATION: flatbuffers::VOffsetT = 4;
    pub const VT_MESSAGE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn location(&self) -> Option<&'a Location> {
    self._tab.get::<Location>(Error::VT_LOCATION, None)
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Error::VT_MESSAGE, None)
  }
}

pub struct ErrorArgs<'a> {
    pub location: Option<&'a Location>,
    pub message: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ErrorArgs<'a> {
    #[inline]
    fn default() -> Self {
        ErrorArgs {
            location: None,
            message: None,
        }
    }
}
pub struct ErrorBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ErrorBuilder<'a, 'b> {
  #[inline]
  pub fn add_location(&mut self, location: &Location) {
    self.fbb_.push_slot_always::<&Location>(Error::VT_LOCATION, location);
  }
  #[inline]
  pub fn add_message(&mut self, message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Error::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ErrorBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ErrorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Error<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum ModuleOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct Module<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Module<'a> {
    type Inner = Module<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> Module<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "dashql.proto.syntax.Module"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Module {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args ModuleArgs<'args>) -> flatbuffers::WIPOffset<Module<'bldr>> {
      let mut builder = ModuleBuilder::new(_fbb);
      if let Some(x) = args.dependencies { builder.add_dependencies(x); }
      if let Some(x) = args.comments { builder.add_comments(x); }
      if let Some(x) = args.line_breaks { builder.add_line_breaks(x); }
      if let Some(x) = args.errors { builder.add_errors(x); }
      if let Some(x) = args.statements { builder.add_statements(x); }
      if let Some(x) = args.nodes { builder.add_nodes(x); }
      builder.finish()
    }

    pub const VT_NODES: flatbuffers::VOffsetT = 4;
    pub const VT_STATEMENTS: flatbuffers::VOffsetT = 6;
    pub const VT_ERRORS: flatbuffers::VOffsetT = 8;
    pub const VT_LINE_BREAKS: flatbuffers::VOffsetT = 10;
    pub const VT_COMMENTS: flatbuffers::VOffsetT = 12;
    pub const VT_DEPENDENCIES: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn nodes(&self) -> Option<&'a [Node]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<Node>>>(Module::VT_NODES, None).map(|v| v.safe_slice() )
  }
  #[inline]
  pub fn statements(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(Module::VT_STATEMENTS, None)
  }
  #[inline]
  pub fn errors(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Error<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<Error<'a>>>>>(Module::VT_ERRORS, None)
  }
  #[inline]
  pub fn line_breaks(&self) -> Option<&'a [Location]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<Location>>>(Module::VT_LINE_BREAKS, None).map(|v| v.safe_slice() )
  }
  #[inline]
  pub fn comments(&self) -> Option<&'a [Location]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<Location>>>(Module::VT_COMMENTS, None).map(|v| v.safe_slice() )
  }
  #[inline]
  pub fn dependencies(&self) -> Option<&'a [Dependency]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<Dependency>>>(Module::VT_DEPENDENCIES, None).map(|v| v.safe_slice() )
  }
}

pub struct ModuleArgs<'a> {
    pub nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Node>>>,
    pub statements: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub errors: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Error<'a>>>>>,
    pub line_breaks: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Location>>>,
    pub comments: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Location>>>,
    pub dependencies: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Dependency>>>,
}
impl<'a> Default for ModuleArgs<'a> {
    #[inline]
    fn default() -> Self {
        ModuleArgs {
            nodes: None,
            statements: None,
            errors: None,
            line_breaks: None,
            comments: None,
            dependencies: None,
        }
    }
}
pub struct ModuleBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ModuleBuilder<'a, 'b> {
  #[inline]
  pub fn add_nodes(&mut self, nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Node>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_NODES, nodes);
  }
  #[inline]
  pub fn add_statements(&mut self, statements: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_STATEMENTS, statements);
  }
  #[inline]
  pub fn add_errors(&mut self, errors: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Error<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_ERRORS, errors);
  }
  #[inline]
  pub fn add_line_breaks(&mut self, line_breaks: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Location>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_LINE_BREAKS, line_breaks);
  }
  #[inline]
  pub fn add_comments(&mut self, comments: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Location>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_COMMENTS, comments);
  }
  #[inline]
  pub fn add_dependencies(&mut self, dependencies: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Dependency>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Module::VT_DEPENDENCIES, dependencies);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ModuleBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ModuleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Module<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

}  // pub mod syntax
}  // pub mod proto
}  // pub mod dashql

