// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(unused_imports, dead_code)]
pub mod duckdb_webapi {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;
#[allow(unused_imports, dead_code)]
pub mod proto {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;

/// A physical type id
#[allow(non_camel_case_types)]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum PhysicalTypeID {
  /// A NULL type having no physical storage
  NA = 0,
  /// Boolean as 1 bit, LSB bit-packed ordering
  BOOL = 1,
  /// Unsigned 8-bit little-endian integer
  UINT8 = 2,
  /// Signed 8-bit little-endian integer
  INT8 = 3,
  /// Unsigned 16-bit little-endian integer
  UINT16 = 4,
  /// Signed 16-bit little-endian integer
  INT16 = 5,
  /// Unsigned 32-bit little-endian integer
  UINT32 = 6,
  /// Signed 32-bit little-endian integer
  INT32 = 7,
  /// Unsigned 64-bit little-endian integer
  UINT64 = 8,
  /// Signed 64-bit little-endian integer
  INT64 = 9,
  /// 2-byte floating point value
  HALF_FLOAT = 10,
  /// 4-byte floating point value
  FLOAT = 11,
  /// 8-byte floating point value
  DOUBLE = 12,
  /// UTF8 variable-length string as List<Char>
  STRING = 13,
  /// Variable-length bytes (no guarantee of UTF8-ness)
  BINARY = 14,
  /// Fixed-size binary. Each value occupies the same number of bytes
  FIXED_SIZE_BINARY = 15,
  /// int32_t days since the UNIX epoch
  DATE32 = 16,
  /// int64_t milliseconds since the UNIX epoch
  DATE64 = 17,
  /// Exact timestamp encoded with int64 since UNIX epoch
  /// Default unit millisecond
  TIMESTAMP = 18,
  /// Time as signed 32-bit integer, representing either seconds or
  /// milliseconds since midnight
  TIME32 = 19,
  /// Time as signed 64-bit integer, representing either microseconds or
  /// nanoseconds since midnight
  TIME64 = 20,
  /// YEAR_MONTH or DAY_TIME interval in SQL style
  INTERVAL = 21,
  /// Precision- and scale-based decimal type. Storage type depends on the
  /// parameters.
  DECIMAL = 22,
  /// A list of some logical data type
  LIST = 23,
  /// Struct of logical types
  STRUCT = 24,
  /// Unions of logical types
  UNION = 25,
  /// Dictionary-encoded type, also called "categorical" or "factor"
  /// in other programming languages. Holds the dictionary value
  /// type but not the dictionary itself, which is part of the
  /// ArrayData struct
  DICTIONARY = 26,
  /// Map, a repeated struct logical type
  MAP = 27,
  /// Custom data type, implemented by user
  EXTENSION = 28,
  /// Fixed size list of some logical type
  FIXED_SIZE_LIST = 29,
  /// Measure of elapsed time in either seconds, milliseconds, microseconds
  /// or nanoseconds.
  DURATION = 30,
  /// Like STRING, but with 64-bit offsets
  LARGE_STRING = 31,
  /// Like BINARY, but with 64-bit offsets
  LARGE_BINARY = 32,
  /// Like LIST, but with 64-bit offsets
  LARGE_LIST = 33,
  VARCHAR = 200,
  VARBINARY = 201,
  POINTER = 202,
  HASH = 203,
  INT128 = 204,
  INVALID = 255,

}

pub const ENUM_MIN_PHYSICAL_TYPE_ID: u8 = 0;
pub const ENUM_MAX_PHYSICAL_TYPE_ID: u8 = 255;

impl<'a> flatbuffers::Follow<'a> for PhysicalTypeID {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for PhysicalTypeID {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u8::to_le(self as u8);
    let p = &n as *const u8 as *const PhysicalTypeID;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u8::from_le(self as u8);
    let p = &n as *const u8 as *const PhysicalTypeID;
    unsafe { *p }
  }
}

impl flatbuffers::Push for PhysicalTypeID {
    type Output = PhysicalTypeID;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<PhysicalTypeID>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PHYSICAL_TYPE_ID: [PhysicalTypeID; 40] = [
  PhysicalTypeID::NA,
  PhysicalTypeID::BOOL,
  PhysicalTypeID::UINT8,
  PhysicalTypeID::INT8,
  PhysicalTypeID::UINT16,
  PhysicalTypeID::INT16,
  PhysicalTypeID::UINT32,
  PhysicalTypeID::INT32,
  PhysicalTypeID::UINT64,
  PhysicalTypeID::INT64,
  PhysicalTypeID::HALF_FLOAT,
  PhysicalTypeID::FLOAT,
  PhysicalTypeID::DOUBLE,
  PhysicalTypeID::STRING,
  PhysicalTypeID::BINARY,
  PhysicalTypeID::FIXED_SIZE_BINARY,
  PhysicalTypeID::DATE32,
  PhysicalTypeID::DATE64,
  PhysicalTypeID::TIMESTAMP,
  PhysicalTypeID::TIME32,
  PhysicalTypeID::TIME64,
  PhysicalTypeID::INTERVAL,
  PhysicalTypeID::DECIMAL,
  PhysicalTypeID::LIST,
  PhysicalTypeID::STRUCT,
  PhysicalTypeID::UNION,
  PhysicalTypeID::DICTIONARY,
  PhysicalTypeID::MAP,
  PhysicalTypeID::EXTENSION,
  PhysicalTypeID::FIXED_SIZE_LIST,
  PhysicalTypeID::DURATION,
  PhysicalTypeID::LARGE_STRING,
  PhysicalTypeID::LARGE_BINARY,
  PhysicalTypeID::LARGE_LIST,
  PhysicalTypeID::VARCHAR,
  PhysicalTypeID::VARBINARY,
  PhysicalTypeID::POINTER,
  PhysicalTypeID::HASH,
  PhysicalTypeID::INT128,
  PhysicalTypeID::INVALID
];

/// A logical type id
#[allow(non_camel_case_types)]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum LogicalTypeID {
  INVALID = 0,
  SQLNULL = 1,
  UNKNOWN = 2,
  ANY = 3,
  BOOLEAN = 10,
  TINYINT = 11,
  SMALLINT = 12,
  INTEGER = 13,
  BIGINT = 14,
  DATE = 15,
  TIME = 16,
  TIMESTAMP = 17,
  FLOAT = 18,
  DOUBLE = 19,
  DECIMAL = 20,
  CHAR = 21,
  VARCHAR = 22,
  VARBINARY = 23,
  BLOB = 24,
  STRUCT = 100,
  LIST = 101,

}

pub const ENUM_MIN_LOGICAL_TYPE_ID: u8 = 0;
pub const ENUM_MAX_LOGICAL_TYPE_ID: u8 = 101;

impl<'a> flatbuffers::Follow<'a> for LogicalTypeID {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for LogicalTypeID {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u8::to_le(self as u8);
    let p = &n as *const u8 as *const LogicalTypeID;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u8::from_le(self as u8);
    let p = &n as *const u8 as *const LogicalTypeID;
    unsafe { *p }
  }
}

impl flatbuffers::Push for LogicalTypeID {
    type Output = LogicalTypeID;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<LogicalTypeID>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LOGICAL_TYPE_ID: [LogicalTypeID; 21] = [
  LogicalTypeID::INVALID,
  LogicalTypeID::SQLNULL,
  LogicalTypeID::UNKNOWN,
  LogicalTypeID::ANY,
  LogicalTypeID::BOOLEAN,
  LogicalTypeID::TINYINT,
  LogicalTypeID::SMALLINT,
  LogicalTypeID::INTEGER,
  LogicalTypeID::BIGINT,
  LogicalTypeID::DATE,
  LogicalTypeID::TIME,
  LogicalTypeID::TIMESTAMP,
  LogicalTypeID::FLOAT,
  LogicalTypeID::DOUBLE,
  LogicalTypeID::DECIMAL,
  LogicalTypeID::CHAR,
  LogicalTypeID::VARCHAR,
  LogicalTypeID::VARBINARY,
  LogicalTypeID::BLOB,
  LogicalTypeID::STRUCT,
  LogicalTypeID::LIST
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_LOGICAL_TYPE_ID: [&str; 102] = [
    "INVALID",
    "SQLNULL",
    "UNKNOWN",
    "ANY",
    "",
    "",
    "",
    "",
    "",
    "",
    "BOOLEAN",
    "TINYINT",
    "SMALLINT",
    "INTEGER",
    "BIGINT",
    "DATE",
    "TIME",
    "TIMESTAMP",
    "FLOAT",
    "DOUBLE",
    "DECIMAL",
    "CHAR",
    "VARCHAR",
    "VARBINARY",
    "BLOB",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "STRUCT",
    "LIST"
];

pub fn enum_name_logical_type_id(e: LogicalTypeID) -> &'static str {
  let index = e as u8;
  ENUM_NAMES_LOGICAL_TYPE_ID[index as usize]
}

// struct LogicalType, aligned to 2
#[repr(C, align(2))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LogicalType {
  type_id_: LogicalTypeID,
  padding0__: u8,
  width_: u16,
  scale_: u8,
  padding1__: u8,
} // pub struct LogicalType
impl flatbuffers::SafeSliceAccess for LogicalType {}
impl<'a> flatbuffers::Follow<'a> for LogicalType {
  type Inner = &'a LogicalType;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a LogicalType>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a LogicalType {
  type Inner = &'a LogicalType;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<LogicalType>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for LogicalType {
    type Output = LogicalType;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const LogicalType as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b LogicalType {
    type Output = LogicalType;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const LogicalType as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl LogicalType {
  pub fn new(_type_id: LogicalTypeID, _width: u16, _scale: u8) -> Self {
    LogicalType {
      type_id_: _type_id.to_little_endian(),
      width_: _width.to_little_endian(),
      scale_: _scale.to_little_endian(),

      padding0__: 0,
      padding1__: 0,
    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.LogicalType"
    }

  pub fn type_id(&self) -> LogicalTypeID {
    self.type_id_.from_little_endian()
  }
  pub fn width(&self) -> u16 {
    self.width_.from_little_endian()
  }
  pub fn scale(&self) -> u8 {
    self.scale_.from_little_endian()
  }
}

}  // pub mod proto
}  // pub mod duckdb_webapi

