// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(unused_imports, dead_code)]
pub mod duckdb_webapi {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;
#[allow(unused_imports, dead_code)]
pub mod proto {

  use std::mem;
  use std::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::EndianScalar;

#[allow(non_camel_case_types)]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum VectorVariant {
  NONE = 0,
  VectorI8 = 1,
  VectorU8 = 2,
  VectorI16 = 3,
  VectorU16 = 4,
  VectorI32 = 5,
  VectorU32 = 6,
  VectorI64 = 7,
  VectorU64 = 8,
  VectorI128 = 9,
  VectorF32 = 10,
  VectorF64 = 11,
  VectorInterval = 12,
  VectorString = 13,

}

pub const ENUM_MIN_VECTOR_VARIANT: u8 = 0;
pub const ENUM_MAX_VECTOR_VARIANT: u8 = 13;

impl<'a> flatbuffers::Follow<'a> for VectorVariant {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for VectorVariant {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u8::to_le(self as u8);
    let p = &n as *const u8 as *const VectorVariant;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u8::from_le(self as u8);
    let p = &n as *const u8 as *const VectorVariant;
    unsafe { *p }
  }
}

impl flatbuffers::Push for VectorVariant {
    type Output = VectorVariant;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<VectorVariant>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_VECTOR_VARIANT: [VectorVariant; 14] = [
  VectorVariant::NONE,
  VectorVariant::VectorI8,
  VectorVariant::VectorU8,
  VectorVariant::VectorI16,
  VectorVariant::VectorU16,
  VectorVariant::VectorI32,
  VectorVariant::VectorU32,
  VectorVariant::VectorI64,
  VectorVariant::VectorU64,
  VectorVariant::VectorI128,
  VectorVariant::VectorF32,
  VectorVariant::VectorF64,
  VectorVariant::VectorInterval,
  VectorVariant::VectorString
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_VECTOR_VARIANT: [&str; 14] = [
    "NONE",
    "VectorI8",
    "VectorU8",
    "VectorI16",
    "VectorU16",
    "VectorI32",
    "VectorU32",
    "VectorI64",
    "VectorU64",
    "VectorI128",
    "VectorF32",
    "VectorF64",
    "VectorInterval",
    "VectorString"
];

pub fn enum_name_vector_variant(e: VectorVariant) -> &'static str {
  let index = e as u8;
  ENUM_NAMES_VECTOR_VARIANT[index as usize]
}

pub struct VectorVariantUnionTableOffset {}
// struct I128, aligned to 8
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct I128 {
  lower_: u64,
  upper_: i64,
} // pub struct I128
impl flatbuffers::SafeSliceAccess for I128 {}
impl<'a> flatbuffers::Follow<'a> for I128 {
  type Inner = &'a I128;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a I128>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a I128 {
  type Inner = &'a I128;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<I128>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for I128 {
    type Output = I128;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const I128 as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b I128 {
    type Output = I128;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const I128 as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl I128 {
  pub fn new(_lower: u64, _upper: i64) -> Self {
    I128 {
      lower_: _lower.to_little_endian(),
      upper_: _upper.to_little_endian(),

    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.I128"
    }

  pub fn lower(&self) -> u64 {
    self.lower_.from_little_endian()
  }
  pub fn upper(&self) -> i64 {
    self.upper_.from_little_endian()
  }
}

// struct Interval, aligned to 8
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Interval {
  months_: i32,
  days_: i32,
  msecs_: i64,
} // pub struct Interval
impl flatbuffers::SafeSliceAccess for Interval {}
impl<'a> flatbuffers::Follow<'a> for Interval {
  type Inner = &'a Interval;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Interval>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Interval {
  type Inner = &'a Interval;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Interval>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Interval {
    type Output = Interval;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const Interval as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Interval {
    type Output = Interval;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const Interval as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl Interval {
  pub fn new(_months: i32, _days: i32, _msecs: i64) -> Self {
    Interval {
      months_: _months.to_little_endian(),
      days_: _days.to_little_endian(),
      msecs_: _msecs.to_little_endian(),

    }
  }
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.Interval"
    }

  pub fn months(&self) -> i32 {
    self.months_.from_little_endian()
  }
  pub fn days(&self) -> i32 {
    self.days_.from_little_endian()
  }
  pub fn msecs(&self) -> i64 {
    self.msecs_.from_little_endian()
  }
}

pub enum VectorI8Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorI8<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorI8<'a> {
    type Inner = VectorI8<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorI8<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorI8"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorI8 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorI8Args<'args>) -> flatbuffers::WIPOffset<VectorI8<'bldr>> {
      let mut builder = VectorI8Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<&'a [i8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i8>>>(VectorI8::VT_VALUES, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorI8::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorI8Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i8>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorI8Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorI8Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorI8Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorI8Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI8::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI8::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorI8Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorI8Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorI8<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorU8Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorU8<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorU8<'a> {
    type Inner = VectorU8<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorU8<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorU8"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorU8 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorU8Args<'args>) -> flatbuffers::WIPOffset<VectorU8<'bldr>> {
      let mut builder = VectorU8Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<&'a [u8]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(VectorU8::VT_VALUES, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorU8::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorU8Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorU8Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorU8Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorU8Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorU8Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU8::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU8::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorU8Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorU8Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorU8<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorI16Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorI16<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorI16<'a> {
    type Inner = VectorI16<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorI16<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorI16"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorI16 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorI16Args<'args>) -> flatbuffers::WIPOffset<VectorI16<'bldr>> {
      let mut builder = VectorI16Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, i16>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i16>>>(VectorI16::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorI16::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorI16Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i16>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorI16Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorI16Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorI16Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorI16Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI16::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI16::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorI16Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorI16Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorI16<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorU16Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorU16<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorU16<'a> {
    type Inner = VectorU16<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorU16<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorU16"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorU16 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorU16Args<'args>) -> flatbuffers::WIPOffset<VectorU16<'bldr>> {
      let mut builder = VectorU16Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, u16>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(VectorU16::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorU16::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorU16Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorU16Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorU16Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorU16Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorU16Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU16::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU16::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorU16Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorU16Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorU16<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorI32Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorI32<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorI32<'a> {
    type Inner = VectorI32<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorI32<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorI32"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorI32 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorI32Args<'args>) -> flatbuffers::WIPOffset<VectorI32<'bldr>> {
      let mut builder = VectorI32Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(VectorI32::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorI32::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorI32Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorI32Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorI32Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorI32Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorI32Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI32::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI32::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorI32Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorI32Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorI32<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorU32Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorU32<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorU32<'a> {
    type Inner = VectorU32<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorU32<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorU32"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorU32 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorU32Args<'args>) -> flatbuffers::WIPOffset<VectorU32<'bldr>> {
      let mut builder = VectorU32Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(VectorU32::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorU32::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorU32Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorU32Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorU32Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorU32Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorU32Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU32::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU32::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorU32Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorU32Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorU32<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorI64Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorI64<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorI64<'a> {
    type Inner = VectorI64<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorI64<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorI64"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorI64 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorI64Args<'args>) -> flatbuffers::WIPOffset<VectorI64<'bldr>> {
      let mut builder = VectorI64Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, i64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i64>>>(VectorI64::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorI64::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorI64Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i64>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorI64Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorI64Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorI64Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorI64Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI64::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI64::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorI64Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorI64Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorI64<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorU64Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorU64<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorU64<'a> {
    type Inner = VectorU64<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorU64<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorU64"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorU64 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorU64Args<'args>) -> flatbuffers::WIPOffset<VectorU64<'bldr>> {
      let mut builder = VectorU64Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(VectorU64::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorU64::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorU64Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorU64Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorU64Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorU64Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorU64Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU64::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorU64::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorU64Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorU64Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorU64<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorI128Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorI128<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorI128<'a> {
    type Inner = VectorI128<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorI128<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorI128"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorI128 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorI128Args<'args>) -> flatbuffers::WIPOffset<VectorI128<'bldr>> {
      let mut builder = VectorI128Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<&'a [I128]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<I128>>>(VectorI128::VT_VALUES, None).map(|v| v.safe_slice() )
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorI128::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorI128Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, I128>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorI128Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorI128Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorI128Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorI128Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , I128>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI128::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorI128::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorI128Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorI128Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorI128<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorF32Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorF32<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorF32<'a> {
    type Inner = VectorF32<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorF32<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorF32"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorF32 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorF32Args<'args>) -> flatbuffers::WIPOffset<VectorF32<'bldr>> {
      let mut builder = VectorF32Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(VectorF32::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorF32::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorF32Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorF32Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorF32Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorF32Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorF32Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorF32::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorF32::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorF32Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorF32Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorF32<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorF64Offset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorF64<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorF64<'a> {
    type Inner = VectorF64<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorF64<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorF64"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorF64 {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorF64Args<'args>) -> flatbuffers::WIPOffset<VectorF64<'bldr>> {
      let mut builder = VectorF64Builder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, f64>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f64>>>(VectorF64::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorF64::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorF64Args<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f64>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorF64Args<'a> {
    #[inline]
    fn default() -> Self {
        VectorF64Args {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorF64Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorF64Builder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorF64::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorF64::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorF64Builder<'a, 'b> {
    let start = _fbb.start_table();
    VectorF64Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorF64<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorIntervalOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorInterval<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorInterval<'a> {
    type Inner = VectorInterval<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorInterval<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorInterval"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorInterval {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorIntervalArgs<'args>) -> flatbuffers::WIPOffset<VectorInterval<'bldr>> {
      let mut builder = VectorIntervalBuilder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<&'a [Interval]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<Interval>>>(VectorInterval::VT_VALUES, None).map(|v| v.safe_slice() )
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorInterval::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorIntervalArgs<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Interval>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorIntervalArgs<'a> {
    #[inline]
    fn default() -> Self {
        VectorIntervalArgs {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorIntervalBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorIntervalBuilder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Interval>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorInterval::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorInterval::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorIntervalBuilder<'a, 'b> {
    let start = _fbb.start_table();
    VectorIntervalBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorInterval<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorStringOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct VectorString<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for VectorString<'a> {
    type Inner = VectorString<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> VectorString<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.VectorString"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        VectorString {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorStringArgs<'args>) -> flatbuffers::WIPOffset<VectorString<'bldr>> {
      let mut builder = VectorStringBuilder::new(_fbb);
      if let Some(x) = args.null_mask { builder.add_null_mask(x); }
      if let Some(x) = args.values { builder.add_values(x); }
      builder.finish()
    }

    pub const VT_VALUES: flatbuffers::VOffsetT = 4;
    pub const VT_NULL_MASK: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<&'a str>>>>(VectorString::VT_VALUES, None)
  }
  #[inline]
  pub fn null_mask(&self) -> Option<&'a [bool]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, bool>>>(VectorString::VT_NULL_MASK, None).map(|v| v.safe_slice())
  }
}

pub struct VectorStringArgs<'a> {
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub null_mask: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, bool>>>,
}
impl<'a> Default for VectorStringArgs<'a> {
    #[inline]
    fn default() -> Self {
        VectorStringArgs {
            values: None,
            null_mask: None,
        }
    }
}
pub struct VectorStringBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorStringBuilder<'a, 'b> {
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorString::VT_VALUES, values);
  }
  #[inline]
  pub fn add_null_mask(&mut self, null_mask: flatbuffers::WIPOffset<flatbuffers::Vector<'b , bool>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(VectorString::VT_NULL_MASK, null_mask);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorStringBuilder<'a, 'b> {
    let start = _fbb.start_table();
    VectorStringBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<VectorString<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum VectorOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct Vector<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Vector<'a> {
    type Inner = Vector<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table { buf, loc } }
    }
}

impl<'a> Vector<'a> {
    pub const fn get_fully_qualified_name() -> &'static str {
        "duckdb_webapi.proto.Vector"
    }

    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Vector {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args VectorArgs) -> flatbuffers::WIPOffset<Vector<'bldr>> {
      let mut builder = VectorBuilder::new(_fbb);
      if let Some(x) = args.variant { builder.add_variant(x); }
      builder.add_variant_type(args.variant_type);
      builder.finish()
    }

    pub const VT_VARIANT_TYPE: flatbuffers::VOffsetT = 4;
    pub const VT_VARIANT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn variant_type(&self) -> VectorVariant {
    self._tab.get::<VectorVariant>(Vector::VT_VARIANT_TYPE, Some(VectorVariant::NONE)).unwrap()
  }
  #[inline]
  pub fn variant(&self) -> Option<flatbuffers::Table<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Vector::VT_VARIANT, None)
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_i8(&self) -> Option<VectorI8<'a>> {
    if self.variant_type() == VectorVariant::VectorI8 {
      self.variant().map(VectorI8::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_u8(&self) -> Option<VectorU8<'a>> {
    if self.variant_type() == VectorVariant::VectorU8 {
      self.variant().map(VectorU8::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_i16(&self) -> Option<VectorI16<'a>> {
    if self.variant_type() == VectorVariant::VectorI16 {
      self.variant().map(VectorI16::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_u16(&self) -> Option<VectorU16<'a>> {
    if self.variant_type() == VectorVariant::VectorU16 {
      self.variant().map(VectorU16::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_i32(&self) -> Option<VectorI32<'a>> {
    if self.variant_type() == VectorVariant::VectorI32 {
      self.variant().map(VectorI32::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_u32(&self) -> Option<VectorU32<'a>> {
    if self.variant_type() == VectorVariant::VectorU32 {
      self.variant().map(VectorU32::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_i64(&self) -> Option<VectorI64<'a>> {
    if self.variant_type() == VectorVariant::VectorI64 {
      self.variant().map(VectorI64::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_u64(&self) -> Option<VectorU64<'a>> {
    if self.variant_type() == VectorVariant::VectorU64 {
      self.variant().map(VectorU64::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_i128(&self) -> Option<VectorI128<'a>> {
    if self.variant_type() == VectorVariant::VectorI128 {
      self.variant().map(VectorI128::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_f32(&self) -> Option<VectorF32<'a>> {
    if self.variant_type() == VectorVariant::VectorF32 {
      self.variant().map(VectorF32::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_f64(&self) -> Option<VectorF64<'a>> {
    if self.variant_type() == VectorVariant::VectorF64 {
      self.variant().map(VectorF64::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_interval(&self) -> Option<VectorInterval<'a>> {
    if self.variant_type() == VectorVariant::VectorInterval {
      self.variant().map(VectorInterval::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn variant_as_vector_string(&self) -> Option<VectorString<'a>> {
    if self.variant_type() == VectorVariant::VectorString {
      self.variant().map(VectorString::init_from_table)
    } else {
      None
    }
  }

}

pub struct VectorArgs {
    pub variant_type: VectorVariant,
    pub variant: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for VectorArgs {
    #[inline]
    fn default() -> Self {
        VectorArgs {
            variant_type: VectorVariant::NONE,
            variant: None,
        }
    }
}
pub struct VectorBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> VectorBuilder<'a, 'b> {
  #[inline]
  pub fn add_variant_type(&mut self, variant_type: VectorVariant) {
    self.fbb_.push_slot::<VectorVariant>(Vector::VT_VARIANT_TYPE, variant_type, VectorVariant::NONE);
  }
  #[inline]
  pub fn add_variant(&mut self, variant: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Vector::VT_VARIANT, variant);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> VectorBuilder<'a, 'b> {
    let start = _fbb.start_table();
    VectorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Vector<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

}  // pub mod proto
}  // pub mod duckdb_webapi

