name: 'Setup Bazel'
description: 'Setup Bazel with trusted CI defaults'

inputs:
  bazel-results-url:
    description: 'Bazel invocation results URL'
    required: true
  bazel-bes-backend:
    description: 'Bazel Build Event Service backend'
    required: true
  bazel-remote-cache:
    description: 'Bazel remote cache URL'
    required: true
  bazel-auth-header:
    description: 'Remote cache authentication header'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.18.0
      with:
        bazelisk-cache: true
        repository-cache: true
        bazelrc: |
          build --bes_results_url=${{ inputs.bazel-results-url }}
          build --bes_backend=${{ inputs.bazel-bes-backend }}
          common --remote_cache=${{ inputs.bazel-remote-cache }}
          common --remote_timeout=10m
          common --remote_header="${{ inputs.bazel-auth-header }}"
          build --remote_cache_compression=true
          build --remote_download_outputs=toplevel
          build --noslim_profile
          build --experimental_profile_include_target_label
          build --experimental_profile_include_primary_output
