
export enum AppLoadingStatus {
    NOT_STARTED = 0,
    LOAD_STORAGE = 1,
    SETUP_DEFAULT_CONNECTIONS = 2,
    SETUP_DEFAULT_NOTEBOOKS = 3,
    SETUP_PROVIDED_CONNECTION = 4,
    SETUP_PROVIDED_NOTEBOOK = 5,
    SETUP_FAILED = 6,
    SETUP_DONE = 7,
}
