[package]
name = "sqlynx-compute"
version = "0.0.2-dev.17"
description = "Arrow-backed computations for SQLynx"
edition = "2021"
rust-version = "1.70"
workspace = "../../"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.94"
wasm-bindgen-futures = "0.4.45"
console_error_panic_hook = "0.1.7"

log = "0.4.22"
chrono = { version = "0.4.38", features = ["wasmbind"] }
getrandom = { version = "0.2.15", features = ["js"] }
anyhow = "1.0.90"

prost = "0.13.3"

tokio = { version = "1.41.0", features = ["macros", "rt", "sync"] }
arrow = { version = "53.2.0", default-features = false, features = ["ipc"] }

datafusion-common = { version = "42.1.0", default-features = false }
datafusion-expr = { version = "42.1.0", default-features = false }
datafusion-execution = { version = "42.1.0", default-features = false }
datafusion-functions = { version = "42.1.0", default-features = false }
datafusion-functions-aggregate = { version = "42.1.0", default-features = false }
datafusion-functions-nested = { version = "42.1.0", default-features = false }
datafusion-physical-expr = { version = "42.1.0", default-features = false }
datafusion-physical-plan = { version = "42.1.0", default-features = false }

[dependencies.web-sys]
version = "0.3.71"
features = [
  'console',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.45"
pretty_assertions = "1.4.1"
indoc = "2.0.5"

[build-dependencies]
anyhow = "1.0.90"
regex = "1.11.0"
prost-build = "0.13.3"

[profile.release]
strip = true
lto = true
opt-level = "s"
