[package]
name = "sqlynx-compute"
version = "0.0.2-dev.17"
description = "Arrow-backed computations for SQLynx"
edition = "2021"
rust-version = "1.70"
workspace = "../../"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

log = "0.4"
chrono = { version = "0.4", features = ["wasmbind"] }
getrandom = { version = "0.2.8", features = ["js"] }

datafusion = { version = "42.0.0", default-features = false }
datafusion-execution = { version = "42.0.0", default-features = false }
datafusion-expr = { version = "42.0.0", default-features = false }
datafusion-optimizer = { version = "42.0.0", default-features = true }
datafusion-physical-expr = { version = "42.0.0", default-features = true }
datafusion-physical-plan = { version = "42.0.0", default-features = false }

[dependencies.web-sys]
version = "0.3"
features = [
  'console',
]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
lto = true
opt-level = "s"
