use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::{env, fs};

use anyhow::{Context, Result};
use serde::Deserialize;
use tauri_utils::acl::manifest::{Manifest, PermissionFile};
use tauri_utils::acl::{ACL_MANIFESTS_FILE_NAME, CAPABILITIES_FILE_NAME};
use tauri_utils::write_if_changed;

// ---------------------------------------------------------------------------
// CLI parsing (no clap dependency — just positional/flag args)
// ---------------------------------------------------------------------------

struct Args {
    core_config: PathBuf,
    out_dir: PathBuf,
    capabilities: Vec<PathBuf>,
    /// (plugin_name, toml_path)
    plugin_files: Vec<(String, PathBuf)>,
}

fn parse_args() -> Result<Args> {
    let mut core_config = None;
    let mut out_dir = None;
    let mut capabilities = Vec::new();
    let mut plugin_files = Vec::new();

    let mut args = env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--core-config" => {
                core_config = Some(PathBuf::from(
                    args.next().context("--core-config requires a value")?,
                ));
            }
            "--out-dir" => {
                out_dir = Some(PathBuf::from(
                    args.next().context("--out-dir requires a value")?,
                ));
            }
            "--capability" => {
                capabilities.push(PathBuf::from(
                    args.next().context("--capability requires a value")?,
                ));
            }
            "--plugin-file" => {
                let val = args.next().context("--plugin-file requires name=path")?;
                let (name, path) = val
                    .split_once('=')
                    .context("--plugin-file value must be name=path")?;
                plugin_files.push((name.to_string(), PathBuf::from(path)));
            }
            other => anyhow::bail!("unknown argument: {other}"),
        }
    }

    Ok(Args {
        core_config: core_config.context("--core-config is required")?,
        out_dir: out_dir.context("--out-dir is required")?,
        capabilities,
        plugin_files,
    })
}

// ---------------------------------------------------------------------------
// acl_core_permissions.toml schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct CoreConfig {
    module: Vec<CoreModule>,
}

#[derive(Deserialize)]
struct CoreModule {
    name: String,
    commands: Vec<CoreCommand>,
}

#[derive(Deserialize)]
struct CoreCommand {
    name: String,
    default: bool,
}

// ---------------------------------------------------------------------------
// Permission file parsing (replicates tauri_utils::acl::build private fn)
// ---------------------------------------------------------------------------

fn parse_permission_file(path: &Path) -> Result<PermissionFile> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");
    match ext {
        "toml" => toml::from_str(&content)
            .with_context(|| format!("failed to parse TOML {}", path.display())),
        "json" => serde_json::from_str(&content)
            .with_context(|| format!("failed to parse JSON {}", path.display())),
        _ => anyhow::bail!("unsupported permission file format: {}", path.display()),
    }
}

// ---------------------------------------------------------------------------
// Core permission generation (mirrors tauri 2.10.3 build.rs logic)
// ---------------------------------------------------------------------------

fn generate_core_permissions(
    config: &CoreConfig,
    work_dir: &Path,
    out_dir: &Path,
) -> Result<BTreeMap<String, Vec<PermissionFile>>> {
    let mut all_permissions = BTreeMap::new();

    for module in &config.module {
        let plugin = &module.name; // e.g. "core:app"
        let dir_name = plugin.strip_prefix("core:").unwrap_or(plugin);
        let permissions_out_dir = work_dir.join("permissions").join(dir_name);
        let commands_dir = permissions_out_dir
            .join(tauri_utils::acl::build::AUTOGENERATED_FOLDER_NAME)
            .join("commands");

        let command_names: Vec<&str> = module.commands.iter().map(|c| c.name.as_str()).collect();

        tauri_utils::acl::build::autogenerate_command_permissions(
            &commands_dir,
            &command_names,
            "",
            false,
        );

        // Generate default.toml listing default-enabled commands
        let default_permissions: Vec<_> = module
            .commands
            .iter()
            .filter(|c| c.default)
            .map(|c| {
                let slug = c.name.replace('_', "-");
                format!("\"allow-{slug}\"")
            })
            .collect();

        let all_default = module.commands.len() == default_permissions.len();
        let suffix = if all_default {
            ", which enables all commands"
        } else {
            ""
        };

        let default_toml = format!(
            "# Automatically generated - DO NOT EDIT!\n\n\
             [default]\n\
             description = \"Default permissions for the plugin{suffix}.\"\n\
             permissions = [{}]\n",
            default_permissions.join(", ")
        );

        let autogenerated_dir = permissions_out_dir
            .join(tauri_utils::acl::build::AUTOGENERATED_FOLDER_NAME);
        let default_path = autogenerated_dir.join("default.toml");
        fs::create_dir_all(&autogenerated_dir)?;
        write_if_changed(&default_path, default_toml)
            .context("failed to write default.toml")?;

        let glob_pattern = format!(
            "{}/**/*.toml",
            glob::Pattern::escape(&permissions_out_dir.to_string_lossy())
        );

        let permissions = tauri_utils::acl::build::define_permissions(
            &glob_pattern,
            &format!("tauri:{plugin}"),
            out_dir,
            |_| true,
        )
        .with_context(|| format!("failed to define permissions for {plugin}"))?;

        all_permissions.insert(plugin.clone(), permissions);
    }

    // Generate core:default permission set (aggregates all module defaults)
    let core_default_dir = work_dir.join("permissions").join("__core_default__");
    fs::create_dir_all(&core_default_dir)?;

    let module_defaults = config
        .module
        .iter()
        .map(|m| format!("\"{}:default\"", m.name))
        .collect::<Vec<_>>()
        .join(",");

    let core_default_toml = format!(
        "# Automatically generated - DO NOT EDIT!\n\n\
         [default]\n\
         description = \"Default core plugins set.\"\n\
         permissions = [{module_defaults}]\n"
    );

    write_if_changed(&core_default_dir.join("default.toml"), core_default_toml)?;

    let core_default_perms = tauri_utils::acl::build::define_permissions(
        &format!(
            "{}/*.toml",
            glob::Pattern::escape(&core_default_dir.to_string_lossy())
        ),
        "tauri:core",
        out_dir,
        |_| true,
    )?;

    all_permissions.insert("core".to_string(), core_default_perms);

    Ok(all_permissions)
}

// ---------------------------------------------------------------------------
// Plugin permission loading
// ---------------------------------------------------------------------------

fn load_plugin_permissions(
    plugin_files: &[(String, PathBuf)],
) -> Result<BTreeMap<String, Vec<PermissionFile>>> {
    let mut grouped: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();
    for (name, path) in plugin_files {
        grouped.entry(name.clone()).or_default().push(path.clone());
    }

    let mut result = BTreeMap::new();
    for (name, paths) in grouped {
        let mut perms = Vec::new();
        for path in &paths {
            perms.push(
                parse_permission_file(path)
                    .with_context(|| format!("plugin {name}: {}", path.display()))?,
            );
        }
        result.insert(name, perms);
    }

    Ok(result)
}

// ---------------------------------------------------------------------------
// Capability parsing (replicates tauri_utils::acl::build::parse_capabilities
// but from explicit file list instead of glob)
// ---------------------------------------------------------------------------

fn parse_capabilities(
    files: &[PathBuf],
) -> Result<BTreeMap<String, tauri_utils::acl::capability::Capability>> {
    use tauri_utils::acl::capability::CapabilityFile;

    let mut map = BTreeMap::new();
    for path in files {
        let cap_file = CapabilityFile::load(path)
            .with_context(|| format!("failed to load capability {}", path.display()))?;
        match cap_file {
            CapabilityFile::Capability(c) => {
                map.insert(c.identifier.clone(), c);
            }
            CapabilityFile::List(list) | CapabilityFile::NamedList { capabilities: list } => {
                for c in list {
                    map.insert(c.identifier.clone(), c);
                }
            }
        }
    }
    Ok(map)
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() -> Result<()> {
    let args = parse_args()?;

    fs::create_dir_all(&args.out_dir)?;

    // Temp work directory for autogenerated core permission TOMLs
    let work_dir = args.out_dir.join("_gen_work");
    fs::create_dir_all(&work_dir)?;

    // 1. Generate core permissions from config
    let core_permissions =
        generate_core_permissions(&CoreConfig::deserialize(
            toml::de::Deserializer::new(
                &fs::read_to_string(&args.core_config)
                    .context("failed to read core config")?,
            ),
        )?, &work_dir, &args.out_dir)?;

    // 2. Load plugin permissions from TOML files
    let plugin_permissions = load_plugin_permissions(&args.plugin_files)?;

    // 3. Build merged ACL manifests
    let mut acl_manifests: BTreeMap<String, Manifest> = BTreeMap::new();

    // Core modules
    for (name, perms) in &core_permissions {
        let manifest = Manifest::new(perms.clone(), None);
        // Core modules use "tauri:xxx" format -> key is just the module name
        let key = name
            .strip_prefix("core:")
            .map(|s| format!("core:{s}"))
            .unwrap_or_else(|| name.clone());
        acl_manifests.insert(key, manifest);
    }

    // Plugin permission files map (for generate_allowed_commands)
    let mut all_permission_files: BTreeMap<String, Vec<PermissionFile>> = BTreeMap::new();

    // Plugins
    for (name, perms) in &plugin_permissions {
        let manifest = Manifest::new(perms.clone(), None);
        acl_manifests.insert(name.clone(), manifest);
        all_permission_files.insert(name.clone(), perms.clone());
    }

    // Also add core permission files
    for (name, perms) in &core_permissions {
        all_permission_files.insert(name.clone(), perms.clone());
    }

    // 4. Parse capabilities
    let capabilities = parse_capabilities(&args.capabilities)?;

    // 5. Write acl-manifests.json
    let acl_json = serde_json::to_string(&acl_manifests)?;
    write_if_changed(&args.out_dir.join(ACL_MANIFESTS_FILE_NAME), acl_json)?;

    // 6. Write capabilities.json
    let cap_json = serde_json::to_string(&capabilities)?;
    write_if_changed(&args.out_dir.join(CAPABILITIES_FILE_NAME), cap_json)?;

    // 7. Generate allowed-commands.json
    tauri_utils::acl::build::generate_allowed_commands(
        &args.out_dir,
        Some(capabilities),
        all_permission_files,
    )?;

    // Clean up work directory
    let _ = fs::remove_dir_all(&work_dir);

    eprintln!(
        "tauri_aclgen: wrote {} manifests to {}",
        acl_manifests.len(),
        args.out_dir.display()
    );

    Ok(())
}
