name: Build

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string
            signed:
                required: false
                type: boolean
                default: false

jobs:
    build:
        name: ${{ matrix.job_name }}
        runs-on: ${{ matrix.runs_on }}
        strategy:
            matrix:
                include:
                    - job_name: Linux / Debug
                      runs_on: ubuntu-24.04
                      bazel_flags: ""
                    - job_name: Linux / Release
                      runs_on: ubuntu-24.04
                      bazel_flags: "--config=release"
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: bazel-contrib/setup-bazel@v0.18.0
              with:
                  bazelisk-cache: true
                  repository-cache: true
                  disk-cache: ${{ github.workflow }}

            - name: Setup protoc
              uses: ./.github/actions/setup-protoc
              with:
                os: ubuntu-24.04

            - name: Build DashQL
              shell: bash
              run: |
                  bazel build ${{ matrix.bazel_flags }} \
                    //packages/dashql-pack:pack \
                    //packages/dashql-compute:dist \
                    //packages/dashql-core:core_wasm \
                    //packages/dashql-core:test_main \
                    //packages/dashql-app:pages \
                    //packages/dashql-app:reloc \
                    //packages/dashql-native:app

            - name: Test DashQL
              shell: bash
              run: |
                  bazel test ${{ matrix.bazel_flags }} //...
