name: Build

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string
            signed:
                required: false
                type: boolean
                default: false

jobs:
    linux_fastbuild:
        name: Linux Fastbuild
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    lld \
                    pkg-config \
                    libglib2.0-dev \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-results-url: ${{ secrets.BAZEL_RESULTS_URL }}
                  bazel-bes-backend: ${{ secrets.BAZEL_BES_BACKEND }}
                  bazel-remote-cache: ${{ secrets.BAZEL_REMOTE_CACHE }}
                  bazel-auth-header: ${{ secrets.BAZEL_AUTH_HEADER }}

            - name: Build Everything
              shell: bash
              run: |
                bazel build --config=fastbuild \
                    //packages/...

            - name: Test Everything
              shell: bash
              run: |
                bazel test --config=fastbuild //packages/... \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

    linux_release:
        name: Linux Release
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    lld \
                    pkg-config \
                    libglib2.0-dev \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-results-url: ${{ secrets.BAZEL_RESULTS_URL }}
                  bazel-bes-backend: ${{ secrets.BAZEL_BES_BACKEND }}
                  bazel-remote-cache: ${{ secrets.BAZEL_REMOTE_CACHE }}
                  bazel-auth-header: ${{ secrets.BAZEL_AUTH_HEADER }}

            - name: Build Web App
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-app:pages

            - name: Test Web App
              shell: bash
              run: |
                bazel test --config=release \
                    //packages/dashql-app/...

            - uses: actions/upload-artifact@v4
              with:
                name: dashql_app_pages
                path: ./bazel-bin/packages/dashql-app/pages/
                retention-days: 1

    macos_release:
        name: MacOS Release
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-results-url: ${{ secrets.BAZEL_RESULTS_URL }}
                  bazel-bes-backend: ${{ secrets.BAZEL_BES_BACKEND }}
                  bazel-remote-cache: ${{ secrets.BAZEL_REMOTE_CACHE }}
                  bazel-auth-header: ${{ secrets.BAZEL_AUTH_HEADER }}

            - name: Build Desktop App
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-native:mac_universal_dmg

            - name: Test Desktop App
              shell: bash
              run: |
                bazel test --config=release \
                    //packages/dashql-native/... \
                    --platforms=//bazel/platforms:aarch64_macos \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

            - name: Sign Desktop App
              if: ${{ inputs.signed }}
              uses: ./.github/actions/sign-macos
              with:
                signing-identity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
                certificate-base64: ${{ secrets.MACOS_DEVELOPER_ID_APPLICATION_BASE64 }}
                certificate-password: ${{ secrets.MACOS_DEVELOPER_ID_APPLICATION_SECRET }}
                notarytool-issuer: ${{ secrets.MACOS_STORE_ISSUER_ID }}
                notarytool-key-id: ${{ secrets.MACOS_STORE_KEY_ID }}
                notarytool-key: ${{ secrets.MACOS_STORE_KEY }}
                updater-signing-key: ${{ secrets.RELEASE_SIGNING_KEY_BASE64 }}
                updater-signing-key-password: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}

            - name: Upload unsigned DMG
              if: ${{ !inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_dmg
                path: ./bazel-bin/packages/dashql-native/DashQL-universal.dmg
                retention-days: 1

            - name: Upload signed DMG
              if: ${{ inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_dmg
                path: ./bazel-bin/packages/dashql-native/DashQL-universal-signed.dmg
                retention-days: 7

            - name: Upload updater bundle
              if: ${{ inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_updater
                path: |
                    ./bazel-bin/packages/dashql-native/DashQL-universal-signed.app.tar.gz
                    ./bazel-bin/packages/dashql-native/DashQL-universal-signed.app.tar.gz.sig
                retention-days: 7
