name: Build

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string
            signed:
                required: false
                type: boolean
                default: false

jobs:
    core_wasm_fastbuild:
        name: Core Wasm Fastbuild
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Build WASM
              shell: bash
              run: |
                bazel build --config=fastbuild \
                    //packages/dashql-core:core_wasm

    core_wasm_release:
        name: Core Wasm Release
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Build WASM
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-core:core_wasm

    compute_wasm_fastbuild:
        name: Compute Wasm Fastbuild
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Build Compute WASM
              shell: bash
              run: |
                bazel build --config=fastbuild \
                    //packages/dashql-compute:dist

    compute_wasm_release:
        name: Compute Wasm Release
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Build Compute WASM
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-compute:dist

    linux_fastbuild:
        name: Linux Fastbuild
        runs-on: ubuntu-24.04
        needs: [core_wasm_fastbuild, compute_wasm_fastbuild]
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    lld \
                    pkg-config \
                    libglib2.0-dev \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Assert WASM is in remote cache
              shell: bash
              run: |
                bazel build --config=fastbuild \
                    --experimental_remote_require_cached \
                    //packages/dashql-core:core_wasm \
                    //packages/dashql-compute:dist

            - name: Build Everything
              shell: bash
              run: |
                bazel build --config=fastbuild \
                    //packages/...

            - name: Test Everything
              shell: bash
              run: |
                bazel test --config=fastbuild //packages/... \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

    linux_release:
        name: Linux Release
        runs-on: ubuntu-24.04
        needs: [core_wasm_release, compute_wasm_release]
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    lld \
                    pkg-config \
                    libglib2.0-dev \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Assert WASM is in remote cache
              shell: bash
              run: |
                bazel build --config=release \
                    --experimental_remote_require_cached \
                    //packages/dashql-core:core_wasm \
                    //packages/dashql-compute:dist

            - name: Build Web App
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/...

            - name: Test Web App
              shell: bash
              run: |
                bazel test --config=release //packages/... \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

            - uses: actions/upload-artifact@v4
              with:
                name: dashql_app_pages
                path: ./bazel-bin/packages/dashql-app/pages/
                retention-days: 1

    macos_aarch64:
        name: MacOS Release Arm
        runs-on: macos-14
        needs: [core_wasm_release, compute_wasm_release]
        steps:
            - name: Free disk space
              shell: bash
              run: |
                sudo rm -rf /Applications/Xcode_1[0-5]*.app || true
                sudo rm -rf /Library/Developer/CoreSimulator/Profiles/Runtimes || true
                sudo rm -rf ~/Library/Android || true
                sudo rm -rf /usr/local/share/dotnet ~/.dotnet || true
                sudo rm -rf /Library/Java/JavaVirtualMachines || true
                brew uninstall --force postgresql@14 postgresql@16 || true
                brew cleanup -s || true
                rm -rf "$(brew --cache)" || true
                df -h /

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Assert WASM is in remote cache
              shell: bash
              run: |
                bazel build --config=release \
                    --experimental_remote_require_cached \
                    //packages/dashql-core:core_wasm \
                    //packages/dashql-compute:dist

            - name: Build aarch64
              shell: bash
              run: |
                bazel build --config=release \
                    --platforms=//bazel/platforms:aarch64_macos \
                    //packages/dashql-native:mac_app_aarch64 \
                    //packages/dashql-native:tests

            - name: Test Desktop App
              shell: bash
              run: |
                bazel test --config=release \
                    --platforms=//bazel/platforms:aarch64_macos \
                    //packages/dashql-native/... \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

    macos_x86_64:
        name: MacOS Release x86
        runs-on: macos-14
        needs: [core_wasm_release, compute_wasm_release]
        steps:
            - name: Free disk space
              shell: bash
              run: |
                sudo rm -rf /Applications/Xcode_1[0-5]*.app || true
                sudo rm -rf /Library/Developer/CoreSimulator/Profiles/Runtimes || true
                sudo rm -rf ~/Library/Android || true
                sudo rm -rf /usr/local/share/dotnet ~/.dotnet || true
                sudo rm -rf /Library/Java/JavaVirtualMachines || true
                brew uninstall --force postgresql@14 postgresql@16 || true
                brew cleanup -s || true
                rm -rf "$(brew --cache)" || true
                df -h /

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Assert WASM is in remote cache
              shell: bash
              run: |
                bazel build --config=release \
                    --experimental_remote_require_cached \
                    //packages/dashql-core:core_wasm \
                    //packages/dashql-compute:dist

            - name: Build x86_64
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-native:mac_app_x86_64

    macos_universal:
        name: MacOS Release Universal
        runs-on: macos-14
        needs: [macos_aarch64, macos_x86_64]
        steps:
            - name: Free disk space
              shell: bash
              run: |
                sudo rm -rf /Applications/Xcode_1[0-5]*.app || true
                sudo rm -rf /Library/Developer/CoreSimulator/Profiles/Runtimes || true
                sudo rm -rf ~/Library/Android || true
                sudo rm -rf /usr/local/share/dotnet ~/.dotnet || true
                sudo rm -rf /Library/Java/JavaVirtualMachines || true
                brew uninstall --force postgresql@14 postgresql@16 || true
                brew cleanup -s || true
                rm -rf "$(brew --cache)" || true
                df -h /

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Assert arch binaries are in remote cache
              shell: bash
              run: |
                bazel build --config=release \
                    --experimental_remote_require_cached \
                    //packages/dashql-native:mac_app_aarch64 \
                    //packages/dashql-native:mac_app_x86_64

            - name: Build unsigned Desktop App
              if: ${{ !inputs.signed }}
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-native:mac_universal_app_bundle \
                    //packages/dashql-native:mac_universal_dmg

            - name: Build Desktop App
              if: ${{ inputs.signed }}
              shell: bash
              run: |
                bazel build --config=release \
                    //packages/dashql-native:mac_universal_app_bundle

            - name: Print disk space
              shell: bash
              run: |
                df -h /
                ls -lisah ./bazel-bin/packages/dashql-native/

            - name: Sign Desktop App
              if: ${{ inputs.signed }}
              uses: ./.github/actions/sign-macos
              with:
                signing-identity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
                certificate-base64: ${{ secrets.MACOS_DEVELOPER_ID_APPLICATION_BASE64 }}
                certificate-password: ${{ secrets.MACOS_DEVELOPER_ID_APPLICATION_SECRET }}
                notarytool-issuer: ${{ secrets.MACOS_STORE_ISSUER_ID }}
                notarytool-key-id: ${{ secrets.MACOS_STORE_KEY_ID }}
                notarytool-key: ${{ secrets.MACOS_STORE_KEY }}
                updater-signing-key: ${{ secrets.RELEASE_SIGNING_KEY_BASE64 }}
                updater-signing-key-password: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}

            - name: Upload unsigned DMG
              if: ${{ !inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_dmg
                path: ./bazel-bin/packages/dashql-native/DashQL-universal.dmg
                retention-days: 1

            - name: Upload signed DMG
              if: ${{ inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_dmg_signed
                path: ${{ runner.temp }}/DashQL-universal-signed.dmg
                retention-days: 7

            - name: Upload updater bundle
              if: ${{ inputs.signed }}
              uses: actions/upload-artifact@v4
              with:
                name: dashql_release_macos_updater_signed
                path: |
                    ./bazel-bin/packages/dashql-native/DashQL-universal-signed.app.tar.gz
                    ./bazel-bin/packages/dashql-native/DashQL-universal-signed.app.tar.gz.sig
                retention-days: 7
