name: Build

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string
            signed:
                required: false
                type: boolean
                default: false

jobs:
    build:
        name: ${{ matrix.job_name }}
        runs-on: ${{ matrix.runs_on }}
        strategy:
            matrix:
                include:
                    - job_id: linux_debug
                      job_name: Linux Debug
                      runs_on: ubuntu-24.04
                      bazel_flags: ""
                    - job_id: linux_release
                      job_name: Linux Release
                      runs_on: ubuntu-24.04
                      bazel_flags: "--config=release"
                    - job_id: mac_release
                      job_name: MacOS Release
                      runs_on: macos-14
                      bazel_flags: "--config=release"
        steps:
            - name: Install apt dependencies
              if: matrix.job_id == 'linux_debug' || matrix.job_id == 'linux_release'
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    lld \
                    pkg-config \
                    libglib2.0-dev \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: bazel-contrib/setup-bazel@0.18.0
              with:
                  bazelisk-cache: true
                  repository-cache: true
                  disk-cache: ${{ github.workflow }}/${{ matrix.job_id }}

            - name: Build DashQL
              shell: bash
              run: |
                bazel build ${{ matrix.bazel_flags }} //packages/...

            - name: Test DashQL
              shell: bash
              run: |
                bazel test ${{ matrix.bazel_flags }} //packages/... \
                    --build_tests_only \
                    --test_output=errors \
                    --test_summary=detailed

#            - uses: actions/upload-artifact@v4
#              if: matrix.job_id == 'mac_release'
#              with:
#                name: dashql_dmg_${{ matrix.job_id }}
#                path: ./bazel-bin/packages/dashql-native/DashQL-universal.dmg
#                retention-days: 1
