name: 'Main'
on:
    push:
    pull_request:
        branches:
            - main

jobs:
    parser_wasm:
        name: Parser WASM
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'
                  fetch-depth: 0

            - name: Install flatbuffers
              shell: bash
              run: sudo apt install flatbuffers

            - name: Generate flatbuffer files
              shell: bash
              run: ./scripts/generate_proto.sh

            - name: Build WASM module
              uses: ankoh/flatsql-ci-env@v0.3
              with:
                  script: |-
                    ./scripts/build_parser_wasm.sh Release