name: 'Main'
on:
    push:
    pull_request:
        branches:
            - main

jobs:
    parser_wasm:
        name: Parser WASM
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'
                  fetch-depth: 0

            - name: Setup flatc
              uses: ./.github/actions/setup-flatc
            - name: Setup wasi-sdk
              uses: ./.github/actions/setup-wasi-sdk
            - name: Setup wabt
              uses: ./.github/actions/setup-wabt

            - name: Generate flatbuffer files
              shell: bash
              run: ./scripts/generate_proto.sh

            - name: Build WASM module
              shell: bash
              run: |
                export WABT_BIN=/opt/wabt
                export WASI_SDK_PREFIX=/opt/wasi
                export WASI_SYSROOT=${WASI_SDK_PREFIX}/share/wasi-sysroot
                export WASI_CMAKE_TOOLCHAIN=${WASI_SDK_PREFIX}/share/cmake/wasi-sdk.cmake
                ./scripts/build_parser_wasm.sh Release