name: 'Main'
on:
    push:
    pull_request:
        branches:
            - main

jobs:
  parser_wasm:
    name: Parser / WASM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup flatc
        uses: ./.github/actions/setup-flatc
      - name: Setup wasi-sdk
        uses: ./.github/actions/setup-wasi-sdk
      - name: Setup wabt
        uses: ./.github/actions/setup-wabt
      - name: Setup binaryen
        uses: ./.github/actions/setup-binaryen

      - name: Generate Flatbuffer files
        shell: bash
        run: ./scripts/generate_proto.sh

      - name: Build WASM module
        shell: bash
        env:
          FLATC: /usr/local/bin/flatc
          BINARYEN_BIN: /opt/binaryen/bin
          WABT_BIN: /opt/wabt/bin
          WASI_SDK_PREFIX: /opt/wasi
          WASI_SYSROOT: /opt/wasi/share/wasi-sysroot
          WASI_CMAKE_TOOLCHAIN: /opt/wasi/share/cmake/wasi-sdk.cmake
        run: |
          ./scripts/build_parser_wasm.sh Release

      - uses: actions/upload-artifact@v3
        with:
          name: flatsql_parser_wasm
          path: ./packages/flatsql-parser/build/wasm/Release/flatsql_parser.wasm
          retention-days: 1

  parser_native_debug:
    name: Parser / Native / Debug
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup flatc
        uses: ./.github/actions/setup-flatc

      - name: Generate Flatbuffer files
        shell: bash
        run: ./scripts/generate_proto.sh

      - name: Compile parser library
        shell: bash
        env:
          PARSER_SOURCE_DIR: ./packages/flatsql-parser
          PARSER_DEBUG_DIR: ./packages/flatsql-parser/build/native/Debug
        run: |
          cmake -S ${PARSER_SOURCE_DIR} -B ${PARSER_DEBUG_DIR} \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          ln -sf ${PARSER_DEBUG_DIR}/compile_commands.json ${PARSER_SOURCE_DIR}/compile_commands.json
          cmake --build ${PARSER_DEBUG_DIR}

      - uses: actions/upload-artifact@v3
        with:
          name: flatsql_parser_native_debug
          path: ./packages/flatsql-parser/build/native/Debug/libflatsql_parser.a
          retention-days: 1

  tests_native_debug:
    name: Tests / Native / Debug
    runs-on: ubuntu-22.04
    needs:
      - parser_native_debug
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: flatsql_parser_native_debug
          path: ./packages/flatsql-parser/build/native/Debug/

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup flatc
        uses: ./.github/actions/setup-flatc

      - name: Generate Flatbuffer files
        shell: bash
        run: ./scripts/generate_proto.sh

      - name: Build FlatSQL tools
        shell: bash
        run: cargo build

      - name: Run ast tests
        shell: bash
        run: cargo test

  js_library:
    name: Library / Javascript
    runs-on: ubuntu-22.04
    needs:
      - parser_wasm
      - tests_native_debug
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0