name: "Main"
on: [push, pull_request]

jobs:
  ubuntu_x86_debug:
    name: Ubuntu / x86 / Debug
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/debug ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh
	        npm --prefix ./proto run build

    - name: Build
      uses: ./ci/image
      with:
        script: |-
          cmake \
              -S./core/cpp/ \
              -B./core/cpp/build/debug \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug
          ccache -s
          make -C./core/cpp/build/debug -j`nproc`
          ccache -s

    - name: Test Core
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/debug/tester ./core/cpp/ \
                --gtest_output=xml:./reports/tests_debug.xml

    - name: Test WebDB
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/debug/duckdb/duckdb_tester \
                --gtest_output=xml:./reports/tests_db_debug.xml

  ubuntu_x86_release:
    name: Ubuntu / x86 / Release
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/release ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build
      uses: ./ci/image
      with:
        script: |-
          cmake \
              -S./core/cpp/ \
              -B./core/cpp/build/release \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Release
          ccache -s
          make -C./core/cpp/build/release -j`nproc`
          ccache -s

    - name: Test Core
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/release/tester ./core/cpp/ \
                --gtest_output=xml:./reports/tests_release.xml

    - name: Test WebDB
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/release/duckdb/duckdb_tester \
                --gtest_output=xml:./reports/tests_db_release.xml

  web:
    name: Web
    runs-on: self-hosted
    needs: ubuntu_x86_debug

    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/wasm/release ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build WASM module
      uses: ./ci/image
      with:
        script: |-
            emcmake cmake \
                -S./core/cpp/ \
                -B./core/cpp/build/wasm/release \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

            emmake make \
                -C./core/cpp/build/wasm/release \
                -j`nproc` \
                dashql_core_web dashql_core_node duckdb_web duckdb_node

            cp ./core/cpp/build/wasm/release/*.wasm ./core/js/src/wasm/
            cp ./core/cpp/build/wasm/release/*.js ./core/js/src/wasm/
            cp ./core/cpp/build/wasm/release/duckdb/*.wasm ./duckdb/js/src/wasm/
            cp ./core/cpp/build/wasm/release/duckdb/*.js ./duckdb/js/src/wasm/

    - name: Build @dashql/core
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            npm --prefix ./core/js ci --cache /mnt/npm_cache
            npm --prefix ./core/js run build

    - name: Test @dashql/core
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            npm --prefix ./core/js run test:ci

    - name: Build @dashql/duckdb
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            npm --prefix ./duckdb/js ci --cache /mnt/npm_cache
            npm --prefix ./duckdb/js run build

    - name: Test @dashql/duckdb
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            npm --prefix ./duckdb/js run test:ci

    - name: Build App
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            npm --prefix ./app ci --cache /mnt/npm_cache
            npm --prefix ./app run build:release
