name: "Main"
on: [push, pull_request]

jobs:
  linux_x86_debug:
    name: Linux / x86 / Debug
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/debug ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build
      uses: ./ci/image
      with:
        script: |-
          cmake \
              -S./core/cpp/ \
              -B./core/cpp/build/debug \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Debug
          ccache -s
          make -C./core/cpp/build/debug -j`nproc`
          ccache -s

    - name: Test Core
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/debug/tester ./core/cpp/ \
                --gtest_output=xml:./reports/tests_debug.xml

    - name: Test WebDB
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/debug/duckdb/duckdb_tester \
                --gtest_output=xml:./reports/tests_db_debug.xml

  linux_x86_coverage:
    name: Linux / x86 / Coverage
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/coverage ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build
      uses: ./ci/image
      with:
        script: |-
          cmake \
              -S./core/cpp/ \
              -B./core/cpp/build/coverage \
              -DCODE_COVERAGE=1 \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Debug
          ccache -s
          make -C./core/cpp/build/coverage -j`nproc`
          ccache -s

    - name: Test Core
      uses: ./ci/image
      with:
        script: |-
            export LLVM_PROFILE_FILE=./core.profraw
            ./core/cpp/build/coverage/tester ./core/cpp/

    - name: Test WebDB
      uses: ./ci/image
      with:
        script: |-
            export LLVM_PROFILE_FILE=./webdb.profraw
            ./core/cpp/build/coverage/duckdb/duckdb_tester

    - name: Code Coverage
      uses: ./ci/image
      with:
        script: |-
            llvm-profdata merge \
                -sparse ./core.profraw ./webdb.profraw \
                -o ./main.profdata
            llvm-cov report ./core/cpp/build/coverage/tester \
                --instr-profile ./main.profdata \
                -ignore-filename-regex submodules

  linux_x86_release:
    name: Linux / x86 / Release
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/release ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build
      uses: ./ci/image
      with:
        script: |-
          cmake \
              -S./core/cpp/ \
              -B./core/cpp/build/release \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Release
          ccache -s
          make -C./core/cpp/build/release -j`nproc`
          ccache -s

    - name: Test Core
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/release/tester ./core/cpp/ \
                --gtest_output=xml:./reports/tests_release.xml

    - name: Test WebDB
      uses: ./ci/image
      with:
        script: |-
            ./core/cpp/build/release/duckdb/duckdb_tester \
                --gtest_output=xml:./reports/tests_db_release.xml

  web:
    name: Web
    runs-on: self-hosted
    needs:
    - linux_x86_debug
    - linux_x86_release
    - linux_x86_coverage
    - plugins

    steps:
    - uses: actions/checkout@v2

    - name: Prepare repository
      uses: ./ci/image
      with:
        script: |-
          make reset_duckdb
          git submodule update --init --recursive
          mkdir -p ./core/cpp/build/wasm/release ./reports

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: Build WASM module
      uses: ./ci/image
      with:
        script: |-
            emcmake cmake \
                -S./core/cpp/ \
                -B./core/cpp/build/wasm/release \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

            emmake make \
                -C./core/cpp/build/wasm/release \
                -j`nproc` \
                core_wasm_web core_wasm_node duckdb_web duckdb_node

            cp ./core/cpp/build/wasm/release/*.wasm ./core/js/src/wasm/
            cp ./core/cpp/build/wasm/release/*.js ./core/js/src/wasm/
            cp ./core/cpp/build/wasm/release/duckdb/*.wasm ./duckdb/js/src/wasm/
            cp ./core/cpp/build/wasm/release/duckdb/*.js ./duckdb/js/src/wasm/

    - name: Build @dashql/proto
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./proto
            npm ci --cache /mnt/npm_cache
            npm run build

    - name: Build @dashql/core
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./core/js
            npm ci --cache /mnt/npm_cache
            npm run build

    - name: Test @dashql/core
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./core/js
            npm run test:ci

    - name: Build @dashql/duckdb
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./duckdb/js
            npm ci --cache /mnt/npm_cache
            npm run build

    - name: Test @dashql/duckdb
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./duckdb/js
            npm run test:ci

    - name: Build App
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./app
            npm ci --cache /mnt/npm_cache
            npm run build:release

  plugins:
    name: Plugins
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Compile flatbuffer schema
      uses: ./ci/image
      with:
        script: |-
            ./scripts/generate_proto.sh

    - name: extract/fortnite-replay
      uses: ./ci/image
      with:
        script: |-
            source /opt/env.sh
            cd ./plugins/extract/fortnite-replay/
            cargo build
            cargo build --target wasm32-unknown-unknown
