name: Main

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build
        uses: ./.github/workflows/build_trusted.yml
        with:
            commit: ${{ github.sha }}
            signed: true
        secrets: inherit

    coverage:
        name: Coverage
        uses: ./.github/workflows/coverage.yml
        with:
            commit: ${{ github.sha }}
        secrets: inherit

    publish:
        name: Publish
        uses: ./.github/workflows/publish.yml
        with:
            commit: ${{ github.sha }}
        needs:
            - build
        secrets: inherit
        permissions:
            contents: read
            pages: write
            id-token: write

