name: Branch

on:
    push:
        branches-ignore:
            - 'main'
            - 'akohn-publish'
            - 'akohn-tauri'

jobs:
    build:
        name: Build
        uses: ./.github/workflows/build_trusted.yml
        with:
            commit: ${{ github.sha }}
            signed: false
        secrets: inherit

    publish:
        name: Publish App
        uses: ./.github/workflows/publish_app.yml
        with:
            commit: ${{ github.sha }}
            branch: ${{ github.ref_name }}
        needs:
            - build
        secrets: inherit
