name: Publish

on:
    workflow_dispatch:
        inputs:
            sha:
                required: true
                type: string

jobs:
    build:
        name: Build
        uses: ./.github/workflows/build.yml
        with:
            sha: github.event.inputs.sha
        secrets: inherit

    test:
        name: Test
        runs-on: ubuntu-22.04
        needs:
            - build

        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: hyper_service_proto
                  path: ./packages/hyper-service/dist
