name: Publish

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string

jobs:
    pages:
        name: GitHub Page
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - uses: actions/download-artifact@v5
              with:
                  name: dashql_pwa_pages
                  path: ./page

            - uses: actions/upload-pages-artifact@v4
              with:
                  path: ./page

            - uses: actions/deploy-pages@v4

    native:
        name: Native apps
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ github.event.inputs.commit || github.sha }}

            - uses: actions/download-artifact@v5
              with:
                  name: dashql_pack_linux
                  path: ${{ github.workspace }}/.bin/

            - uses: actions/download-artifact@v5
              with:
                  name: dashql_native_macos_dmg
                  path: ${{ github.workspace }}/target/universal-apple-darwin/release/bundle/dmg/

            - uses: actions/download-artifact@v5
              with:
                  name: dashql_native_macos_update
                  path: ${{ github.workspace }}/target/release/bundle/macos/

            - name: Freeze DashQL version
              shell: bash
              run: |
                    chmod +x ./.bin/dashql-pack
                    ./.bin/dashql-pack freeze

            - name: Publish native apps
              env:
                DASHQL_GET_R2_ENDPOINT: ${{ secrets.R2_DASHQL_GET_ENDPOINT }}
                DASHQL_GET_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
                DASHQL_GET_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
                DASHQL_RELEASE_SIGNING_KEY_BASE64: ${{ secrets.RELEASE_SIGNING_KEY_BASE64 }}
                DASHQL_RELEASE_SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
              run: |
                    ./.bin/dashql-pack publish --save-summary ./release.json

            - name: Cleanup native app releases
              env:
                DASHQL_GET_R2_ENDPOINT: ${{ secrets.R2_DASHQL_GET_ENDPOINT }}
                DASHQL_GET_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
                DASHQL_GET_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
              run: |
                    ./.bin/dashql-pack vacuum --keep-stable 100 --keep-canary 10

            - name: Publish release metadata through Slack Webhook
              uses: slackapi/slack-github-action@v2.1.1
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload-file-path: "./release.json"
