name: Publish

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    pages:
        name: GitHub Page
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - uses: actions/download-artifact@v8
              with:
                  name: dashql_app_pages
                  path: ${{ runner.temp }}/artifacts/pages

            - uses: actions/upload-pages-artifact@v4
              with:
                  path: ${{ runner.temp }}/artifacts/pages

            - uses: actions/deploy-pages@v5

    native:
        name: Native apps
        runs-on: ubuntu-24.04
        steps:
            - name: Install apt dependencies
              shell: bash
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld

            - uses: actions/checkout@v6
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ inputs.commit || github.sha }}

            - name: Setup Bazel
              uses: ./.github/actions/setup-bazel
              with:
                  bazel-mtls-ca: ${{ secrets.BAZEL_CACHE_MTLS_CA }}
                  bazel-mtls-client-cert: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_CERT }}
                  bazel-mtls-client-key: ${{ secrets.BAZEL_CACHE_MTLS_CLIENT_KEY }}

            - name: Build DashQL Pack
              shell: bash
              run: |
                bazel build --config=release \
                  //packages/dashql-pack:pack

            - uses: actions/download-artifact@v8
              with:
                  name: dashql_macos_dmg_signed
                  path: ${{ runner.temp }}/artifacts/

            - uses: actions/download-artifact@v8
              with:
                  name: dashql_macos_updater_signed
                  path: ${{ runner.temp }}/artifacts/

            - name: Publish native apps
              env:
                DASHQL_GET_R2_ENDPOINT: ${{ secrets.R2_DASHQL_GET_ENDPOINT }}
                DASHQL_GET_R2_ACCESS_KEY_ID: ${{ secrets.R2_DASHQL_GET_ACCESS_KEY_ID }}
                DASHQL_GET_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_DASHQL_GET_SECRET_ACCESS_KEY }}
                DASHQL_RELEASE_SIGNING_KEY_BASE64: ${{ secrets.RELEASE_SIGNING_KEY_BASE64 }}
                DASHQL_RELEASE_SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
              run: |
                bazel run --config=release //packages/dashql-pack:pack -- publish-get \
                  --source-dir $GITHUB_WORKSPACE \
                  --macos-dmg-path ${{ runner.temp }}/artifacts/DashQL-universal-signed.dmg \
                  --macos-updater-bundle-path ${{ runner.temp }}/artifacts/DashQL-universal-signed.app.tar.gz \
                  --macos-updater-signature-path ${{ runner.temp }}/artifacts/DashQL-universal-signed.app.tar.gz.sig \
                  --save-summary ${{ runner.temp }}/release.json

            - name: Cleanup native app releases
              env:
                DASHQL_GET_R2_ENDPOINT: ${{ secrets.R2_DASHQL_GET_ENDPOINT }}
                DASHQL_GET_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
                DASHQL_GET_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
              run: |
                bazel run --config=release //packages/dashql-pack:pack -- vacuum-get --keep-stable 100 --keep-canary 10

            - name: Publish release metadata through Slack Webhook
              uses: slackapi/slack-github-action@v3.0.1
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload-file-path: "${{ runner.temp }}/release.json"
