name: Branch

on:
    push:
        branches-ignore:
            - 'main'
            - 'renovate/*'
            - 'akohn-publish'
            - 'akohn-tauri'

jobs:
    build:
        name: Build
        uses: ./.github/workflows/build.yml
        with:
            commit: github.event.inputs.sha
            signed: false
        secrets: inherit

    coverage:
        name: Collect Coverage Report
        runs-on: ubuntu-24.04
        needs:
            - build
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
                  fetch-depth: 0
                  ref: ${{ github.event.inputs.sha || github.sha }}

            - uses: actions/download-artifact@v5
              with:
                  name: dashql_coverage_native_o0
                  path: ./packages/dashql-core/build/coverage/

            - uses: actions/download-artifact@v5
              with:
                  name: dashql_coverage_js
                  path: ./packages/dashql-core-bindings/coverage/

            - name: Upload coverage report
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
