name: Renovate

# Instructions can be found here:
# https://github.com/renovatebot/github-action

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Override default log level'
                required: false
                default: 'info'
                type: string
            overrideSchedule:
                description: 'Override all schedules'
                required: false
                default: 'false'
                type: string

    # Run renovate at 5 and 6 in the morning (7, 8 CEST), every day
    # We run twice to trigger auto-merges of the first round.
    schedule:
        - cron: '0 5,6 * * *'

concurrency: renovate
jobs:
    renovate:
        name: 'Renovate'
        runs-on: ubuntu-latest
        steps:
            - name: Get token
              id: get_token
              uses: tibdex/github-app-token@v2
              with:
                  private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
                  app_id: ${{ secrets.RENOVATE_APP_ID }}

            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'
                  fetch-depth: 0

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@42c1d3cb1d1ca891765626ba71cdff5e757258de # v40.0.2
              env:
                  # Repository taken from variable to keep configuration file generic
                  RENOVATE_REPOSITORIES: ${{ github.repository }}
                  # Onboarding not needed for self hosted
                  RENOVATE_ONBOARDING: 'false'
                  # Username for GitHub authentication (should match GitHub App name + [bot])
                  RENOVATE_USERNAME: 'sqlynx-renovate[bot]'
                  # Git commit author used, must match GitHub App
                  # Get user-id from https://api.github.com/users/sqlynx-renovate[bot]
                  RENOVATE_GIT_AUTHOR: 'SQLynx Renovate Bot <138368581+sqlynx-renovate[bot]@users.noreply.github.com>'
                  # Use GitHub API to create commits (this allows for signed commits from GitHub App)
                  RENOVATE_PLATFORM_COMMIT: 'true'
                  # Override schedule if set
                  RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
                  # Renovate logging
                  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
              with:
                  configurationFile: .github/renovate.json
                  token: '${{ steps.get_token.outputs.token }}'
