#cloud-config

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - git
  - curl
  - jq

  - build-essential
  - git
  - ccache
  - cmake
  - ninja-build
  - clang
  - clang-tidy
  - curl
  - python
  - python3
  - bison
  - flex
  - openjdk-14-jdk
  - libpthread-stubs0-dev
  - libboost-all-dev

users:
 - name: actions
   homedir: /home/actions
   lock_passwd: true
   sudo: False

runcmd:
  - export ACTIONS_VERSION="v2.274.1"
  - export EMSDK_VERSION="2.0.4"
  - export NVM_DIR=/usr/local/nvm
  - export NVM_VERSION="v0.36.0"
  - export NODE_VERSION="v14.13.0"

  - mkdir -p /usr/local/actions-runner && cd ./usr/local/actions-runner
  - curl -o runner.tgz -L https://github.com/actions/runner/releases/download/${ACTIONS_VERSION}/actions-runner-linux-x64-${ACTIONS_VERSION}.tar.gz
  - tar -xzf ./runner.tgz
  - chown -R actions:actions .
  - ./installdependencies.sh
  - rm ./runner.tgz

  - mkdir -p /usr/local/emsdk && cd /usr/local/emsdk
  - curl -SL https://github.com/emscripten-core/emsdk/archive/${EMSDK_VERSION}.tar.gz | tar -xz --strip-components=1
  - ./emsdk install latest
  - ./emsdk activate latest
  - /bin/bash ./emsdk_env.sh
  - rm -rf ./emscripten/tag-*/tests
  - rm -rf ./emscripten/tag-*/site
  - rm -rf ./emscripten/tag-*/docs
  - rm -rf ./zips
  - find . -name "*.o" -exec rm {} \;
  - find . -name "*.a" -exec rm {} \;
  - find . -name "*.tmp" -exec rm {} \;

  - mkdir -p /usr/local/nvm
  - curl https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash
  - source /usr/local/nvm/nvm.sh
  - nvm install ${NODE_VERSION}
  - nvm alias default ${NODE_VERSION}
  - nvm use default

  - cd /home/actions
  - source /usr/local/emsdk/emsdk_env.sh
  - echo "PATH=$PATH" >> ./env.sh
  - echo "EMSDK=$EMSDK" >> ./env.sh
  - echo "EM_CONFIG=$EM_CONFIG" >> ./env.sh
  - echo "EM_CACHE=/home/actions/.emscripten_cache/" >> ./env.sh
  - echo "EMSCRIPTEN=$EMSCRIPTEN" >> ./env.sh
  - echo "source /usr/local/nvm/nvm.sh" >> ./env.sh
  - chown actions:actions ./env.sh

  - sudo ufw allow ssh
  - sudo ufw allow out to 192.168.178.1
  - sudo ufw allow out to 192.168.122.1
  - sudo ufw reject out to 192.168.0.0/16
  - sudo ufw enable
  - sudo ufw reload

  - mkdir -p /home/actions/.emscripten_cache /home/actions/.npm_cache /home/actions/.ccache
  - chown -R actions:actions /home/actions/.emscripten_cache /home/actions/.npm_cache /home/actions/.ccache
